// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bilibili/playershared/playershared.proto

// Protobuf Java Version: 4.26.1
package bilibili.playershared;

public interface BottomDisplayOrBuilder extends
    // @@protoc_insertion_point(interface_extends:bilibili.playershared.BottomDisplay)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * </pre>
   *
   * <code>.bilibili.playershared.TextInfo title = 1;</code>
   * @return Whether the title field is set.
   */
  boolean hasTitle();
  /**
   * <pre>
   * </pre>
   *
   * <code>.bilibili.playershared.TextInfo title = 1;</code>
   * @return The title.
   */
  bilibili.playershared.TextInfo getTitle();
  /**
   * <pre>
   * </pre>
   *
   * <code>.bilibili.playershared.TextInfo title = 1;</code>
   */
  bilibili.playershared.TextInfoOrBuilder getTitleOrBuilder();

  /**
   * <pre>
   * </pre>
   *
   * <code>string icon = 2;</code>
   * @return The icon.
   */
  java.lang.String getIcon();
  /**
   * <pre>
   * </pre>
   *
   * <code>string icon = 2;</code>
   * @return The bytes for icon.
   */
  com.google.protobuf.ByteString
      getIconBytes();
}
