// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bilibili/account/fission/v1/fission.proto

// Protobuf Java Version: 4.26.1
package bilibili.account.fission.v1;

public interface EntranceReqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:bilibili.account.fission.v1.EntranceReq)
    com.google.protobuf.MessageOrBuilder {
}
