// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: bilibili/web/interfaces/v1/interfaces.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package bilibili.web.interfaces.v1;

@kotlin.jvm.JvmName("-initializedimension")
public inline fun dimension(block: bilibili.web.interfaces.v1.DimensionKt.Dsl.() -> kotlin.Unit): bilibili.web.interfaces.v1.Dimension =
  bilibili.web.interfaces.v1.DimensionKt.Dsl._create(bilibili.web.interfaces.v1.Dimension.newBuilder()).apply { block() }._build()
/**
 * ```
 * ```
 *
 * Protobuf type `bilibili.web.interfaces.v1.Dimension`
 */
public object DimensionKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: bilibili.web.interfaces.v1.Dimension.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: bilibili.web.interfaces.v1.Dimension.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): bilibili.web.interfaces.v1.Dimension = _builder.build()

    /**
     * ```
     * ```
     *
     * `int64 width = 1;`
     */
    public var width: kotlin.Long
      @JvmName("getWidth")
      get() = _builder.getWidth()
      @JvmName("setWidth")
      set(value) {
        _builder.setWidth(value)
      }
    /**
     * ```
     * ```
     *
     * `int64 width = 1;`
     */
    public fun clearWidth() {
      _builder.clearWidth()
    }

    /**
     * ```
     * ```
     *
     * `int64 height = 2;`
     */
    public var height: kotlin.Long
      @JvmName("getHeight")
      get() = _builder.getHeight()
      @JvmName("setHeight")
      set(value) {
        _builder.setHeight(value)
      }
    /**
     * ```
     * ```
     *
     * `int64 height = 2;`
     */
    public fun clearHeight() {
      _builder.clearHeight()
    }

    /**
     * ```
     * ```
     *
     * `int64 rotate = 3;`
     */
    public var rotate: kotlin.Long
      @JvmName("getRotate")
      get() = _builder.getRotate()
      @JvmName("setRotate")
      set(value) {
        _builder.setRotate(value)
      }
    /**
     * ```
     * ```
     *
     * `int64 rotate = 3;`
     */
    public fun clearRotate() {
      _builder.clearRotate()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun bilibili.web.interfaces.v1.Dimension.copy(block: `bilibili.web.interfaces.v1`.DimensionKt.Dsl.() -> kotlin.Unit): bilibili.web.interfaces.v1.Dimension =
  `bilibili.web.interfaces.v1`.DimensionKt.Dsl._create(this.toBuilder()).apply { block() }._build()

