// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: bilibili/web/interfaces/v1/interfaces.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package bilibili.web.interfaces.v1;

@kotlin.jvm.JvmName("-initializeliveTimeline")
public inline fun liveTimeline(block: bilibili.web.interfaces.v1.LiveTimelineKt.Dsl.() -> kotlin.Unit): bilibili.web.interfaces.v1.LiveTimeline =
  bilibili.web.interfaces.v1.LiveTimelineKt.Dsl._create(bilibili.web.interfaces.v1.LiveTimeline.newBuilder()).apply { block() }._build()
/**
 * ```
 * ```
 *
 * Protobuf type `bilibili.web.interfaces.v1.LiveTimeline`
 */
public object LiveTimelineKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: bilibili.web.interfaces.v1.LiveTimeline.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: bilibili.web.interfaces.v1.LiveTimeline.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): bilibili.web.interfaces.v1.LiveTimeline = _builder.build()

    /**
     * ```
     * ```
     *
     * `string name = 1;`
     */
    public var name: kotlin.String
      @JvmName("getName")
      get() = _builder.getName()
      @JvmName("setName")
      set(value) {
        _builder.setName(value)
      }
    /**
     * ```
     * ```
     *
     * `string name = 1;`
     */
    public fun clearName() {
      _builder.clearName()
    }

    /**
     * ```
     * ```
     *
     * `int64 start_time = 2;`
     */
    public var startTime: kotlin.Long
      @JvmName("getStartTime")
      get() = _builder.getStartTime()
      @JvmName("setStartTime")
      set(value) {
        _builder.setStartTime(value)
      }
    /**
     * ```
     * ```
     *
     * `int64 start_time = 2;`
     */
    public fun clearStartTime() {
      _builder.clearStartTime()
    }

    /**
     * ```
     * ```
     *
     * `int64 end_time = 3;`
     */
    public var endTime: kotlin.Long
      @JvmName("getEndTime")
      get() = _builder.getEndTime()
      @JvmName("setEndTime")
      set(value) {
        _builder.setEndTime(value)
      }
    /**
     * ```
     * ```
     *
     * `int64 end_time = 3;`
     */
    public fun clearEndTime() {
      _builder.clearEndTime()
    }

    /**
     * ```
     * ```
     *
     * `string cover = 4;`
     */
    public var cover: kotlin.String
      @JvmName("getCover")
      get() = _builder.getCover()
      @JvmName("setCover")
      set(value) {
        _builder.setCover(value)
      }
    /**
     * ```
     * ```
     *
     * `string cover = 4;`
     */
    public fun clearCover() {
      _builder.clearCover()
    }

    /**
     * ```
     * ```
     *
     * `string subtitle = 5;`
     */
    public var subtitle: kotlin.String
      @JvmName("getSubtitle")
      get() = _builder.getSubtitle()
      @JvmName("setSubtitle")
      set(value) {
        _builder.setSubtitle(value)
      }
    /**
     * ```
     * ```
     *
     * `string subtitle = 5;`
     */
    public fun clearSubtitle() {
      _builder.clearSubtitle()
    }

    /**
     * ```
     * ```
     *
     * `string h5_cover = 6;`
     */
    public var h5Cover: kotlin.String
      @JvmName("getH5Cover")
      get() = _builder.getH5Cover()
      @JvmName("setH5Cover")
      set(value) {
        _builder.setH5Cover(value)
      }
    /**
     * ```
     * ```
     *
     * `string h5_cover = 6;`
     */
    public fun clearH5Cover() {
      _builder.clearH5Cover()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun bilibili.web.interfaces.v1.LiveTimeline.copy(block: `bilibili.web.interfaces.v1`.LiveTimelineKt.Dsl.() -> kotlin.Unit): bilibili.web.interfaces.v1.LiveTimeline =
  `bilibili.web.interfaces.v1`.LiveTimelineKt.Dsl._create(this.toBuilder()).apply { block() }._build()

