// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: bilibili/web/interfaces/v1/interfaces.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package bilibili.web.interfaces.v1;

@kotlin.jvm.JvmName("-initializereplyVote")
public inline fun replyVote(block: bilibili.web.interfaces.v1.ReplyVoteKt.Dsl.() -> kotlin.Unit): bilibili.web.interfaces.v1.ReplyVote =
  bilibili.web.interfaces.v1.ReplyVoteKt.Dsl._create(bilibili.web.interfaces.v1.ReplyVote.newBuilder()).apply { block() }._build()
/**
 * ```
 * ```
 *
 * Protobuf type `bilibili.web.interfaces.v1.ReplyVote`
 */
public object ReplyVoteKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: bilibili.web.interfaces.v1.ReplyVote.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: bilibili.web.interfaces.v1.ReplyVote.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): bilibili.web.interfaces.v1.ReplyVote = _builder.build()

    /**
     * ```
     * ```
     *
     * `int64 id = 1;`
     */
    public var id: kotlin.Long
      @JvmName("getId")
      get() = _builder.getId()
      @JvmName("setId")
      set(value) {
        _builder.setId(value)
      }
    /**
     * ```
     * ```
     *
     * `int64 id = 1;`
     */
    public fun clearId() {
      _builder.clearId()
    }

    /**
     * ```
     * ```
     *
     * `string title = 2;`
     */
    public var title: kotlin.String
      @JvmName("getTitle")
      get() = _builder.getTitle()
      @JvmName("setTitle")
      set(value) {
        _builder.setTitle(value)
      }
    /**
     * ```
     * ```
     *
     * `string title = 2;`
     */
    public fun clearTitle() {
      _builder.clearTitle()
    }

    /**
     * ```
     * ```
     *
     * `int32 cnt = 3;`
     */
    public var cnt: kotlin.Int
      @JvmName("getCnt")
      get() = _builder.getCnt()
      @JvmName("setCnt")
      set(value) {
        _builder.setCnt(value)
      }
    /**
     * ```
     * ```
     *
     * `int32 cnt = 3;`
     */
    public fun clearCnt() {
      _builder.clearCnt()
    }

    /**
     * ```
     * ```
     *
     * `string desc = 4;`
     */
    public var desc: kotlin.String
      @JvmName("getDesc")
      get() = _builder.getDesc()
      @JvmName("setDesc")
      set(value) {
        _builder.setDesc(value)
      }
    /**
     * ```
     * ```
     *
     * `string desc = 4;`
     */
    public fun clearDesc() {
      _builder.clearDesc()
    }

    /**
     * ```
     * ```
     *
     * `bool deleted = 5;`
     */
    public var deleted: kotlin.Boolean
      @JvmName("getDeleted")
      get() = _builder.getDeleted()
      @JvmName("setDeleted")
      set(value) {
        _builder.setDeleted(value)
      }
    /**
     * ```
     * ```
     *
     * `bool deleted = 5;`
     */
    public fun clearDeleted() {
      _builder.clearDeleted()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun bilibili.web.interfaces.v1.ReplyVote.copy(block: `bilibili.web.interfaces.v1`.ReplyVoteKt.Dsl.() -> kotlin.Unit): bilibili.web.interfaces.v1.ReplyVote =
  `bilibili.web.interfaces.v1`.ReplyVoteKt.Dsl._create(this.toBuilder()).apply { block() }._build()

