// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: bilibili/dynamic/gw/gateway.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package bilibili.dynamic.gateway;

@kotlin.jvm.JvmName("-initializeinfoOGV")
public inline fun infoOGV(block: bilibili.dynamic.gateway.InfoOGVKt.Dsl.() -> kotlin.Unit): bilibili.dynamic.gateway.InfoOGV =
  bilibili.dynamic.gateway.InfoOGVKt.Dsl._create(bilibili.dynamic.gateway.InfoOGV.newBuilder()).apply { block() }._build()
/**
 * ```
 * 动态-拓展小卡模块-ogv小卡-(one of 片单、榜单、分区)
 * ```
 *
 * Protobuf type `bilibili.dynamic.gateway.InfoOGV`
 */
public object InfoOGVKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: bilibili.dynamic.gateway.InfoOGV.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: bilibili.dynamic.gateway.InfoOGV.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): bilibili.dynamic.gateway.InfoOGV = _builder.build()

    /**
     * ```
     * 标题
     * ```
     *
     * `string title = 1;`
     */
    public var title: kotlin.String
      @JvmName("getTitle")
      get() = _builder.getTitle()
      @JvmName("setTitle")
      set(value) {
        _builder.setTitle(value)
      }
    /**
     * ```
     * 标题
     * ```
     *
     * `string title = 1;`
     */
    public fun clearTitle() {
      _builder.clearTitle()
    }

    /**
     * ```
     * 跳转地址
     * ```
     *
     * `string uri = 2;`
     */
    public var uri: kotlin.String
      @JvmName("getUri")
      get() = _builder.getUri()
      @JvmName("setUri")
      set(value) {
        _builder.setUri(value)
      }
    /**
     * ```
     * 跳转地址
     * ```
     *
     * `string uri = 2;`
     */
    public fun clearUri() {
      _builder.clearUri()
    }

    /**
     * ```
     * 小图标
     * ```
     *
     * `string icon = 3;`
     */
    public var icon: kotlin.String
      @JvmName("getIcon")
      get() = _builder.getIcon()
      @JvmName("setIcon")
      set(value) {
        _builder.setIcon(value)
      }
    /**
     * ```
     * 小图标
     * ```
     *
     * `string icon = 3;`
     */
    public fun clearIcon() {
      _builder.clearIcon()
    }

    /**
     * ```
     * 客户端埋点用
     * ```
     *
     * `string sub_module = 4;`
     */
    public var subModule: kotlin.String
      @JvmName("getSubModule")
      get() = _builder.getSubModule()
      @JvmName("setSubModule")
      set(value) {
        _builder.setSubModule(value)
      }
    /**
     * ```
     * 客户端埋点用
     * ```
     *
     * `string sub_module = 4;`
     */
    public fun clearSubModule() {
      _builder.clearSubModule()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun bilibili.dynamic.gateway.InfoOGV.copy(block: `bilibili.dynamic.gateway`.InfoOGVKt.Dsl.() -> kotlin.Unit): bilibili.dynamic.gateway.InfoOGV =
  `bilibili.dynamic.gateway`.InfoOGVKt.Dsl._create(this.toBuilder()).apply { block() }._build()

