// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: bilibili/dynamic/gw/gateway.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package bilibili.dynamic.gateway;

@kotlin.jvm.JvmName("-initializemoduleDynamic")
public inline fun moduleDynamic(block: bilibili.dynamic.gateway.ModuleDynamicKt.Dsl.() -> kotlin.Unit): bilibili.dynamic.gateway.ModuleDynamic =
  bilibili.dynamic.gateway.ModuleDynamicKt.Dsl._create(bilibili.dynamic.gateway.ModuleDynamic.newBuilder()).apply { block() }._build()
/**
 * ```
 * 动态-详情模块
 * ```
 *
 * Protobuf type `bilibili.dynamic.gateway.ModuleDynamic`
 */
public object ModuleDynamicKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: bilibili.dynamic.gateway.ModuleDynamic.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: bilibili.dynamic.gateway.ModuleDynamic.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): bilibili.dynamic.gateway.ModuleDynamic = _builder.build()

    /**
     * ```
     * 类型
     * ```
     *
     * `.bilibili.dynamic.gateway.ModuleDynamicType type = 1;`
     */
    public var type: bilibili.dynamic.gateway.ModuleDynamicType
      @JvmName("getType")
      get() = _builder.getType()
      @JvmName("setType")
      set(value) {
        _builder.setType(value)
      }
    public var typeValue: kotlin.Int
      @JvmName("getTypeValue")
      get() = _builder.getTypeValue()
      @JvmName("setTypeValue")
      set(value) {
        _builder.setTypeValue(value)
      }
    /**
     * ```
     * 类型
     * ```
     *
     * `.bilibili.dynamic.gateway.ModuleDynamicType type = 1;`
     */
    public fun clearType() {
      _builder.clearType()
    }

    /**
     * ```
     * 稿件
     * ```
     *
     * `.bilibili.dynamic.gateway.MdlDynArchive dyn_archive = 2;`
     */
    public var dynArchive: bilibili.dynamic.gateway.MdlDynArchive
      @JvmName("getDynArchive")
      get() = _builder.getDynArchive()
      @JvmName("setDynArchive")
      set(value) {
        _builder.setDynArchive(value)
      }
    /**
     * ```
     * 稿件
     * ```
     *
     * `.bilibili.dynamic.gateway.MdlDynArchive dyn_archive = 2;`
     */
    public fun clearDynArchive() {
      _builder.clearDynArchive()
    }
    /**
     * ```
     * 稿件
     * ```
     *
     * `.bilibili.dynamic.gateway.MdlDynArchive dyn_archive = 2;`
     * @return Whether the dynArchive field is set.
     */
    public fun hasDynArchive(): kotlin.Boolean {
      return _builder.hasDynArchive()
    }

    /**
     * ```
     * pgc
     * ```
     *
     * `.bilibili.dynamic.gateway.MdlDynPGC dyn_pgc = 3;`
     */
    public var dynPgc: bilibili.dynamic.gateway.MdlDynPGC
      @JvmName("getDynPgc")
      get() = _builder.getDynPgc()
      @JvmName("setDynPgc")
      set(value) {
        _builder.setDynPgc(value)
      }
    /**
     * ```
     * pgc
     * ```
     *
     * `.bilibili.dynamic.gateway.MdlDynPGC dyn_pgc = 3;`
     */
    public fun clearDynPgc() {
      _builder.clearDynPgc()
    }
    /**
     * ```
     * pgc
     * ```
     *
     * `.bilibili.dynamic.gateway.MdlDynPGC dyn_pgc = 3;`
     * @return Whether the dynPgc field is set.
     */
    public fun hasDynPgc(): kotlin.Boolean {
      return _builder.hasDynPgc()
    }

    /**
     * ```
     * 付费课程-系列
     * ```
     *
     * `.bilibili.dynamic.gateway.MdlDynCourSeason dyn_cour_season = 4;`
     */
    public var dynCourSeason: bilibili.dynamic.gateway.MdlDynCourSeason
      @JvmName("getDynCourSeason")
      get() = _builder.getDynCourSeason()
      @JvmName("setDynCourSeason")
      set(value) {
        _builder.setDynCourSeason(value)
      }
    /**
     * ```
     * 付费课程-系列
     * ```
     *
     * `.bilibili.dynamic.gateway.MdlDynCourSeason dyn_cour_season = 4;`
     */
    public fun clearDynCourSeason() {
      _builder.clearDynCourSeason()
    }
    /**
     * ```
     * 付费课程-系列
     * ```
     *
     * `.bilibili.dynamic.gateway.MdlDynCourSeason dyn_cour_season = 4;`
     * @return Whether the dynCourSeason field is set.
     */
    public fun hasDynCourSeason(): kotlin.Boolean {
      return _builder.hasDynCourSeason()
    }

    /**
     * ```
     * 付费课程-批次
     * ```
     *
     * `.bilibili.dynamic.gateway.MdlDynCourBatch dyn_cour_batch = 5;`
     */
    public var dynCourBatch: bilibili.dynamic.gateway.MdlDynCourBatch
      @JvmName("getDynCourBatch")
      get() = _builder.getDynCourBatch()
      @JvmName("setDynCourBatch")
      set(value) {
        _builder.setDynCourBatch(value)
      }
    /**
     * ```
     * 付费课程-批次
     * ```
     *
     * `.bilibili.dynamic.gateway.MdlDynCourBatch dyn_cour_batch = 5;`
     */
    public fun clearDynCourBatch() {
      _builder.clearDynCourBatch()
    }
    /**
     * ```
     * 付费课程-批次
     * ```
     *
     * `.bilibili.dynamic.gateway.MdlDynCourBatch dyn_cour_batch = 5;`
     * @return Whether the dynCourBatch field is set.
     */
    public fun hasDynCourBatch(): kotlin.Boolean {
      return _builder.hasDynCourBatch()
    }

    /**
     * ```
     * 转发卡
     * ```
     *
     * `.bilibili.dynamic.gateway.MdlDynForward dyn_forward = 6;`
     */
    public var dynForward: bilibili.dynamic.gateway.MdlDynForward
      @JvmName("getDynForward")
      get() = _builder.getDynForward()
      @JvmName("setDynForward")
      set(value) {
        _builder.setDynForward(value)
      }
    /**
     * ```
     * 转发卡
     * ```
     *
     * `.bilibili.dynamic.gateway.MdlDynForward dyn_forward = 6;`
     */
    public fun clearDynForward() {
      _builder.clearDynForward()
    }
    /**
     * ```
     * 转发卡
     * ```
     *
     * `.bilibili.dynamic.gateway.MdlDynForward dyn_forward = 6;`
     * @return Whether the dynForward field is set.
     */
    public fun hasDynForward(): kotlin.Boolean {
      return _builder.hasDynForward()
    }

    /**
     * ```
     * 图文
     * ```
     *
     * `.bilibili.dynamic.gateway.MdlDynDraw dyn_draw = 7;`
     */
    public var dynDraw: bilibili.dynamic.gateway.MdlDynDraw
      @JvmName("getDynDraw")
      get() = _builder.getDynDraw()
      @JvmName("setDynDraw")
      set(value) {
        _builder.setDynDraw(value)
      }
    /**
     * ```
     * 图文
     * ```
     *
     * `.bilibili.dynamic.gateway.MdlDynDraw dyn_draw = 7;`
     */
    public fun clearDynDraw() {
      _builder.clearDynDraw()
    }
    /**
     * ```
     * 图文
     * ```
     *
     * `.bilibili.dynamic.gateway.MdlDynDraw dyn_draw = 7;`
     * @return Whether the dynDraw field is set.
     */
    public fun hasDynDraw(): kotlin.Boolean {
      return _builder.hasDynDraw()
    }

    /**
     * ```
     * 专栏
     * ```
     *
     * `.bilibili.dynamic.gateway.MdlDynArticle dyn_article = 8;`
     */
    public var dynArticle: bilibili.dynamic.gateway.MdlDynArticle
      @JvmName("getDynArticle")
      get() = _builder.getDynArticle()
      @JvmName("setDynArticle")
      set(value) {
        _builder.setDynArticle(value)
      }
    /**
     * ```
     * 专栏
     * ```
     *
     * `.bilibili.dynamic.gateway.MdlDynArticle dyn_article = 8;`
     */
    public fun clearDynArticle() {
      _builder.clearDynArticle()
    }
    /**
     * ```
     * 专栏
     * ```
     *
     * `.bilibili.dynamic.gateway.MdlDynArticle dyn_article = 8;`
     * @return Whether the dynArticle field is set.
     */
    public fun hasDynArticle(): kotlin.Boolean {
      return _builder.hasDynArticle()
    }

    /**
     * ```
     * 音频
     * ```
     *
     * `.bilibili.dynamic.gateway.MdlDynMusic dyn_music = 9;`
     */
    public var dynMusic: bilibili.dynamic.gateway.MdlDynMusic
      @JvmName("getDynMusic")
      get() = _builder.getDynMusic()
      @JvmName("setDynMusic")
      set(value) {
        _builder.setDynMusic(value)
      }
    /**
     * ```
     * 音频
     * ```
     *
     * `.bilibili.dynamic.gateway.MdlDynMusic dyn_music = 9;`
     */
    public fun clearDynMusic() {
      _builder.clearDynMusic()
    }
    /**
     * ```
     * 音频
     * ```
     *
     * `.bilibili.dynamic.gateway.MdlDynMusic dyn_music = 9;`
     * @return Whether the dynMusic field is set.
     */
    public fun hasDynMusic(): kotlin.Boolean {
      return _builder.hasDynMusic()
    }

    /**
     * ```
     * 通用卡方
     * ```
     *
     * `.bilibili.dynamic.gateway.MdlDynCommon dyn_common = 10;`
     */
    public var dynCommon: bilibili.dynamic.gateway.MdlDynCommon
      @JvmName("getDynCommon")
      get() = _builder.getDynCommon()
      @JvmName("setDynCommon")
      set(value) {
        _builder.setDynCommon(value)
      }
    /**
     * ```
     * 通用卡方
     * ```
     *
     * `.bilibili.dynamic.gateway.MdlDynCommon dyn_common = 10;`
     */
    public fun clearDynCommon() {
      _builder.clearDynCommon()
    }
    /**
     * ```
     * 通用卡方
     * ```
     *
     * `.bilibili.dynamic.gateway.MdlDynCommon dyn_common = 10;`
     * @return Whether the dynCommon field is set.
     */
    public fun hasDynCommon(): kotlin.Boolean {
      return _builder.hasDynCommon()
    }

    /**
     * ```
     * 直播卡
     * ```
     *
     * `.bilibili.dynamic.gateway.MdlDynLive dyn_common_live = 11;`
     */
    public var dynCommonLive: bilibili.dynamic.gateway.MdlDynLive
      @JvmName("getDynCommonLive")
      get() = _builder.getDynCommonLive()
      @JvmName("setDynCommonLive")
      set(value) {
        _builder.setDynCommonLive(value)
      }
    /**
     * ```
     * 直播卡
     * ```
     *
     * `.bilibili.dynamic.gateway.MdlDynLive dyn_common_live = 11;`
     */
    public fun clearDynCommonLive() {
      _builder.clearDynCommonLive()
    }
    /**
     * ```
     * 直播卡
     * ```
     *
     * `.bilibili.dynamic.gateway.MdlDynLive dyn_common_live = 11;`
     * @return Whether the dynCommonLive field is set.
     */
    public fun hasDynCommonLive(): kotlin.Boolean {
      return _builder.hasDynCommonLive()
    }

    /**
     * ```
     * 播单
     * ```
     *
     * `.bilibili.dynamic.gateway.MdlDynMedialist dyn_medialist = 12;`
     */
    public var dynMedialist: bilibili.dynamic.gateway.MdlDynMedialist
      @JvmName("getDynMedialist")
      get() = _builder.getDynMedialist()
      @JvmName("setDynMedialist")
      set(value) {
        _builder.setDynMedialist(value)
      }
    /**
     * ```
     * 播单
     * ```
     *
     * `.bilibili.dynamic.gateway.MdlDynMedialist dyn_medialist = 12;`
     */
    public fun clearDynMedialist() {
      _builder.clearDynMedialist()
    }
    /**
     * ```
     * 播单
     * ```
     *
     * `.bilibili.dynamic.gateway.MdlDynMedialist dyn_medialist = 12;`
     * @return Whether the dynMedialist field is set.
     */
    public fun hasDynMedialist(): kotlin.Boolean {
      return _builder.hasDynMedialist()
    }

    /**
     * ```
     * 小程序卡
     * ```
     *
     * `.bilibili.dynamic.gateway.MdlDynApplet dyn_applet = 13;`
     */
    public var dynApplet: bilibili.dynamic.gateway.MdlDynApplet
      @JvmName("getDynApplet")
      get() = _builder.getDynApplet()
      @JvmName("setDynApplet")
      set(value) {
        _builder.setDynApplet(value)
      }
    /**
     * ```
     * 小程序卡
     * ```
     *
     * `.bilibili.dynamic.gateway.MdlDynApplet dyn_applet = 13;`
     */
    public fun clearDynApplet() {
      _builder.clearDynApplet()
    }
    /**
     * ```
     * 小程序卡
     * ```
     *
     * `.bilibili.dynamic.gateway.MdlDynApplet dyn_applet = 13;`
     * @return Whether the dynApplet field is set.
     */
    public fun hasDynApplet(): kotlin.Boolean {
      return _builder.hasDynApplet()
    }

    /**
     * ```
     * 订阅卡
     * ```
     *
     * `.bilibili.dynamic.gateway.MdlDynSubscription dyn_subscription = 14;`
     */
    public var dynSubscription: bilibili.dynamic.gateway.MdlDynSubscription
      @JvmName("getDynSubscription")
      get() = _builder.getDynSubscription()
      @JvmName("setDynSubscription")
      set(value) {
        _builder.setDynSubscription(value)
      }
    /**
     * ```
     * 订阅卡
     * ```
     *
     * `.bilibili.dynamic.gateway.MdlDynSubscription dyn_subscription = 14;`
     */
    public fun clearDynSubscription() {
      _builder.clearDynSubscription()
    }
    /**
     * ```
     * 订阅卡
     * ```
     *
     * `.bilibili.dynamic.gateway.MdlDynSubscription dyn_subscription = 14;`
     * @return Whether the dynSubscription field is set.
     */
    public fun hasDynSubscription(): kotlin.Boolean {
      return _builder.hasDynSubscription()
    }

    /**
     * ```
     * 直播推荐卡
     * ```
     *
     * `.bilibili.dynamic.gateway.MdlDynLiveRcmd dyn_live_rcmd = 15;`
     */
    public var dynLiveRcmd: bilibili.dynamic.gateway.MdlDynLiveRcmd
      @JvmName("getDynLiveRcmd")
      get() = _builder.getDynLiveRcmd()
      @JvmName("setDynLiveRcmd")
      set(value) {
        _builder.setDynLiveRcmd(value)
      }
    /**
     * ```
     * 直播推荐卡
     * ```
     *
     * `.bilibili.dynamic.gateway.MdlDynLiveRcmd dyn_live_rcmd = 15;`
     */
    public fun clearDynLiveRcmd() {
      _builder.clearDynLiveRcmd()
    }
    /**
     * ```
     * 直播推荐卡
     * ```
     *
     * `.bilibili.dynamic.gateway.MdlDynLiveRcmd dyn_live_rcmd = 15;`
     * @return Whether the dynLiveRcmd field is set.
     */
    public fun hasDynLiveRcmd(): kotlin.Boolean {
      return _builder.hasDynLiveRcmd()
    }

    /**
     * ```
     * UGC合集
     * ```
     *
     * `.bilibili.dynamic.gateway.MdlDynUGCSeason dyn_ugc_season = 16;`
     */
    public var dynUgcSeason: bilibili.dynamic.gateway.MdlDynUGCSeason
      @JvmName("getDynUgcSeason")
      get() = _builder.getDynUgcSeason()
      @JvmName("setDynUgcSeason")
      set(value) {
        _builder.setDynUgcSeason(value)
      }
    /**
     * ```
     * UGC合集
     * ```
     *
     * `.bilibili.dynamic.gateway.MdlDynUGCSeason dyn_ugc_season = 16;`
     */
    public fun clearDynUgcSeason() {
      _builder.clearDynUgcSeason()
    }
    /**
     * ```
     * UGC合集
     * ```
     *
     * `.bilibili.dynamic.gateway.MdlDynUGCSeason dyn_ugc_season = 16;`
     * @return Whether the dynUgcSeason field is set.
     */
    public fun hasDynUgcSeason(): kotlin.Boolean {
      return _builder.hasDynUgcSeason()
    }

    /**
     * ```
     * 订阅卡
     * ```
     *
     * `.bilibili.dynamic.gateway.MdlDynSubscriptionNew dyn_subscription_new = 17;`
     */
    public var dynSubscriptionNew: bilibili.dynamic.gateway.MdlDynSubscriptionNew
      @JvmName("getDynSubscriptionNew")
      get() = _builder.getDynSubscriptionNew()
      @JvmName("setDynSubscriptionNew")
      set(value) {
        _builder.setDynSubscriptionNew(value)
      }
    /**
     * ```
     * 订阅卡
     * ```
     *
     * `.bilibili.dynamic.gateway.MdlDynSubscriptionNew dyn_subscription_new = 17;`
     */
    public fun clearDynSubscriptionNew() {
      _builder.clearDynSubscriptionNew()
    }
    /**
     * ```
     * 订阅卡
     * ```
     *
     * `.bilibili.dynamic.gateway.MdlDynSubscriptionNew dyn_subscription_new = 17;`
     * @return Whether the dynSubscriptionNew field is set.
     */
    public fun hasDynSubscriptionNew(): kotlin.Boolean {
      return _builder.hasDynSubscriptionNew()
    }
    public val moduleItemCase: bilibili.dynamic.gateway.ModuleDynamic.ModuleItemCase
      @JvmName("getModuleItemCase")
      get() = _builder.getModuleItemCase()

    public fun clearModuleItem() {
      _builder.clearModuleItem()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun bilibili.dynamic.gateway.ModuleDynamic.copy(block: `bilibili.dynamic.gateway`.ModuleDynamicKt.Dsl.() -> kotlin.Unit): bilibili.dynamic.gateway.ModuleDynamic =
  `bilibili.dynamic.gateway`.ModuleDynamicKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val bilibili.dynamic.gateway.ModuleDynamicOrBuilder.dynArchiveOrNull: bilibili.dynamic.gateway.MdlDynArchive?
  get() = if (hasDynArchive()) getDynArchive() else null

public val bilibili.dynamic.gateway.ModuleDynamicOrBuilder.dynPgcOrNull: bilibili.dynamic.gateway.MdlDynPGC?
  get() = if (hasDynPgc()) getDynPgc() else null

public val bilibili.dynamic.gateway.ModuleDynamicOrBuilder.dynCourSeasonOrNull: bilibili.dynamic.gateway.MdlDynCourSeason?
  get() = if (hasDynCourSeason()) getDynCourSeason() else null

public val bilibili.dynamic.gateway.ModuleDynamicOrBuilder.dynCourBatchOrNull: bilibili.dynamic.gateway.MdlDynCourBatch?
  get() = if (hasDynCourBatch()) getDynCourBatch() else null

public val bilibili.dynamic.gateway.ModuleDynamicOrBuilder.dynForwardOrNull: bilibili.dynamic.gateway.MdlDynForward?
  get() = if (hasDynForward()) getDynForward() else null

public val bilibili.dynamic.gateway.ModuleDynamicOrBuilder.dynDrawOrNull: bilibili.dynamic.gateway.MdlDynDraw?
  get() = if (hasDynDraw()) getDynDraw() else null

public val bilibili.dynamic.gateway.ModuleDynamicOrBuilder.dynArticleOrNull: bilibili.dynamic.gateway.MdlDynArticle?
  get() = if (hasDynArticle()) getDynArticle() else null

public val bilibili.dynamic.gateway.ModuleDynamicOrBuilder.dynMusicOrNull: bilibili.dynamic.gateway.MdlDynMusic?
  get() = if (hasDynMusic()) getDynMusic() else null

public val bilibili.dynamic.gateway.ModuleDynamicOrBuilder.dynCommonOrNull: bilibili.dynamic.gateway.MdlDynCommon?
  get() = if (hasDynCommon()) getDynCommon() else null

public val bilibili.dynamic.gateway.ModuleDynamicOrBuilder.dynCommonLiveOrNull: bilibili.dynamic.gateway.MdlDynLive?
  get() = if (hasDynCommonLive()) getDynCommonLive() else null

public val bilibili.dynamic.gateway.ModuleDynamicOrBuilder.dynMedialistOrNull: bilibili.dynamic.gateway.MdlDynMedialist?
  get() = if (hasDynMedialist()) getDynMedialist() else null

public val bilibili.dynamic.gateway.ModuleDynamicOrBuilder.dynAppletOrNull: bilibili.dynamic.gateway.MdlDynApplet?
  get() = if (hasDynApplet()) getDynApplet() else null

public val bilibili.dynamic.gateway.ModuleDynamicOrBuilder.dynSubscriptionOrNull: bilibili.dynamic.gateway.MdlDynSubscription?
  get() = if (hasDynSubscription()) getDynSubscription() else null

public val bilibili.dynamic.gateway.ModuleDynamicOrBuilder.dynLiveRcmdOrNull: bilibili.dynamic.gateway.MdlDynLiveRcmd?
  get() = if (hasDynLiveRcmd()) getDynLiveRcmd() else null

public val bilibili.dynamic.gateway.ModuleDynamicOrBuilder.dynUgcSeasonOrNull: bilibili.dynamic.gateway.MdlDynUGCSeason?
  get() = if (hasDynUgcSeason()) getDynUgcSeason() else null

public val bilibili.dynamic.gateway.ModuleDynamicOrBuilder.dynSubscriptionNewOrNull: bilibili.dynamic.gateway.MdlDynSubscriptionNew?
  get() = if (hasDynSubscriptionNew()) getDynSubscriptionNew() else null

