// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: bilibili/dynamic/gw/gateway.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package bilibili.dynamic.gateway;

@kotlin.jvm.JvmName("-initializercmdUPsParam")
public inline fun rcmdUPsParam(block: bilibili.dynamic.gateway.RcmdUPsParamKt.Dsl.() -> kotlin.Unit): bilibili.dynamic.gateway.RcmdUPsParam =
  bilibili.dynamic.gateway.RcmdUPsParamKt.Dsl._create(bilibili.dynamic.gateway.RcmdUPsParam.newBuilder()).apply { block() }._build()
/**
 * ```
 * 推荐up主入参
 * ```
 *
 * Protobuf type `bilibili.dynamic.gateway.RcmdUPsParam`
 */
public object RcmdUPsParamKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: bilibili.dynamic.gateway.RcmdUPsParam.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: bilibili.dynamic.gateway.RcmdUPsParam.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): bilibili.dynamic.gateway.RcmdUPsParam = _builder.build()

    /**
     * `int64 dislike_ts = 1;`
     */
    public var dislikeTs: kotlin.Long
      @JvmName("getDislikeTs")
      get() = _builder.getDislikeTs()
      @JvmName("setDislikeTs")
      set(value) {
        _builder.setDislikeTs(value)
      }
    /**
     * `int64 dislike_ts = 1;`
     */
    public fun clearDislikeTs() {
      _builder.clearDislikeTs()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun bilibili.dynamic.gateway.RcmdUPsParam.copy(block: `bilibili.dynamic.gateway`.RcmdUPsParamKt.Dsl.() -> kotlin.Unit): bilibili.dynamic.gateway.RcmdUPsParam =
  `bilibili.dynamic.gateway`.RcmdUPsParamKt.Dsl._create(this.toBuilder()).apply { block() }._build()

