// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: bilibili/dynamic/gw/gateway.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package bilibili.dynamic.gateway;

@kotlin.jvm.JvmName("-initializethreePointAttention")
public inline fun threePointAttention(block: bilibili.dynamic.gateway.ThreePointAttentionKt.Dsl.() -> kotlin.Unit): bilibili.dynamic.gateway.ThreePointAttention =
  bilibili.dynamic.gateway.ThreePointAttentionKt.Dsl._create(bilibili.dynamic.gateway.ThreePointAttention.newBuilder()).apply { block() }._build()
/**
 * ```
 * 三点-关注
 * ```
 *
 * Protobuf type `bilibili.dynamic.gateway.ThreePointAttention`
 */
public object ThreePointAttentionKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: bilibili.dynamic.gateway.ThreePointAttention.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: bilibili.dynamic.gateway.ThreePointAttention.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): bilibili.dynamic.gateway.ThreePointAttention = _builder.build()

    /**
     * ```
     * attention icon
     * ```
     *
     * `string attention_icon = 1;`
     */
    public var attentionIcon: kotlin.String
      @JvmName("getAttentionIcon")
      get() = _builder.getAttentionIcon()
      @JvmName("setAttentionIcon")
      set(value) {
        _builder.setAttentionIcon(value)
      }
    /**
     * ```
     * attention icon
     * ```
     *
     * `string attention_icon = 1;`
     */
    public fun clearAttentionIcon() {
      _builder.clearAttentionIcon()
    }

    /**
     * ```
     * 关注时显示的文案
     * ```
     *
     * `string attention_text = 2;`
     */
    public var attentionText: kotlin.String
      @JvmName("getAttentionText")
      get() = _builder.getAttentionText()
      @JvmName("setAttentionText")
      set(value) {
        _builder.setAttentionText(value)
      }
    /**
     * ```
     * 关注时显示的文案
     * ```
     *
     * `string attention_text = 2;`
     */
    public fun clearAttentionText() {
      _builder.clearAttentionText()
    }

    /**
     * ```
     * not attention icon
     * ```
     *
     * `string not_attention_icon = 3;`
     */
    public var notAttentionIcon: kotlin.String
      @JvmName("getNotAttentionIcon")
      get() = _builder.getNotAttentionIcon()
      @JvmName("setNotAttentionIcon")
      set(value) {
        _builder.setNotAttentionIcon(value)
      }
    /**
     * ```
     * not attention icon
     * ```
     *
     * `string not_attention_icon = 3;`
     */
    public fun clearNotAttentionIcon() {
      _builder.clearNotAttentionIcon()
    }

    /**
     * ```
     * 未关注时显示的文案
     * ```
     *
     * `string not_attention_text = 4;`
     */
    public var notAttentionText: kotlin.String
      @JvmName("getNotAttentionText")
      get() = _builder.getNotAttentionText()
      @JvmName("setNotAttentionText")
      set(value) {
        _builder.setNotAttentionText(value)
      }
    /**
     * ```
     * 未关注时显示的文案
     * ```
     *
     * `string not_attention_text = 4;`
     */
    public fun clearNotAttentionText() {
      _builder.clearNotAttentionText()
    }

    /**
     * ```
     * 当前关注状态
     * ```
     *
     * `.bilibili.dynamic.gateway.ThreePointAttentionStatus status = 5;`
     */
    public var status: bilibili.dynamic.gateway.ThreePointAttentionStatus
      @JvmName("getStatus")
      get() = _builder.getStatus()
      @JvmName("setStatus")
      set(value) {
        _builder.setStatus(value)
      }
    public var statusValue: kotlin.Int
      @JvmName("getStatusValue")
      get() = _builder.getStatusValue()
      @JvmName("setStatusValue")
      set(value) {
        _builder.setStatusValue(value)
      }
    /**
     * ```
     * 当前关注状态
     * ```
     *
     * `.bilibili.dynamic.gateway.ThreePointAttentionStatus status = 5;`
     */
    public fun clearStatus() {
      _builder.clearStatus()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun bilibili.dynamic.gateway.ThreePointAttention.copy(block: `bilibili.dynamic.gateway`.ThreePointAttentionKt.Dsl.() -> kotlin.Unit): bilibili.dynamic.gateway.ThreePointAttention =
  `bilibili.dynamic.gateway`.ThreePointAttentionKt.Dsl._create(this.toBuilder()).apply { block() }._build()

