// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: bilibili/app/dynamic/v1/dynamic.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package bilibili.app.dynamic.v1;

@kotlin.jvm.JvmName("-initializeadInfo")
public inline fun adInfo(block: bilibili.app.dynamic.v1.AdInfoKt.Dsl.() -> kotlin.Unit): bilibili.app.dynamic.v1.AdInfo =
  bilibili.app.dynamic.v1.AdInfoKt.Dsl._create(bilibili.app.dynamic.v1.AdInfo.newBuilder()).apply { block() }._build()
/**
 * ```
 * 行政区划信息
 * ```
 *
 * Protobuf type `bilibili.app.dynamic.v1.AdInfo`
 */
public object AdInfoKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: bilibili.app.dynamic.v1.AdInfo.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: bilibili.app.dynamic.v1.AdInfo.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): bilibili.app.dynamic.v1.AdInfo = _builder.build()

    /**
     * ```
     * 国家代码(ISO3166标准3位数字码)
     * ```
     *
     * `string nation_code = 1;`
     */
    public var nationCode: kotlin.String
      @JvmName("getNationCode")
      get() = _builder.getNationCode()
      @JvmName("setNationCode")
      set(value) {
        _builder.setNationCode(value)
      }
    /**
     * ```
     * 国家代码(ISO3166标准3位数字码)
     * ```
     *
     * `string nation_code = 1;`
     */
    public fun clearNationCode() {
      _builder.clearNationCode()
    }

    /**
     * ```
     * 行政区划代码，规则详见：行政区划代码说明
     * ```
     *
     * `string adcode = 2;`
     */
    public var adcode: kotlin.String
      @JvmName("getAdcode")
      get() = _builder.getAdcode()
      @JvmName("setAdcode")
      set(value) {
        _builder.setAdcode(value)
      }
    /**
     * ```
     * 行政区划代码，规则详见：行政区划代码说明
     * ```
     *
     * `string adcode = 2;`
     */
    public fun clearAdcode() {
      _builder.clearAdcode()
    }

    /**
     * ```
     * 城市代码，由国家码+行政区划代码(提出城市级别)组合而来，总共为9位
     * ```
     *
     * `string city_code = 3;`
     */
    public var cityCode: kotlin.String
      @JvmName("getCityCode")
      get() = _builder.getCityCode()
      @JvmName("setCityCode")
      set(value) {
        _builder.setCityCode(value)
      }
    /**
     * ```
     * 城市代码，由国家码+行政区划代码(提出城市级别)组合而来，总共为9位
     * ```
     *
     * `string city_code = 3;`
     */
    public fun clearCityCode() {
      _builder.clearCityCode()
    }

    /**
     * ```
     * 行政区划名称
     * ```
     *
     * `string name = 4;`
     */
    public var name: kotlin.String
      @JvmName("getName")
      get() = _builder.getName()
      @JvmName("setName")
      set(value) {
        _builder.setName(value)
      }
    /**
     * ```
     * 行政区划名称
     * ```
     *
     * `string name = 4;`
     */
    public fun clearName() {
      _builder.clearName()
    }

    /**
     * ```
     * 行政区划中心点坐标
     * ```
     *
     * `.bilibili.app.dynamic.v1.Gps gps = 5;`
     */
    public var gps: bilibili.app.dynamic.v1.Gps
      @JvmName("getGps")
      get() = _builder.getGps()
      @JvmName("setGps")
      set(value) {
        _builder.setGps(value)
      }
    /**
     * ```
     * 行政区划中心点坐标
     * ```
     *
     * `.bilibili.app.dynamic.v1.Gps gps = 5;`
     */
    public fun clearGps() {
      _builder.clearGps()
    }
    /**
     * ```
     * 行政区划中心点坐标
     * ```
     *
     * `.bilibili.app.dynamic.v1.Gps gps = 5;`
     * @return Whether the gps field is set.
     */
    public fun hasGps(): kotlin.Boolean {
      return _builder.hasGps()
    }
    public val AdInfoKt.Dsl.gpsOrNull: bilibili.app.dynamic.v1.Gps?
      get() = _builder.gpsOrNull
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun bilibili.app.dynamic.v1.AdInfo.copy(block: `bilibili.app.dynamic.v1`.AdInfoKt.Dsl.() -> kotlin.Unit): bilibili.app.dynamic.v1.AdInfo =
  `bilibili.app.dynamic.v1`.AdInfoKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val bilibili.app.dynamic.v1.AdInfoOrBuilder.gpsOrNull: bilibili.app.dynamic.v1.Gps?
  get() = if (hasGps()) getGps() else null

