// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: bilibili/app/dynamic/v1/dynamic.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package bilibili.app.dynamic.v1;

@kotlin.jvm.JvmName("-initializesVideoModuleDesc")
public inline fun sVideoModuleDesc(block: bilibili.app.dynamic.v1.SVideoModuleDescKt.Dsl.() -> kotlin.Unit): bilibili.app.dynamic.v1.SVideoModuleDesc =
  bilibili.app.dynamic.v1.SVideoModuleDescKt.Dsl._create(bilibili.app.dynamic.v1.SVideoModuleDesc.newBuilder()).apply { block() }._build()
/**
 * ```
 * 文本内容模块
 * ```
 *
 * Protobuf type `bilibili.app.dynamic.v1.SVideoModuleDesc`
 */
public object SVideoModuleDescKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: bilibili.app.dynamic.v1.SVideoModuleDesc.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: bilibili.app.dynamic.v1.SVideoModuleDesc.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): bilibili.app.dynamic.v1.SVideoModuleDesc = _builder.build()

    /**
     * ```
     * 文本内容
     * ```
     *
     * `string text = 1;`
     */
    public var text: kotlin.String
      @JvmName("getText")
      get() = _builder.getText()
      @JvmName("setText")
      set(value) {
        _builder.setText(value)
      }
    /**
     * ```
     * 文本内容
     * ```
     *
     * `string text = 1;`
     */
    public fun clearText() {
      _builder.clearText()
    }

    /**
     * ```
     * 跳转地址
     * ```
     *
     * `string uri = 2;`
     */
    public var uri: kotlin.String
      @JvmName("getUri")
      get() = _builder.getUri()
      @JvmName("setUri")
      set(value) {
        _builder.setUri(value)
      }
    /**
     * ```
     * 跳转地址
     * ```
     *
     * `string uri = 2;`
     */
    public fun clearUri() {
      _builder.clearUri()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun bilibili.app.dynamic.v1.SVideoModuleDesc.copy(block: `bilibili.app.dynamic.v1`.SVideoModuleDescKt.Dsl.() -> kotlin.Unit): bilibili.app.dynamic.v1.SVideoModuleDesc =
  `bilibili.app.dynamic.v1`.SVideoModuleDescKt.Dsl._create(this.toBuilder()).apply { block() }._build()

