// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: bilibili/api/probe/v1/probe.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package bilibili.api.probe.v1;

@kotlin.jvm.JvmName("-initializeprobeSubReply")
public inline fun probeSubReply(block: bilibili.api.probe.v1.ProbeSubReplyKt.Dsl.() -> kotlin.Unit): bilibili.api.probe.v1.ProbeSubReply =
  bilibili.api.probe.v1.ProbeSubReplyKt.Dsl._create(bilibili.api.probe.v1.ProbeSubReply.newBuilder()).apply { block() }._build()
/**
 * ```
 * ```
 *
 * Protobuf type `bilibili.api.probe.v1.ProbeSubReply`
 */
public object ProbeSubReplyKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: bilibili.api.probe.v1.ProbeSubReply.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: bilibili.api.probe.v1.ProbeSubReply.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): bilibili.api.probe.v1.ProbeSubReply = _builder.build()

    /**
     * ```
     * ```
     *
     * `int64 message_id = 1;`
     */
    public var messageId: kotlin.Long
      @JvmName("getMessageId")
      get() = _builder.getMessageId()
      @JvmName("setMessageId")
      set(value) {
        _builder.setMessageId(value)
      }
    /**
     * ```
     * ```
     *
     * `int64 message_id = 1;`
     */
    public fun clearMessageId() {
      _builder.clearMessageId()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun bilibili.api.probe.v1.ProbeSubReply.copy(block: `bilibili.api.probe.v1`.ProbeSubReplyKt.Dsl.() -> kotlin.Unit): bilibili.api.probe.v1.ProbeSubReply =
  `bilibili.api.probe.v1`.ProbeSubReplyKt.Dsl._create(this.toBuilder()).apply { block() }._build()

