// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: bilibili/account/fission/v1/fission.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package bilibili.account.fission.v1;

@kotlin.jvm.JvmName("-initializeentranceReply")
public inline fun entranceReply(block: bilibili.account.fission.v1.EntranceReplyKt.Dsl.() -> kotlin.Unit): bilibili.account.fission.v1.EntranceReply =
  bilibili.account.fission.v1.EntranceReplyKt.Dsl._create(bilibili.account.fission.v1.EntranceReply.newBuilder()).apply { block() }._build()
/**
 * ```
 * 活动入口-响应
 * ```
 *
 * Protobuf type `bilibili.account.fission.v1.EntranceReply`
 */
public object EntranceReplyKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: bilibili.account.fission.v1.EntranceReply.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: bilibili.account.fission.v1.EntranceReply.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): bilibili.account.fission.v1.EntranceReply = _builder.build()

    /**
     * ```
     * 展示图标
     * ```
     *
     * `string icon = 1;`
     */
    public var icon: kotlin.String
      @JvmName("getIcon")
      get() = _builder.getIcon()
      @JvmName("setIcon")
      set(value) {
        _builder.setIcon(value)
      }
    /**
     * ```
     * 展示图标
     * ```
     *
     * `string icon = 1;`
     */
    public fun clearIcon() {
      _builder.clearIcon()
    }

    /**
     * ```
     * 活动名称
     * ```
     *
     * `string name = 2;`
     */
    public var name: kotlin.String
      @JvmName("getName")
      get() = _builder.getName()
      @JvmName("setName")
      set(value) {
        _builder.setName(value)
      }
    /**
     * ```
     * 活动名称
     * ```
     *
     * `string name = 2;`
     */
    public fun clearName() {
      _builder.clearName()
    }

    /**
     * ```
     * 活动跳转链接
     * ```
     *
     * `string url = 3;`
     */
    public var url: kotlin.String
      @JvmName("getUrl")
      get() = _builder.getUrl()
      @JvmName("setUrl")
      set(value) {
        _builder.setUrl(value)
      }
    /**
     * ```
     * 活动跳转链接
     * ```
     *
     * `string url = 3;`
     */
    public fun clearUrl() {
      _builder.clearUrl()
    }

    /**
     * ```
     * 动画效果
     * ```
     *
     * `.bilibili.account.fission.v1.AnimateIcon animate_icon = 4;`
     */
    public var animateIcon: bilibili.account.fission.v1.AnimateIcon
      @JvmName("getAnimateIcon")
      get() = _builder.getAnimateIcon()
      @JvmName("setAnimateIcon")
      set(value) {
        _builder.setAnimateIcon(value)
      }
    /**
     * ```
     * 动画效果
     * ```
     *
     * `.bilibili.account.fission.v1.AnimateIcon animate_icon = 4;`
     */
    public fun clearAnimateIcon() {
      _builder.clearAnimateIcon()
    }
    /**
     * ```
     * 动画效果
     * ```
     *
     * `.bilibili.account.fission.v1.AnimateIcon animate_icon = 4;`
     * @return Whether the animateIcon field is set.
     */
    public fun hasAnimateIcon(): kotlin.Boolean {
      return _builder.hasAnimateIcon()
    }
    public val EntranceReplyKt.Dsl.animateIconOrNull: bilibili.account.fission.v1.AnimateIcon?
      get() = _builder.animateIconOrNull
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun bilibili.account.fission.v1.EntranceReply.copy(block: `bilibili.account.fission.v1`.EntranceReplyKt.Dsl.() -> kotlin.Unit): bilibili.account.fission.v1.EntranceReply =
  `bilibili.account.fission.v1`.EntranceReplyKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val bilibili.account.fission.v1.EntranceReplyOrBuilder.animateIconOrNull: bilibili.account.fission.v1.AnimateIcon?
  get() = if (hasAnimateIcon()) getAnimateIcon() else null

