// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bilibili/app/viewunite/common.proto

// Protobuf Java Version: 4.26.1
package bilibili.app.viewunite.common;

public interface LiveOrderOrBuilder extends
    // @@protoc_insertion_point(interface_extends:bilibili.app.viewunite.common.LiveOrder)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * </pre>
   *
   * <code>int64 sid = 1;</code>
   * @return The sid.
   */
  long getSid();

  /**
   * <pre>
   * </pre>
   *
   * <code>string text = 2;</code>
   * @return The text.
   */
  java.lang.String getText();
  /**
   * <pre>
   * </pre>
   *
   * <code>string text = 2;</code>
   * @return The bytes for text.
   */
  com.google.protobuf.ByteString
      getTextBytes();

  /**
   * <pre>
   * </pre>
   *
   * <code>int64 live_plan_start_time = 3;</code>
   * @return The livePlanStartTime.
   */
  long getLivePlanStartTime();

  /**
   * <pre>
   * </pre>
   *
   * <code>bool is_follow = 4;</code>
   * @return The isFollow.
   */
  boolean getIsFollow();

  /**
   * <pre>
   * </pre>
   *
   * <code>int64 follow_count = 5;</code>
   * @return The followCount.
   */
  long getFollowCount();
}
