// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bilibili/app/viewunite/common.proto

// Protobuf Java Version: 4.26.1
package bilibili.app.viewunite.common;

public interface OgvTitleOrBuilder extends
    // @@protoc_insertion_point(interface_extends:bilibili.app.viewunite.common.OgvTitle)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * </pre>
   *
   * <code>string title = 1;</code>
   * @return The title.
   */
  java.lang.String getTitle();
  /**
   * <pre>
   * </pre>
   *
   * <code>string title = 1;</code>
   * @return The bytes for title.
   */
  com.google.protobuf.ByteString
      getTitleBytes();

  /**
   * <pre>
   * </pre>
   *
   * <code>.bilibili.app.viewunite.common.BadgeInfo badge_info = 2;</code>
   * @return Whether the badgeInfo field is set.
   */
  boolean hasBadgeInfo();
  /**
   * <pre>
   * </pre>
   *
   * <code>.bilibili.app.viewunite.common.BadgeInfo badge_info = 2;</code>
   * @return The badgeInfo.
   */
  bilibili.app.viewunite.common.BadgeInfo getBadgeInfo();
  /**
   * <pre>
   * </pre>
   *
   * <code>.bilibili.app.viewunite.common.BadgeInfo badge_info = 2;</code>
   */
  bilibili.app.viewunite.common.BadgeInfoOrBuilder getBadgeInfoOrBuilder();

  /**
   * <pre>
   * </pre>
   *
   * <code>int32 is_show_btn_animation = 3;</code>
   * @return The isShowBtnAnimation.
   */
  int getIsShowBtnAnimation();

  /**
   * <pre>
   * </pre>
   *
   * <code>int32 follow_video_is_reserve_live = 4;</code>
   * @return The followVideoIsReserveLive.
   */
  int getFollowVideoIsReserveLive();

  /**
   * <pre>
   * </pre>
   *
   * <code>int64 reserve_id = 5;</code>
   * @return The reserveId.
   */
  long getReserveId();

  /**
   * <pre>
   * </pre>
   *
   * <code>.bilibili.app.viewunite.common.TitleDeliveryButton title_delivery_button = 6;</code>
   * @return Whether the titleDeliveryButton field is set.
   */
  boolean hasTitleDeliveryButton();
  /**
   * <pre>
   * </pre>
   *
   * <code>.bilibili.app.viewunite.common.TitleDeliveryButton title_delivery_button = 6;</code>
   * @return The titleDeliveryButton.
   */
  bilibili.app.viewunite.common.TitleDeliveryButton getTitleDeliveryButton();
  /**
   * <pre>
   * </pre>
   *
   * <code>.bilibili.app.viewunite.common.TitleDeliveryButton title_delivery_button = 6;</code>
   */
  bilibili.app.viewunite.common.TitleDeliveryButtonOrBuilder getTitleDeliveryButtonOrBuilder();
}
