// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bilibili/app/viewunite/common.proto

// Protobuf Java Version: 4.26.1
package bilibili.app.viewunite.common;

/**
 * <pre>
 * 视频详情下方推荐卡子类型: 直播
 * </pre>
 *
 * Protobuf type {@code bilibili.app.viewunite.common.RelateLiveCard}
 */
public final class RelateLiveCard extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:bilibili.app.viewunite.common.RelateLiveCard)
    RelateLiveCardOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 26,
      /* patch= */ 1,
      /* suffix= */ "",
      RelateLiveCard.class.getName());
  }
  // Use RelateLiveCard.newBuilder() to construct.
  private RelateLiveCard(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private RelateLiveCard() {
    areaName_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return bilibili.app.viewunite.common.Common.internal_static_bilibili_app_viewunite_common_RelateLiveCard_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return bilibili.app.viewunite.common.Common.internal_static_bilibili_app_viewunite_common_RelateLiveCard_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            bilibili.app.viewunite.common.RelateLiveCard.class, bilibili.app.viewunite.common.RelateLiveCard.Builder.class);
  }

  public static final int ICON_TYPE_FIELD_NUMBER = 1;
  private long iconType_ = 0L;
  /**
   * <pre>
   * </pre>
   *
   * <code>int64 icon_type = 1;</code>
   * @return The iconType.
   */
  @java.lang.Override
  public long getIconType() {
    return iconType_;
  }

  public static final int AREA_NAME_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object areaName_ = "";
  /**
   * <pre>
   * </pre>
   *
   * <code>string area_name = 2;</code>
   * @return The areaName.
   */
  @java.lang.Override
  public java.lang.String getAreaName() {
    java.lang.Object ref = areaName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      areaName_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * </pre>
   *
   * <code>string area_name = 2;</code>
   * @return The bytes for areaName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getAreaNameBytes() {
    java.lang.Object ref = areaName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      areaName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int WATCHED_SHOW_FIELD_NUMBER = 3;
  private long watchedShow_ = 0L;
  /**
   * <pre>
   * </pre>
   *
   * <code>int64 watched_show = 3;</code>
   * @return The watchedShow.
   */
  @java.lang.Override
  public long getWatchedShow() {
    return watchedShow_;
  }

  public static final int LIVE_STATUS_FIELD_NUMBER = 4;
  private long liveStatus_ = 0L;
  /**
   * <pre>
   * </pre>
   *
   * <code>int64 live_status = 4;</code>
   * @return The liveStatus.
   */
  @java.lang.Override
  public long getLiveStatus() {
    return liveStatus_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (iconType_ != 0L) {
      output.writeInt64(1, iconType_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(areaName_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, areaName_);
    }
    if (watchedShow_ != 0L) {
      output.writeInt64(3, watchedShow_);
    }
    if (liveStatus_ != 0L) {
      output.writeInt64(4, liveStatus_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (iconType_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, iconType_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(areaName_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(2, areaName_);
    }
    if (watchedShow_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(3, watchedShow_);
    }
    if (liveStatus_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(4, liveStatus_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof bilibili.app.viewunite.common.RelateLiveCard)) {
      return super.equals(obj);
    }
    bilibili.app.viewunite.common.RelateLiveCard other = (bilibili.app.viewunite.common.RelateLiveCard) obj;

    if (getIconType()
        != other.getIconType()) return false;
    if (!getAreaName()
        .equals(other.getAreaName())) return false;
    if (getWatchedShow()
        != other.getWatchedShow()) return false;
    if (getLiveStatus()
        != other.getLiveStatus()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ICON_TYPE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getIconType());
    hash = (37 * hash) + AREA_NAME_FIELD_NUMBER;
    hash = (53 * hash) + getAreaName().hashCode();
    hash = (37 * hash) + WATCHED_SHOW_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getWatchedShow());
    hash = (37 * hash) + LIVE_STATUS_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getLiveStatus());
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static bilibili.app.viewunite.common.RelateLiveCard parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static bilibili.app.viewunite.common.RelateLiveCard parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static bilibili.app.viewunite.common.RelateLiveCard parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static bilibili.app.viewunite.common.RelateLiveCard parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static bilibili.app.viewunite.common.RelateLiveCard parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static bilibili.app.viewunite.common.RelateLiveCard parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static bilibili.app.viewunite.common.RelateLiveCard parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static bilibili.app.viewunite.common.RelateLiveCard parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static bilibili.app.viewunite.common.RelateLiveCard parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static bilibili.app.viewunite.common.RelateLiveCard parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static bilibili.app.viewunite.common.RelateLiveCard parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static bilibili.app.viewunite.common.RelateLiveCard parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(bilibili.app.viewunite.common.RelateLiveCard prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * 视频详情下方推荐卡子类型: 直播
   * </pre>
   *
   * Protobuf type {@code bilibili.app.viewunite.common.RelateLiveCard}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:bilibili.app.viewunite.common.RelateLiveCard)
      bilibili.app.viewunite.common.RelateLiveCardOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return bilibili.app.viewunite.common.Common.internal_static_bilibili_app_viewunite_common_RelateLiveCard_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return bilibili.app.viewunite.common.Common.internal_static_bilibili_app_viewunite_common_RelateLiveCard_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              bilibili.app.viewunite.common.RelateLiveCard.class, bilibili.app.viewunite.common.RelateLiveCard.Builder.class);
    }

    // Construct using bilibili.app.viewunite.common.RelateLiveCard.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      iconType_ = 0L;
      areaName_ = "";
      watchedShow_ = 0L;
      liveStatus_ = 0L;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return bilibili.app.viewunite.common.Common.internal_static_bilibili_app_viewunite_common_RelateLiveCard_descriptor;
    }

    @java.lang.Override
    public bilibili.app.viewunite.common.RelateLiveCard getDefaultInstanceForType() {
      return bilibili.app.viewunite.common.RelateLiveCard.getDefaultInstance();
    }

    @java.lang.Override
    public bilibili.app.viewunite.common.RelateLiveCard build() {
      bilibili.app.viewunite.common.RelateLiveCard result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public bilibili.app.viewunite.common.RelateLiveCard buildPartial() {
      bilibili.app.viewunite.common.RelateLiveCard result = new bilibili.app.viewunite.common.RelateLiveCard(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(bilibili.app.viewunite.common.RelateLiveCard result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.iconType_ = iconType_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.areaName_ = areaName_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.watchedShow_ = watchedShow_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.liveStatus_ = liveStatus_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof bilibili.app.viewunite.common.RelateLiveCard) {
        return mergeFrom((bilibili.app.viewunite.common.RelateLiveCard)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(bilibili.app.viewunite.common.RelateLiveCard other) {
      if (other == bilibili.app.viewunite.common.RelateLiveCard.getDefaultInstance()) return this;
      if (other.getIconType() != 0L) {
        setIconType(other.getIconType());
      }
      if (!other.getAreaName().isEmpty()) {
        areaName_ = other.areaName_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (other.getWatchedShow() != 0L) {
        setWatchedShow(other.getWatchedShow());
      }
      if (other.getLiveStatus() != 0L) {
        setLiveStatus(other.getLiveStatus());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              iconType_ = input.readInt64();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 18: {
              areaName_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 24: {
              watchedShow_ = input.readInt64();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            case 32: {
              liveStatus_ = input.readInt64();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private long iconType_ ;
    /**
     * <pre>
     * </pre>
     *
     * <code>int64 icon_type = 1;</code>
     * @return The iconType.
     */
    @java.lang.Override
    public long getIconType() {
      return iconType_;
    }
    /**
     * <pre>
     * </pre>
     *
     * <code>int64 icon_type = 1;</code>
     * @param value The iconType to set.
     * @return This builder for chaining.
     */
    public Builder setIconType(long value) {

      iconType_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * </pre>
     *
     * <code>int64 icon_type = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearIconType() {
      bitField0_ = (bitField0_ & ~0x00000001);
      iconType_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object areaName_ = "";
    /**
     * <pre>
     * </pre>
     *
     * <code>string area_name = 2;</code>
     * @return The areaName.
     */
    public java.lang.String getAreaName() {
      java.lang.Object ref = areaName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        areaName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * </pre>
     *
     * <code>string area_name = 2;</code>
     * @return The bytes for areaName.
     */
    public com.google.protobuf.ByteString
        getAreaNameBytes() {
      java.lang.Object ref = areaName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        areaName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * </pre>
     *
     * <code>string area_name = 2;</code>
     * @param value The areaName to set.
     * @return This builder for chaining.
     */
    public Builder setAreaName(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      areaName_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * </pre>
     *
     * <code>string area_name = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearAreaName() {
      areaName_ = getDefaultInstance().getAreaName();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * </pre>
     *
     * <code>string area_name = 2;</code>
     * @param value The bytes for areaName to set.
     * @return This builder for chaining.
     */
    public Builder setAreaNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      areaName_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private long watchedShow_ ;
    /**
     * <pre>
     * </pre>
     *
     * <code>int64 watched_show = 3;</code>
     * @return The watchedShow.
     */
    @java.lang.Override
    public long getWatchedShow() {
      return watchedShow_;
    }
    /**
     * <pre>
     * </pre>
     *
     * <code>int64 watched_show = 3;</code>
     * @param value The watchedShow to set.
     * @return This builder for chaining.
     */
    public Builder setWatchedShow(long value) {

      watchedShow_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * </pre>
     *
     * <code>int64 watched_show = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearWatchedShow() {
      bitField0_ = (bitField0_ & ~0x00000004);
      watchedShow_ = 0L;
      onChanged();
      return this;
    }

    private long liveStatus_ ;
    /**
     * <pre>
     * </pre>
     *
     * <code>int64 live_status = 4;</code>
     * @return The liveStatus.
     */
    @java.lang.Override
    public long getLiveStatus() {
      return liveStatus_;
    }
    /**
     * <pre>
     * </pre>
     *
     * <code>int64 live_status = 4;</code>
     * @param value The liveStatus to set.
     * @return This builder for chaining.
     */
    public Builder setLiveStatus(long value) {

      liveStatus_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * </pre>
     *
     * <code>int64 live_status = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearLiveStatus() {
      bitField0_ = (bitField0_ & ~0x00000008);
      liveStatus_ = 0L;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:bilibili.app.viewunite.common.RelateLiveCard)
  }

  // @@protoc_insertion_point(class_scope:bilibili.app.viewunite.common.RelateLiveCard)
  private static final bilibili.app.viewunite.common.RelateLiveCard DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new bilibili.app.viewunite.common.RelateLiveCard();
  }

  public static bilibili.app.viewunite.common.RelateLiveCard getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<RelateLiveCard>
      PARSER = new com.google.protobuf.AbstractParser<RelateLiveCard>() {
    @java.lang.Override
    public RelateLiveCard parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<RelateLiveCard> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<RelateLiveCard> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public bilibili.app.viewunite.common.RelateLiveCard getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

