// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bilibili/app/viewunite/common.proto

// Protobuf Java Version: 4.26.1
package bilibili.app.viewunite.common;

/**
 * <pre>
 * </pre>
 *
 * Protobuf type {@code bilibili.app.viewunite.common.Rights}
 */
public final class Rights extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:bilibili.app.viewunite.common.Rights)
    RightsOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 26,
      /* patch= */ 1,
      /* suffix= */ "",
      Rights.class.getName());
  }
  // Use Rights.newBuilder() to construct.
  private Rights(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private Rights() {
    resource_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return bilibili.app.viewunite.common.Common.internal_static_bilibili_app_viewunite_common_Rights_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return bilibili.app.viewunite.common.Common.internal_static_bilibili_app_viewunite_common_Rights_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            bilibili.app.viewunite.common.Rights.class, bilibili.app.viewunite.common.Rights.Builder.class);
  }

  public static final int ALLOW_DOWNLOAD_FIELD_NUMBER = 1;
  private int allowDownload_ = 0;
  /**
   * <pre>
   * </pre>
   *
   * <code>int32 allow_download = 1;</code>
   * @return The allowDownload.
   */
  @java.lang.Override
  public int getAllowDownload() {
    return allowDownload_;
  }

  public static final int ALLOW_REVIEW_FIELD_NUMBER = 2;
  private int allowReview_ = 0;
  /**
   * <pre>
   * </pre>
   *
   * <code>int32 allow_review = 2;</code>
   * @return The allowReview.
   */
  @java.lang.Override
  public int getAllowReview() {
    return allowReview_;
  }

  public static final int CAN_WATCH_FIELD_NUMBER = 3;
  private int canWatch_ = 0;
  /**
   * <pre>
   * </pre>
   *
   * <code>int32 can_watch = 3;</code>
   * @return The canWatch.
   */
  @java.lang.Override
  public int getCanWatch() {
    return canWatch_;
  }

  public static final int RESOURCE_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private volatile java.lang.Object resource_ = "";
  /**
   * <pre>
   * </pre>
   *
   * <code>string resource = 4;</code>
   * @return The resource.
   */
  @java.lang.Override
  public java.lang.String getResource() {
    java.lang.Object ref = resource_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      resource_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * </pre>
   *
   * <code>string resource = 4;</code>
   * @return The bytes for resource.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getResourceBytes() {
    java.lang.Object ref = resource_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      resource_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ALLOW_DM_FIELD_NUMBER = 5;
  private int allowDm_ = 0;
  /**
   * <pre>
   * </pre>
   *
   * <code>int32 allow_dm = 5;</code>
   * @return The allowDm.
   */
  @java.lang.Override
  public int getAllowDm() {
    return allowDm_;
  }

  public static final int ALLOW_DEMAND_FIELD_NUMBER = 6;
  private int allowDemand_ = 0;
  /**
   * <pre>
   * </pre>
   *
   * <code>int32 allow_demand = 6;</code>
   * @return The allowDemand.
   */
  @java.lang.Override
  public int getAllowDemand() {
    return allowDemand_;
  }

  public static final int AREA_LIMIT_FIELD_NUMBER = 7;
  private int areaLimit_ = 0;
  /**
   * <pre>
   * 区域限制
   * </pre>
   *
   * <code>int32 area_limit = 7;</code>
   * @return The areaLimit.
   */
  @java.lang.Override
  public int getAreaLimit() {
    return areaLimit_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (allowDownload_ != 0) {
      output.writeInt32(1, allowDownload_);
    }
    if (allowReview_ != 0) {
      output.writeInt32(2, allowReview_);
    }
    if (canWatch_ != 0) {
      output.writeInt32(3, canWatch_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(resource_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 4, resource_);
    }
    if (allowDm_ != 0) {
      output.writeInt32(5, allowDm_);
    }
    if (allowDemand_ != 0) {
      output.writeInt32(6, allowDemand_);
    }
    if (areaLimit_ != 0) {
      output.writeInt32(7, areaLimit_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (allowDownload_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, allowDownload_);
    }
    if (allowReview_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, allowReview_);
    }
    if (canWatch_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, canWatch_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(resource_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(4, resource_);
    }
    if (allowDm_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(5, allowDm_);
    }
    if (allowDemand_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(6, allowDemand_);
    }
    if (areaLimit_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(7, areaLimit_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof bilibili.app.viewunite.common.Rights)) {
      return super.equals(obj);
    }
    bilibili.app.viewunite.common.Rights other = (bilibili.app.viewunite.common.Rights) obj;

    if (getAllowDownload()
        != other.getAllowDownload()) return false;
    if (getAllowReview()
        != other.getAllowReview()) return false;
    if (getCanWatch()
        != other.getCanWatch()) return false;
    if (!getResource()
        .equals(other.getResource())) return false;
    if (getAllowDm()
        != other.getAllowDm()) return false;
    if (getAllowDemand()
        != other.getAllowDemand()) return false;
    if (getAreaLimit()
        != other.getAreaLimit()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ALLOW_DOWNLOAD_FIELD_NUMBER;
    hash = (53 * hash) + getAllowDownload();
    hash = (37 * hash) + ALLOW_REVIEW_FIELD_NUMBER;
    hash = (53 * hash) + getAllowReview();
    hash = (37 * hash) + CAN_WATCH_FIELD_NUMBER;
    hash = (53 * hash) + getCanWatch();
    hash = (37 * hash) + RESOURCE_FIELD_NUMBER;
    hash = (53 * hash) + getResource().hashCode();
    hash = (37 * hash) + ALLOW_DM_FIELD_NUMBER;
    hash = (53 * hash) + getAllowDm();
    hash = (37 * hash) + ALLOW_DEMAND_FIELD_NUMBER;
    hash = (53 * hash) + getAllowDemand();
    hash = (37 * hash) + AREA_LIMIT_FIELD_NUMBER;
    hash = (53 * hash) + getAreaLimit();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static bilibili.app.viewunite.common.Rights parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static bilibili.app.viewunite.common.Rights parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static bilibili.app.viewunite.common.Rights parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static bilibili.app.viewunite.common.Rights parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static bilibili.app.viewunite.common.Rights parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static bilibili.app.viewunite.common.Rights parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static bilibili.app.viewunite.common.Rights parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static bilibili.app.viewunite.common.Rights parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static bilibili.app.viewunite.common.Rights parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static bilibili.app.viewunite.common.Rights parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static bilibili.app.viewunite.common.Rights parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static bilibili.app.viewunite.common.Rights parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(bilibili.app.viewunite.common.Rights prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * </pre>
   *
   * Protobuf type {@code bilibili.app.viewunite.common.Rights}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:bilibili.app.viewunite.common.Rights)
      bilibili.app.viewunite.common.RightsOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return bilibili.app.viewunite.common.Common.internal_static_bilibili_app_viewunite_common_Rights_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return bilibili.app.viewunite.common.Common.internal_static_bilibili_app_viewunite_common_Rights_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              bilibili.app.viewunite.common.Rights.class, bilibili.app.viewunite.common.Rights.Builder.class);
    }

    // Construct using bilibili.app.viewunite.common.Rights.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      allowDownload_ = 0;
      allowReview_ = 0;
      canWatch_ = 0;
      resource_ = "";
      allowDm_ = 0;
      allowDemand_ = 0;
      areaLimit_ = 0;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return bilibili.app.viewunite.common.Common.internal_static_bilibili_app_viewunite_common_Rights_descriptor;
    }

    @java.lang.Override
    public bilibili.app.viewunite.common.Rights getDefaultInstanceForType() {
      return bilibili.app.viewunite.common.Rights.getDefaultInstance();
    }

    @java.lang.Override
    public bilibili.app.viewunite.common.Rights build() {
      bilibili.app.viewunite.common.Rights result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public bilibili.app.viewunite.common.Rights buildPartial() {
      bilibili.app.viewunite.common.Rights result = new bilibili.app.viewunite.common.Rights(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(bilibili.app.viewunite.common.Rights result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.allowDownload_ = allowDownload_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.allowReview_ = allowReview_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.canWatch_ = canWatch_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.resource_ = resource_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.allowDm_ = allowDm_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.allowDemand_ = allowDemand_;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.areaLimit_ = areaLimit_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof bilibili.app.viewunite.common.Rights) {
        return mergeFrom((bilibili.app.viewunite.common.Rights)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(bilibili.app.viewunite.common.Rights other) {
      if (other == bilibili.app.viewunite.common.Rights.getDefaultInstance()) return this;
      if (other.getAllowDownload() != 0) {
        setAllowDownload(other.getAllowDownload());
      }
      if (other.getAllowReview() != 0) {
        setAllowReview(other.getAllowReview());
      }
      if (other.getCanWatch() != 0) {
        setCanWatch(other.getCanWatch());
      }
      if (!other.getResource().isEmpty()) {
        resource_ = other.resource_;
        bitField0_ |= 0x00000008;
        onChanged();
      }
      if (other.getAllowDm() != 0) {
        setAllowDm(other.getAllowDm());
      }
      if (other.getAllowDemand() != 0) {
        setAllowDemand(other.getAllowDemand());
      }
      if (other.getAreaLimit() != 0) {
        setAreaLimit(other.getAreaLimit());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              allowDownload_ = input.readInt32();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 16: {
              allowReview_ = input.readInt32();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 24: {
              canWatch_ = input.readInt32();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            case 34: {
              resource_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            case 40: {
              allowDm_ = input.readInt32();
              bitField0_ |= 0x00000010;
              break;
            } // case 40
            case 48: {
              allowDemand_ = input.readInt32();
              bitField0_ |= 0x00000020;
              break;
            } // case 48
            case 56: {
              areaLimit_ = input.readInt32();
              bitField0_ |= 0x00000040;
              break;
            } // case 56
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private int allowDownload_ ;
    /**
     * <pre>
     * </pre>
     *
     * <code>int32 allow_download = 1;</code>
     * @return The allowDownload.
     */
    @java.lang.Override
    public int getAllowDownload() {
      return allowDownload_;
    }
    /**
     * <pre>
     * </pre>
     *
     * <code>int32 allow_download = 1;</code>
     * @param value The allowDownload to set.
     * @return This builder for chaining.
     */
    public Builder setAllowDownload(int value) {

      allowDownload_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * </pre>
     *
     * <code>int32 allow_download = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearAllowDownload() {
      bitField0_ = (bitField0_ & ~0x00000001);
      allowDownload_ = 0;
      onChanged();
      return this;
    }

    private int allowReview_ ;
    /**
     * <pre>
     * </pre>
     *
     * <code>int32 allow_review = 2;</code>
     * @return The allowReview.
     */
    @java.lang.Override
    public int getAllowReview() {
      return allowReview_;
    }
    /**
     * <pre>
     * </pre>
     *
     * <code>int32 allow_review = 2;</code>
     * @param value The allowReview to set.
     * @return This builder for chaining.
     */
    public Builder setAllowReview(int value) {

      allowReview_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * </pre>
     *
     * <code>int32 allow_review = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearAllowReview() {
      bitField0_ = (bitField0_ & ~0x00000002);
      allowReview_ = 0;
      onChanged();
      return this;
    }

    private int canWatch_ ;
    /**
     * <pre>
     * </pre>
     *
     * <code>int32 can_watch = 3;</code>
     * @return The canWatch.
     */
    @java.lang.Override
    public int getCanWatch() {
      return canWatch_;
    }
    /**
     * <pre>
     * </pre>
     *
     * <code>int32 can_watch = 3;</code>
     * @param value The canWatch to set.
     * @return This builder for chaining.
     */
    public Builder setCanWatch(int value) {

      canWatch_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * </pre>
     *
     * <code>int32 can_watch = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearCanWatch() {
      bitField0_ = (bitField0_ & ~0x00000004);
      canWatch_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object resource_ = "";
    /**
     * <pre>
     * </pre>
     *
     * <code>string resource = 4;</code>
     * @return The resource.
     */
    public java.lang.String getResource() {
      java.lang.Object ref = resource_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        resource_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * </pre>
     *
     * <code>string resource = 4;</code>
     * @return The bytes for resource.
     */
    public com.google.protobuf.ByteString
        getResourceBytes() {
      java.lang.Object ref = resource_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        resource_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * </pre>
     *
     * <code>string resource = 4;</code>
     * @param value The resource to set.
     * @return This builder for chaining.
     */
    public Builder setResource(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      resource_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * </pre>
     *
     * <code>string resource = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearResource() {
      resource_ = getDefaultInstance().getResource();
      bitField0_ = (bitField0_ & ~0x00000008);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * </pre>
     *
     * <code>string resource = 4;</code>
     * @param value The bytes for resource to set.
     * @return This builder for chaining.
     */
    public Builder setResourceBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      resource_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }

    private int allowDm_ ;
    /**
     * <pre>
     * </pre>
     *
     * <code>int32 allow_dm = 5;</code>
     * @return The allowDm.
     */
    @java.lang.Override
    public int getAllowDm() {
      return allowDm_;
    }
    /**
     * <pre>
     * </pre>
     *
     * <code>int32 allow_dm = 5;</code>
     * @param value The allowDm to set.
     * @return This builder for chaining.
     */
    public Builder setAllowDm(int value) {

      allowDm_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * </pre>
     *
     * <code>int32 allow_dm = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearAllowDm() {
      bitField0_ = (bitField0_ & ~0x00000010);
      allowDm_ = 0;
      onChanged();
      return this;
    }

    private int allowDemand_ ;
    /**
     * <pre>
     * </pre>
     *
     * <code>int32 allow_demand = 6;</code>
     * @return The allowDemand.
     */
    @java.lang.Override
    public int getAllowDemand() {
      return allowDemand_;
    }
    /**
     * <pre>
     * </pre>
     *
     * <code>int32 allow_demand = 6;</code>
     * @param value The allowDemand to set.
     * @return This builder for chaining.
     */
    public Builder setAllowDemand(int value) {

      allowDemand_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * </pre>
     *
     * <code>int32 allow_demand = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearAllowDemand() {
      bitField0_ = (bitField0_ & ~0x00000020);
      allowDemand_ = 0;
      onChanged();
      return this;
    }

    private int areaLimit_ ;
    /**
     * <pre>
     * 区域限制
     * </pre>
     *
     * <code>int32 area_limit = 7;</code>
     * @return The areaLimit.
     */
    @java.lang.Override
    public int getAreaLimit() {
      return areaLimit_;
    }
    /**
     * <pre>
     * 区域限制
     * </pre>
     *
     * <code>int32 area_limit = 7;</code>
     * @param value The areaLimit to set.
     * @return This builder for chaining.
     */
    public Builder setAreaLimit(int value) {

      areaLimit_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 区域限制
     * </pre>
     *
     * <code>int32 area_limit = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearAreaLimit() {
      bitField0_ = (bitField0_ & ~0x00000040);
      areaLimit_ = 0;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:bilibili.app.viewunite.common.Rights)
  }

  // @@protoc_insertion_point(class_scope:bilibili.app.viewunite.common.Rights)
  private static final bilibili.app.viewunite.common.Rights DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new bilibili.app.viewunite.common.Rights();
  }

  public static bilibili.app.viewunite.common.Rights getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Rights>
      PARSER = new com.google.protobuf.AbstractParser<Rights>() {
    @java.lang.Override
    public Rights parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Rights> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Rights> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public bilibili.app.viewunite.common.Rights getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

