// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bilibili/app/viewunite/common.proto

// Protobuf Java Version: 4.26.1
package bilibili.app.viewunite.common;

/**
 * <pre>
 * </pre>
 *
 * Protobuf type {@code bilibili.app.viewunite.common.UserStatus}
 */
public final class UserStatus extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:bilibili.app.viewunite.common.UserStatus)
    UserStatusOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 26,
      /* patch= */ 1,
      /* suffix= */ "",
      UserStatus.class.getName());
  }
  // Use UserStatus.newBuilder() to construct.
  private UserStatus(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private UserStatus() {
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return bilibili.app.viewunite.common.Common.internal_static_bilibili_app_viewunite_common_UserStatus_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return bilibili.app.viewunite.common.Common.internal_static_bilibili_app_viewunite_common_UserStatus_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            bilibili.app.viewunite.common.UserStatus.class, bilibili.app.viewunite.common.UserStatus.Builder.class);
  }

  public static final int SHOW_FIELD_NUMBER = 1;
  private int show_ = 0;
  /**
   * <pre>
   * </pre>
   *
   * <code>int32 show = 1;</code>
   * @return The show.
   */
  @java.lang.Override
  public int getShow() {
    return show_;
  }

  public static final int FOLLOW_FIELD_NUMBER = 2;
  private int follow_ = 0;
  /**
   * <pre>
   * </pre>
   *
   * <code>int32 follow = 2;</code>
   * @return The follow.
   */
  @java.lang.Override
  public int getFollow() {
    return follow_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (show_ != 0) {
      output.writeInt32(1, show_);
    }
    if (follow_ != 0) {
      output.writeInt32(2, follow_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (show_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, show_);
    }
    if (follow_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, follow_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof bilibili.app.viewunite.common.UserStatus)) {
      return super.equals(obj);
    }
    bilibili.app.viewunite.common.UserStatus other = (bilibili.app.viewunite.common.UserStatus) obj;

    if (getShow()
        != other.getShow()) return false;
    if (getFollow()
        != other.getFollow()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + SHOW_FIELD_NUMBER;
    hash = (53 * hash) + getShow();
    hash = (37 * hash) + FOLLOW_FIELD_NUMBER;
    hash = (53 * hash) + getFollow();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static bilibili.app.viewunite.common.UserStatus parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static bilibili.app.viewunite.common.UserStatus parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static bilibili.app.viewunite.common.UserStatus parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static bilibili.app.viewunite.common.UserStatus parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static bilibili.app.viewunite.common.UserStatus parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static bilibili.app.viewunite.common.UserStatus parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static bilibili.app.viewunite.common.UserStatus parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static bilibili.app.viewunite.common.UserStatus parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static bilibili.app.viewunite.common.UserStatus parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static bilibili.app.viewunite.common.UserStatus parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static bilibili.app.viewunite.common.UserStatus parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static bilibili.app.viewunite.common.UserStatus parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(bilibili.app.viewunite.common.UserStatus prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * </pre>
   *
   * Protobuf type {@code bilibili.app.viewunite.common.UserStatus}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:bilibili.app.viewunite.common.UserStatus)
      bilibili.app.viewunite.common.UserStatusOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return bilibili.app.viewunite.common.Common.internal_static_bilibili_app_viewunite_common_UserStatus_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return bilibili.app.viewunite.common.Common.internal_static_bilibili_app_viewunite_common_UserStatus_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              bilibili.app.viewunite.common.UserStatus.class, bilibili.app.viewunite.common.UserStatus.Builder.class);
    }

    // Construct using bilibili.app.viewunite.common.UserStatus.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      show_ = 0;
      follow_ = 0;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return bilibili.app.viewunite.common.Common.internal_static_bilibili_app_viewunite_common_UserStatus_descriptor;
    }

    @java.lang.Override
    public bilibili.app.viewunite.common.UserStatus getDefaultInstanceForType() {
      return bilibili.app.viewunite.common.UserStatus.getDefaultInstance();
    }

    @java.lang.Override
    public bilibili.app.viewunite.common.UserStatus build() {
      bilibili.app.viewunite.common.UserStatus result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public bilibili.app.viewunite.common.UserStatus buildPartial() {
      bilibili.app.viewunite.common.UserStatus result = new bilibili.app.viewunite.common.UserStatus(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(bilibili.app.viewunite.common.UserStatus result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.show_ = show_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.follow_ = follow_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof bilibili.app.viewunite.common.UserStatus) {
        return mergeFrom((bilibili.app.viewunite.common.UserStatus)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(bilibili.app.viewunite.common.UserStatus other) {
      if (other == bilibili.app.viewunite.common.UserStatus.getDefaultInstance()) return this;
      if (other.getShow() != 0) {
        setShow(other.getShow());
      }
      if (other.getFollow() != 0) {
        setFollow(other.getFollow());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              show_ = input.readInt32();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 16: {
              follow_ = input.readInt32();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private int show_ ;
    /**
     * <pre>
     * </pre>
     *
     * <code>int32 show = 1;</code>
     * @return The show.
     */
    @java.lang.Override
    public int getShow() {
      return show_;
    }
    /**
     * <pre>
     * </pre>
     *
     * <code>int32 show = 1;</code>
     * @param value The show to set.
     * @return This builder for chaining.
     */
    public Builder setShow(int value) {

      show_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * </pre>
     *
     * <code>int32 show = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearShow() {
      bitField0_ = (bitField0_ & ~0x00000001);
      show_ = 0;
      onChanged();
      return this;
    }

    private int follow_ ;
    /**
     * <pre>
     * </pre>
     *
     * <code>int32 follow = 2;</code>
     * @return The follow.
     */
    @java.lang.Override
    public int getFollow() {
      return follow_;
    }
    /**
     * <pre>
     * </pre>
     *
     * <code>int32 follow = 2;</code>
     * @param value The follow to set.
     * @return This builder for chaining.
     */
    public Builder setFollow(int value) {

      follow_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * </pre>
     *
     * <code>int32 follow = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearFollow() {
      bitField0_ = (bitField0_ & ~0x00000002);
      follow_ = 0;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:bilibili.app.viewunite.common.UserStatus)
  }

  // @@protoc_insertion_point(class_scope:bilibili.app.viewunite.common.UserStatus)
  private static final bilibili.app.viewunite.common.UserStatus DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new bilibili.app.viewunite.common.UserStatus();
  }

  public static bilibili.app.viewunite.common.UserStatus getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<UserStatus>
      PARSER = new com.google.protobuf.AbstractParser<UserStatus>() {
    @java.lang.Override
    public UserStatus parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<UserStatus> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<UserStatus> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public bilibili.app.viewunite.common.UserStatus getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

