// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: bilibili/app/viewunite/common.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package bilibili.app.viewunite.common;

@kotlin.jvm.JvmName("-initializecombinationEp")
public inline fun combinationEp(block: bilibili.app.viewunite.common.CombinationEpKt.Dsl.() -> kotlin.Unit): bilibili.app.viewunite.common.CombinationEp =
  bilibili.app.viewunite.common.CombinationEpKt.Dsl._create(bilibili.app.viewunite.common.CombinationEp.newBuilder()).apply { block() }._build()
/**
 * ```
 * ```
 *
 * Protobuf type `bilibili.app.viewunite.common.CombinationEp`
 */
public object CombinationEpKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: bilibili.app.viewunite.common.CombinationEp.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: bilibili.app.viewunite.common.CombinationEp.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): bilibili.app.viewunite.common.CombinationEp = _builder.build()

    /**
     * ```
     * ```
     *
     * `int32 id = 1;`
     */
    public var id: kotlin.Int
      @JvmName("getId")
      get() = _builder.getId()
      @JvmName("setId")
      set(value) {
        _builder.setId(value)
      }
    /**
     * ```
     * ```
     *
     * `int32 id = 1;`
     */
    public fun clearId() {
      _builder.clearId()
    }

    /**
     * ```
     * ```
     *
     * `int32 section_id = 2;`
     */
    public var sectionId: kotlin.Int
      @JvmName("getSectionId")
      get() = _builder.getSectionId()
      @JvmName("setSectionId")
      set(value) {
        _builder.setSectionId(value)
      }
    /**
     * ```
     * ```
     *
     * `int32 section_id = 2;`
     */
    public fun clearSectionId() {
      _builder.clearSectionId()
    }

    /**
     * ```
     * ```
     *
     * `string title = 3;`
     */
    public var title: kotlin.String
      @JvmName("getTitle")
      get() = _builder.getTitle()
      @JvmName("setTitle")
      set(value) {
        _builder.setTitle(value)
      }
    /**
     * ```
     * ```
     *
     * `string title = 3;`
     */
    public fun clearTitle() {
      _builder.clearTitle()
    }

    /**
     * ```
     * ```
     *
     * `int32 can_ord_desc = 4;`
     */
    public var canOrdDesc: kotlin.Int
      @JvmName("getCanOrdDesc")
      get() = _builder.getCanOrdDesc()
      @JvmName("setCanOrdDesc")
      set(value) {
        _builder.setCanOrdDesc(value)
      }
    /**
     * ```
     * ```
     *
     * `int32 can_ord_desc = 4;`
     */
    public fun clearCanOrdDesc() {
      _builder.clearCanOrdDesc()
    }

    /**
     * ```
     * ```
     *
     * `string more = 5;`
     */
    public var more: kotlin.String
      @JvmName("getMore")
      get() = _builder.getMore()
      @JvmName("setMore")
      set(value) {
        _builder.setMore(value)
      }
    /**
     * ```
     * ```
     *
     * `string more = 5;`
     */
    public fun clearMore() {
      _builder.clearMore()
    }

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class EpisodeIdsProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * ```
     * ```
     *
     * `repeated int32 episode_ids = 6;`
     */
     public val episodeIds: com.google.protobuf.kotlin.DslList<kotlin.Int, EpisodeIdsProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.getEpisodeIdsList()
      )
    /**
     * ```
     * ```
     *
     * `repeated int32 episode_ids = 6;`
     * @param value The episodeIds to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addEpisodeIds")
    public fun com.google.protobuf.kotlin.DslList<kotlin.Int, EpisodeIdsProxy>.add(value: kotlin.Int) {
      _builder.addEpisodeIds(value)
    }/**
     * ```
     * ```
     *
     * `repeated int32 episode_ids = 6;`
     * @param value The episodeIds to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignEpisodeIds")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<kotlin.Int, EpisodeIdsProxy>.plusAssign(value: kotlin.Int) {
      add(value)
    }/**
     * ```
     * ```
     *
     * `repeated int32 episode_ids = 6;`
     * @param values The episodeIds to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllEpisodeIds")
    public fun com.google.protobuf.kotlin.DslList<kotlin.Int, EpisodeIdsProxy>.addAll(values: kotlin.collections.Iterable<kotlin.Int>) {
      _builder.addAllEpisodeIds(values)
    }/**
     * ```
     * ```
     *
     * `repeated int32 episode_ids = 6;`
     * @param values The episodeIds to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllEpisodeIds")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<kotlin.Int, EpisodeIdsProxy>.plusAssign(values: kotlin.collections.Iterable<kotlin.Int>) {
      addAll(values)
    }/**
     * ```
     * ```
     *
     * `repeated int32 episode_ids = 6;`
     * @param index The index to set the value at.
     * @param value The episodeIds to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setEpisodeIds")
    public operator fun com.google.protobuf.kotlin.DslList<kotlin.Int, EpisodeIdsProxy>.set(index: kotlin.Int, value: kotlin.Int) {
      _builder.setEpisodeIds(index, value)
    }/**
     * ```
     * ```
     *
     * `repeated int32 episode_ids = 6;`
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearEpisodeIds")
    public fun com.google.protobuf.kotlin.DslList<kotlin.Int, EpisodeIdsProxy>.clear() {
      _builder.clearEpisodeIds()
    }
    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class EpisodesProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * ```
     * ```
     *
     * `repeated .bilibili.app.viewunite.common.ViewEpisode episodes = 7;`
     */
     public val episodes: com.google.protobuf.kotlin.DslList<bilibili.app.viewunite.common.ViewEpisode, EpisodesProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.getEpisodesList()
      )
    /**
     * ```
     * ```
     *
     * `repeated .bilibili.app.viewunite.common.ViewEpisode episodes = 7;`
     * @param value The episodes to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addEpisodes")
    public fun com.google.protobuf.kotlin.DslList<bilibili.app.viewunite.common.ViewEpisode, EpisodesProxy>.add(value: bilibili.app.viewunite.common.ViewEpisode) {
      _builder.addEpisodes(value)
    }
    /**
     * ```
     * ```
     *
     * `repeated .bilibili.app.viewunite.common.ViewEpisode episodes = 7;`
     * @param value The episodes to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignEpisodes")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<bilibili.app.viewunite.common.ViewEpisode, EpisodesProxy>.plusAssign(value: bilibili.app.viewunite.common.ViewEpisode) {
      add(value)
    }
    /**
     * ```
     * ```
     *
     * `repeated .bilibili.app.viewunite.common.ViewEpisode episodes = 7;`
     * @param values The episodes to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllEpisodes")
    public fun com.google.protobuf.kotlin.DslList<bilibili.app.viewunite.common.ViewEpisode, EpisodesProxy>.addAll(values: kotlin.collections.Iterable<bilibili.app.viewunite.common.ViewEpisode>) {
      _builder.addAllEpisodes(values)
    }
    /**
     * ```
     * ```
     *
     * `repeated .bilibili.app.viewunite.common.ViewEpisode episodes = 7;`
     * @param values The episodes to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllEpisodes")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<bilibili.app.viewunite.common.ViewEpisode, EpisodesProxy>.plusAssign(values: kotlin.collections.Iterable<bilibili.app.viewunite.common.ViewEpisode>) {
      addAll(values)
    }
    /**
     * ```
     * ```
     *
     * `repeated .bilibili.app.viewunite.common.ViewEpisode episodes = 7;`
     * @param index The index to set the value at.
     * @param value The episodes to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setEpisodes")
    public operator fun com.google.protobuf.kotlin.DslList<bilibili.app.viewunite.common.ViewEpisode, EpisodesProxy>.set(index: kotlin.Int, value: bilibili.app.viewunite.common.ViewEpisode) {
      _builder.setEpisodes(index, value)
    }
    /**
     * ```
     * ```
     *
     * `repeated .bilibili.app.viewunite.common.ViewEpisode episodes = 7;`
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearEpisodes")
    public fun com.google.protobuf.kotlin.DslList<bilibili.app.viewunite.common.ViewEpisode, EpisodesProxy>.clear() {
      _builder.clearEpisodes()
    }


    /**
     * ```
     * ```
     *
     * `string split_text = 8;`
     */
    public var splitText: kotlin.String
      @JvmName("getSplitText")
      get() = _builder.getSplitText()
      @JvmName("setSplitText")
      set(value) {
        _builder.setSplitText(value)
      }
    /**
     * ```
     * ```
     *
     * `string split_text = 8;`
     */
    public fun clearSplitText() {
      _builder.clearSplitText()
    }

    /**
     * ```
     * ```
     *
     * `.bilibili.app.viewunite.common.Style module_style = 9;`
     */
    public var moduleStyle: bilibili.app.viewunite.common.Style
      @JvmName("getModuleStyle")
      get() = _builder.getModuleStyle()
      @JvmName("setModuleStyle")
      set(value) {
        _builder.setModuleStyle(value)
      }
    /**
     * ```
     * ```
     *
     * `.bilibili.app.viewunite.common.Style module_style = 9;`
     */
    public fun clearModuleStyle() {
      _builder.clearModuleStyle()
    }
    /**
     * ```
     * ```
     *
     * `.bilibili.app.viewunite.common.Style module_style = 9;`
     * @return Whether the moduleStyle field is set.
     */
    public fun hasModuleStyle(): kotlin.Boolean {
      return _builder.hasModuleStyle()
    }
    public val CombinationEpKt.Dsl.moduleStyleOrNull: bilibili.app.viewunite.common.Style?
      get() = _builder.moduleStyleOrNull

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class SerialSeasonProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * ```
     * ```
     *
     * `repeated .bilibili.app.viewunite.common.SerialSeason serial_season = 10;`
     */
     public val serialSeason: com.google.protobuf.kotlin.DslList<bilibili.app.viewunite.common.SerialSeason, SerialSeasonProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.getSerialSeasonList()
      )
    /**
     * ```
     * ```
     *
     * `repeated .bilibili.app.viewunite.common.SerialSeason serial_season = 10;`
     * @param value The serialSeason to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addSerialSeason")
    public fun com.google.protobuf.kotlin.DslList<bilibili.app.viewunite.common.SerialSeason, SerialSeasonProxy>.add(value: bilibili.app.viewunite.common.SerialSeason) {
      _builder.addSerialSeason(value)
    }
    /**
     * ```
     * ```
     *
     * `repeated .bilibili.app.viewunite.common.SerialSeason serial_season = 10;`
     * @param value The serialSeason to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignSerialSeason")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<bilibili.app.viewunite.common.SerialSeason, SerialSeasonProxy>.plusAssign(value: bilibili.app.viewunite.common.SerialSeason) {
      add(value)
    }
    /**
     * ```
     * ```
     *
     * `repeated .bilibili.app.viewunite.common.SerialSeason serial_season = 10;`
     * @param values The serialSeason to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllSerialSeason")
    public fun com.google.protobuf.kotlin.DslList<bilibili.app.viewunite.common.SerialSeason, SerialSeasonProxy>.addAll(values: kotlin.collections.Iterable<bilibili.app.viewunite.common.SerialSeason>) {
      _builder.addAllSerialSeason(values)
    }
    /**
     * ```
     * ```
     *
     * `repeated .bilibili.app.viewunite.common.SerialSeason serial_season = 10;`
     * @param values The serialSeason to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllSerialSeason")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<bilibili.app.viewunite.common.SerialSeason, SerialSeasonProxy>.plusAssign(values: kotlin.collections.Iterable<bilibili.app.viewunite.common.SerialSeason>) {
      addAll(values)
    }
    /**
     * ```
     * ```
     *
     * `repeated .bilibili.app.viewunite.common.SerialSeason serial_season = 10;`
     * @param index The index to set the value at.
     * @param value The serialSeason to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setSerialSeason")
    public operator fun com.google.protobuf.kotlin.DslList<bilibili.app.viewunite.common.SerialSeason, SerialSeasonProxy>.set(index: kotlin.Int, value: bilibili.app.viewunite.common.SerialSeason) {
      _builder.setSerialSeason(index, value)
    }
    /**
     * ```
     * ```
     *
     * `repeated .bilibili.app.viewunite.common.SerialSeason serial_season = 10;`
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearSerialSeason")
    public fun com.google.protobuf.kotlin.DslList<bilibili.app.viewunite.common.SerialSeason, SerialSeasonProxy>.clear() {
      _builder.clearSerialSeason()
    }


    /**
     * ```
     * ```
     *
     * `.bilibili.app.viewunite.common.SectionData section_data = 11;`
     */
    public var sectionData: bilibili.app.viewunite.common.SectionData
      @JvmName("getSectionData")
      get() = _builder.getSectionData()
      @JvmName("setSectionData")
      set(value) {
        _builder.setSectionData(value)
      }
    /**
     * ```
     * ```
     *
     * `.bilibili.app.viewunite.common.SectionData section_data = 11;`
     */
    public fun clearSectionData() {
      _builder.clearSectionData()
    }
    /**
     * ```
     * ```
     *
     * `.bilibili.app.viewunite.common.SectionData section_data = 11;`
     * @return Whether the sectionData field is set.
     */
    public fun hasSectionData(): kotlin.Boolean {
      return _builder.hasSectionData()
    }
    public val CombinationEpKt.Dsl.sectionDataOrNull: bilibili.app.viewunite.common.SectionData?
      get() = _builder.sectionDataOrNull
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun bilibili.app.viewunite.common.CombinationEp.copy(block: `bilibili.app.viewunite.common`.CombinationEpKt.Dsl.() -> kotlin.Unit): bilibili.app.viewunite.common.CombinationEp =
  `bilibili.app.viewunite.common`.CombinationEpKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val bilibili.app.viewunite.common.CombinationEpOrBuilder.moduleStyleOrNull: bilibili.app.viewunite.common.Style?
  get() = if (hasModuleStyle()) getModuleStyle() else null

public val bilibili.app.viewunite.common.CombinationEpOrBuilder.sectionDataOrNull: bilibili.app.viewunite.common.SectionData?
  get() = if (hasSectionData()) getSectionData() else null

