// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: bilibili/app/viewunite/common.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package bilibili.app.viewunite.common;

@kotlin.jvm.JvmName("-initializeugcEpisode")
public inline fun ugcEpisode(block: bilibili.app.viewunite.common.UgcEpisodeKt.Dsl.() -> kotlin.Unit): bilibili.app.viewunite.common.UgcEpisode =
  bilibili.app.viewunite.common.UgcEpisodeKt.Dsl._create(bilibili.app.viewunite.common.UgcEpisode.newBuilder()).apply { block() }._build()
/**
 * ```
 * ```
 *
 * Protobuf type `bilibili.app.viewunite.common.UgcEpisode`
 */
public object UgcEpisodeKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: bilibili.app.viewunite.common.UgcEpisode.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: bilibili.app.viewunite.common.UgcEpisode.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): bilibili.app.viewunite.common.UgcEpisode = _builder.build()

    /**
     * ```
     * ```
     *
     * `int64 id = 1;`
     */
    public var id: kotlin.Long
      @JvmName("getId")
      get() = _builder.getId()
      @JvmName("setId")
      set(value) {
        _builder.setId(value)
      }
    /**
     * ```
     * ```
     *
     * `int64 id = 1;`
     */
    public fun clearId() {
      _builder.clearId()
    }

    /**
     * ```
     * ```
     *
     * `int64 aid = 2;`
     */
    public var aid: kotlin.Long
      @JvmName("getAid")
      get() = _builder.getAid()
      @JvmName("setAid")
      set(value) {
        _builder.setAid(value)
      }
    /**
     * ```
     * ```
     *
     * `int64 aid = 2;`
     */
    public fun clearAid() {
      _builder.clearAid()
    }

    /**
     * ```
     * ```
     *
     * `int64 cid = 3;`
     */
    public var cid: kotlin.Long
      @JvmName("getCid")
      get() = _builder.getCid()
      @JvmName("setCid")
      set(value) {
        _builder.setCid(value)
      }
    /**
     * ```
     * ```
     *
     * `int64 cid = 3;`
     */
    public fun clearCid() {
      _builder.clearCid()
    }

    /**
     * ```
     * ```
     *
     * `string title = 4;`
     */
    public var title: kotlin.String
      @JvmName("getTitle")
      get() = _builder.getTitle()
      @JvmName("setTitle")
      set(value) {
        _builder.setTitle(value)
      }
    /**
     * ```
     * ```
     *
     * `string title = 4;`
     */
    public fun clearTitle() {
      _builder.clearTitle()
    }

    /**
     * ```
     * ```
     *
     * `string cover = 5;`
     */
    public var cover: kotlin.String
      @JvmName("getCover")
      get() = _builder.getCover()
      @JvmName("setCover")
      set(value) {
        _builder.setCover(value)
      }
    /**
     * ```
     * ```
     *
     * `string cover = 5;`
     */
    public fun clearCover() {
      _builder.clearCover()
    }

    /**
     * ```
     * ```
     *
     * `string cover_right_text = 6;`
     */
    public var coverRightText: kotlin.String
      @JvmName("getCoverRightText")
      get() = _builder.getCoverRightText()
      @JvmName("setCoverRightText")
      set(value) {
        _builder.setCoverRightText(value)
      }
    /**
     * ```
     * ```
     *
     * `string cover_right_text = 6;`
     */
    public fun clearCoverRightText() {
      _builder.clearCoverRightText()
    }

    /**
     * ```
     * ```
     *
     * `.bilibili.app.viewunite.common.Page page = 7;`
     */
    public var page: bilibili.app.viewunite.common.Page
      @JvmName("getPage")
      get() = _builder.getPage()
      @JvmName("setPage")
      set(value) {
        _builder.setPage(value)
      }
    /**
     * ```
     * ```
     *
     * `.bilibili.app.viewunite.common.Page page = 7;`
     */
    public fun clearPage() {
      _builder.clearPage()
    }
    /**
     * ```
     * ```
     *
     * `.bilibili.app.viewunite.common.Page page = 7;`
     * @return Whether the page field is set.
     */
    public fun hasPage(): kotlin.Boolean {
      return _builder.hasPage()
    }
    public val UgcEpisodeKt.Dsl.pageOrNull: bilibili.app.viewunite.common.Page?
      get() = _builder.pageOrNull

    /**
     * ```
     * ```
     *
     * `.bilibili.app.viewunite.common.StatInfo vt = 8;`
     */
    public var vt: bilibili.app.viewunite.common.StatInfo
      @JvmName("getVt")
      get() = _builder.getVt()
      @JvmName("setVt")
      set(value) {
        _builder.setVt(value)
      }
    /**
     * ```
     * ```
     *
     * `.bilibili.app.viewunite.common.StatInfo vt = 8;`
     */
    public fun clearVt() {
      _builder.clearVt()
    }
    /**
     * ```
     * ```
     *
     * `.bilibili.app.viewunite.common.StatInfo vt = 8;`
     * @return Whether the vt field is set.
     */
    public fun hasVt(): kotlin.Boolean {
      return _builder.hasVt()
    }
    public val UgcEpisodeKt.Dsl.vtOrNull: bilibili.app.viewunite.common.StatInfo?
      get() = _builder.vtOrNull

    /**
     * ```
     * ```
     *
     * `.bilibili.app.viewunite.common.StatInfo danmaku = 9;`
     */
    public var danmaku: bilibili.app.viewunite.common.StatInfo
      @JvmName("getDanmaku")
      get() = _builder.getDanmaku()
      @JvmName("setDanmaku")
      set(value) {
        _builder.setDanmaku(value)
      }
    /**
     * ```
     * ```
     *
     * `.bilibili.app.viewunite.common.StatInfo danmaku = 9;`
     */
    public fun clearDanmaku() {
      _builder.clearDanmaku()
    }
    /**
     * ```
     * ```
     *
     * `.bilibili.app.viewunite.common.StatInfo danmaku = 9;`
     * @return Whether the danmaku field is set.
     */
    public fun hasDanmaku(): kotlin.Boolean {
      return _builder.hasDanmaku()
    }
    public val UgcEpisodeKt.Dsl.danmakuOrNull: bilibili.app.viewunite.common.StatInfo?
      get() = _builder.danmakuOrNull
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun bilibili.app.viewunite.common.UgcEpisode.copy(block: `bilibili.app.viewunite.common`.UgcEpisodeKt.Dsl.() -> kotlin.Unit): bilibili.app.viewunite.common.UgcEpisode =
  `bilibili.app.viewunite.common`.UgcEpisodeKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val bilibili.app.viewunite.common.UgcEpisodeOrBuilder.pageOrNull: bilibili.app.viewunite.common.Page?
  get() = if (hasPage()) getPage() else null

public val bilibili.app.viewunite.common.UgcEpisodeOrBuilder.vtOrNull: bilibili.app.viewunite.common.StatInfo?
  get() = if (hasVt()) getVt() else null

public val bilibili.app.viewunite.common.UgcEpisodeOrBuilder.danmakuOrNull: bilibili.app.viewunite.common.StatInfo?
  get() = if (hasDanmaku()) getDanmaku() else null

