// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: bilibili/app/viewunite/common.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package bilibili.app.viewunite.common;

@kotlin.jvm.JvmName("-initializeugcSection")
public inline fun ugcSection(block: bilibili.app.viewunite.common.UgcSectionKt.Dsl.() -> kotlin.Unit): bilibili.app.viewunite.common.UgcSection =
  bilibili.app.viewunite.common.UgcSectionKt.Dsl._create(bilibili.app.viewunite.common.UgcSection.newBuilder()).apply { block() }._build()
/**
 * ```
 * ```
 *
 * Protobuf type `bilibili.app.viewunite.common.UgcSection`
 */
public object UgcSectionKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: bilibili.app.viewunite.common.UgcSection.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: bilibili.app.viewunite.common.UgcSection.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): bilibili.app.viewunite.common.UgcSection = _builder.build()

    /**
     * ```
     * ```
     *
     * `int64 id = 1;`
     */
    public var id: kotlin.Long
      @JvmName("getId")
      get() = _builder.getId()
      @JvmName("setId")
      set(value) {
        _builder.setId(value)
      }
    /**
     * ```
     * ```
     *
     * `int64 id = 1;`
     */
    public fun clearId() {
      _builder.clearId()
    }

    /**
     * ```
     * ```
     *
     * `string title = 2;`
     */
    public var title: kotlin.String
      @JvmName("getTitle")
      get() = _builder.getTitle()
      @JvmName("setTitle")
      set(value) {
        _builder.setTitle(value)
      }
    /**
     * ```
     * ```
     *
     * `string title = 2;`
     */
    public fun clearTitle() {
      _builder.clearTitle()
    }

    /**
     * ```
     * ```
     *
     * `int64 type = 3;`
     */
    public var type: kotlin.Long
      @JvmName("getType")
      get() = _builder.getType()
      @JvmName("setType")
      set(value) {
        _builder.setType(value)
      }
    /**
     * ```
     * ```
     *
     * `int64 type = 3;`
     */
    public fun clearType() {
      _builder.clearType()
    }

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class EpisodesProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * ```
     * ```
     *
     * `repeated .bilibili.app.viewunite.common.UgcEpisode episodes = 4;`
     */
     public val episodes: com.google.protobuf.kotlin.DslList<bilibili.app.viewunite.common.UgcEpisode, EpisodesProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.getEpisodesList()
      )
    /**
     * ```
     * ```
     *
     * `repeated .bilibili.app.viewunite.common.UgcEpisode episodes = 4;`
     * @param value The episodes to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addEpisodes")
    public fun com.google.protobuf.kotlin.DslList<bilibili.app.viewunite.common.UgcEpisode, EpisodesProxy>.add(value: bilibili.app.viewunite.common.UgcEpisode) {
      _builder.addEpisodes(value)
    }
    /**
     * ```
     * ```
     *
     * `repeated .bilibili.app.viewunite.common.UgcEpisode episodes = 4;`
     * @param value The episodes to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignEpisodes")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<bilibili.app.viewunite.common.UgcEpisode, EpisodesProxy>.plusAssign(value: bilibili.app.viewunite.common.UgcEpisode) {
      add(value)
    }
    /**
     * ```
     * ```
     *
     * `repeated .bilibili.app.viewunite.common.UgcEpisode episodes = 4;`
     * @param values The episodes to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllEpisodes")
    public fun com.google.protobuf.kotlin.DslList<bilibili.app.viewunite.common.UgcEpisode, EpisodesProxy>.addAll(values: kotlin.collections.Iterable<bilibili.app.viewunite.common.UgcEpisode>) {
      _builder.addAllEpisodes(values)
    }
    /**
     * ```
     * ```
     *
     * `repeated .bilibili.app.viewunite.common.UgcEpisode episodes = 4;`
     * @param values The episodes to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllEpisodes")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<bilibili.app.viewunite.common.UgcEpisode, EpisodesProxy>.plusAssign(values: kotlin.collections.Iterable<bilibili.app.viewunite.common.UgcEpisode>) {
      addAll(values)
    }
    /**
     * ```
     * ```
     *
     * `repeated .bilibili.app.viewunite.common.UgcEpisode episodes = 4;`
     * @param index The index to set the value at.
     * @param value The episodes to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setEpisodes")
    public operator fun com.google.protobuf.kotlin.DslList<bilibili.app.viewunite.common.UgcEpisode, EpisodesProxy>.set(index: kotlin.Int, value: bilibili.app.viewunite.common.UgcEpisode) {
      _builder.setEpisodes(index, value)
    }
    /**
     * ```
     * ```
     *
     * `repeated .bilibili.app.viewunite.common.UgcEpisode episodes = 4;`
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearEpisodes")
    public fun com.google.protobuf.kotlin.DslList<bilibili.app.viewunite.common.UgcEpisode, EpisodesProxy>.clear() {
      _builder.clearEpisodes()
    }

  }
}
@kotlin.jvm.JvmSynthetic
public inline fun bilibili.app.viewunite.common.UgcSection.copy(block: `bilibili.app.viewunite.common`.UgcSectionKt.Dsl.() -> kotlin.Unit): bilibili.app.viewunite.common.UgcSection =
  `bilibili.app.viewunite.common`.UgcSectionKt.Dsl._create(this.toBuilder()).apply { block() }._build()

