// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: bilibili/app/playeronline/v1/playeronline.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package bilibili.app.playeronline.v1;

@kotlin.jvm.JvmName("-initializepremiereInfoReply")
public inline fun premiereInfoReply(block: bilibili.app.playeronline.v1.PremiereInfoReplyKt.Dsl.() -> kotlin.Unit): bilibili.app.playeronline.v1.PremiereInfoReply =
  bilibili.app.playeronline.v1.PremiereInfoReplyKt.Dsl._create(bilibili.app.playeronline.v1.PremiereInfoReply.newBuilder()).apply { block() }._build()
/**
 * ```
 * ```
 *
 * Protobuf type `bilibili.app.playeronline.v1.PremiereInfoReply`
 */
public object PremiereInfoReplyKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: bilibili.app.playeronline.v1.PremiereInfoReply.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: bilibili.app.playeronline.v1.PremiereInfoReply.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): bilibili.app.playeronline.v1.PremiereInfoReply = _builder.build()

    /**
     * ```
     * ```
     *
     * `string premiere_over_text = 1;`
     */
    public var premiereOverText: kotlin.String
      @JvmName("getPremiereOverText")
      get() = _builder.getPremiereOverText()
      @JvmName("setPremiereOverText")
      set(value) {
        _builder.setPremiereOverText(value)
      }
    /**
     * ```
     * ```
     *
     * `string premiere_over_text = 1;`
     */
    public fun clearPremiereOverText() {
      _builder.clearPremiereOverText()
    }

    /**
     * ```
     * ```
     *
     * `int64 participant = 2;`
     */
    public var participant: kotlin.Long
      @JvmName("getParticipant")
      get() = _builder.getParticipant()
      @JvmName("setParticipant")
      set(value) {
        _builder.setParticipant(value)
      }
    /**
     * ```
     * ```
     *
     * `int64 participant = 2;`
     */
    public fun clearParticipant() {
      _builder.clearParticipant()
    }

    /**
     * ```
     * ```
     *
     * `int64 interaction = 3;`
     */
    public var interaction: kotlin.Long
      @JvmName("getInteraction")
      get() = _builder.getInteraction()
      @JvmName("setInteraction")
      set(value) {
        _builder.setInteraction(value)
      }
    /**
     * ```
     * ```
     *
     * `int64 interaction = 3;`
     */
    public fun clearInteraction() {
      _builder.clearInteraction()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun bilibili.app.playeronline.v1.PremiereInfoReply.copy(block: `bilibili.app.playeronline.v1`.PremiereInfoReplyKt.Dsl.() -> kotlin.Unit): bilibili.app.playeronline.v1.PremiereInfoReply =
  `bilibili.app.playeronline.v1`.PremiereInfoReplyKt.Dsl._create(this.toBuilder()).apply { block() }._build()

