// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bilibili/web/space/v1/space.proto

// Protobuf Java Version: 4.26.1
package bilibili.web.space.v1;

public interface UpRcmdBlackListReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:bilibili.web.space.v1.UpRcmdBlackListReply)
    com.google.protobuf.MessageOrBuilder {
}
