// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bilibili/app/view/v1/view.proto

// Protobuf Java Version: 4.26.1
package bilibili.app.view.v1;

/**
 * <pre>
 * </pre>
 *
 * Protobuf type {@code bilibili.app.view.v1.RecThreePoint}
 */
public final class RecThreePoint extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:bilibili.app.view.v1.RecThreePoint)
    RecThreePointOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 26,
      /* patch= */ 1,
      /* suffix= */ "",
      RecThreePoint.class.getName());
  }
  // Use RecThreePoint.newBuilder() to construct.
  private RecThreePoint(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private RecThreePoint() {
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return bilibili.app.view.v1.ViewOuterClass.internal_static_bilibili_app_view_v1_RecThreePoint_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return bilibili.app.view.v1.ViewOuterClass.internal_static_bilibili_app_view_v1_RecThreePoint_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            bilibili.app.view.v1.RecThreePoint.class, bilibili.app.view.v1.RecThreePoint.Builder.class);
  }

  private int bitField0_;
  public static final int DISLIKE_FIELD_NUMBER = 1;
  private bilibili.app.view.v1.RecDislike dislike_;
  /**
   * <pre>
   * </pre>
   *
   * <code>.bilibili.app.view.v1.RecDislike dislike = 1;</code>
   * @return Whether the dislike field is set.
   */
  @java.lang.Override
  public boolean hasDislike() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <pre>
   * </pre>
   *
   * <code>.bilibili.app.view.v1.RecDislike dislike = 1;</code>
   * @return The dislike.
   */
  @java.lang.Override
  public bilibili.app.view.v1.RecDislike getDislike() {
    return dislike_ == null ? bilibili.app.view.v1.RecDislike.getDefaultInstance() : dislike_;
  }
  /**
   * <pre>
   * </pre>
   *
   * <code>.bilibili.app.view.v1.RecDislike dislike = 1;</code>
   */
  @java.lang.Override
  public bilibili.app.view.v1.RecDislikeOrBuilder getDislikeOrBuilder() {
    return dislike_ == null ? bilibili.app.view.v1.RecDislike.getDefaultInstance() : dislike_;
  }

  public static final int FEEDBACK_FIELD_NUMBER = 2;
  private bilibili.app.view.v1.RecDislike feedback_;
  /**
   * <pre>
   * </pre>
   *
   * <code>.bilibili.app.view.v1.RecDislike feedback = 2;</code>
   * @return Whether the feedback field is set.
   */
  @java.lang.Override
  public boolean hasFeedback() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <pre>
   * </pre>
   *
   * <code>.bilibili.app.view.v1.RecDislike feedback = 2;</code>
   * @return The feedback.
   */
  @java.lang.Override
  public bilibili.app.view.v1.RecDislike getFeedback() {
    return feedback_ == null ? bilibili.app.view.v1.RecDislike.getDefaultInstance() : feedback_;
  }
  /**
   * <pre>
   * </pre>
   *
   * <code>.bilibili.app.view.v1.RecDislike feedback = 2;</code>
   */
  @java.lang.Override
  public bilibili.app.view.v1.RecDislikeOrBuilder getFeedbackOrBuilder() {
    return feedback_ == null ? bilibili.app.view.v1.RecDislike.getDefaultInstance() : feedback_;
  }

  public static final int WATCH_LATER_FIELD_NUMBER = 3;
  private boolean watchLater_ = false;
  /**
   * <pre>
   * </pre>
   *
   * <code>bool watch_later = 3;</code>
   * @return The watchLater.
   */
  @java.lang.Override
  public boolean getWatchLater() {
    return watchLater_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(1, getDislike());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeMessage(2, getFeedback());
    }
    if (watchLater_ != false) {
      output.writeBool(3, watchLater_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getDislike());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getFeedback());
    }
    if (watchLater_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(3, watchLater_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof bilibili.app.view.v1.RecThreePoint)) {
      return super.equals(obj);
    }
    bilibili.app.view.v1.RecThreePoint other = (bilibili.app.view.v1.RecThreePoint) obj;

    if (hasDislike() != other.hasDislike()) return false;
    if (hasDislike()) {
      if (!getDislike()
          .equals(other.getDislike())) return false;
    }
    if (hasFeedback() != other.hasFeedback()) return false;
    if (hasFeedback()) {
      if (!getFeedback()
          .equals(other.getFeedback())) return false;
    }
    if (getWatchLater()
        != other.getWatchLater()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasDislike()) {
      hash = (37 * hash) + DISLIKE_FIELD_NUMBER;
      hash = (53 * hash) + getDislike().hashCode();
    }
    if (hasFeedback()) {
      hash = (37 * hash) + FEEDBACK_FIELD_NUMBER;
      hash = (53 * hash) + getFeedback().hashCode();
    }
    hash = (37 * hash) + WATCH_LATER_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getWatchLater());
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static bilibili.app.view.v1.RecThreePoint parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static bilibili.app.view.v1.RecThreePoint parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static bilibili.app.view.v1.RecThreePoint parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static bilibili.app.view.v1.RecThreePoint parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static bilibili.app.view.v1.RecThreePoint parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static bilibili.app.view.v1.RecThreePoint parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static bilibili.app.view.v1.RecThreePoint parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static bilibili.app.view.v1.RecThreePoint parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static bilibili.app.view.v1.RecThreePoint parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static bilibili.app.view.v1.RecThreePoint parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static bilibili.app.view.v1.RecThreePoint parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static bilibili.app.view.v1.RecThreePoint parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(bilibili.app.view.v1.RecThreePoint prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * </pre>
   *
   * Protobuf type {@code bilibili.app.view.v1.RecThreePoint}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:bilibili.app.view.v1.RecThreePoint)
      bilibili.app.view.v1.RecThreePointOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return bilibili.app.view.v1.ViewOuterClass.internal_static_bilibili_app_view_v1_RecThreePoint_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return bilibili.app.view.v1.ViewOuterClass.internal_static_bilibili_app_view_v1_RecThreePoint_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              bilibili.app.view.v1.RecThreePoint.class, bilibili.app.view.v1.RecThreePoint.Builder.class);
    }

    // Construct using bilibili.app.view.v1.RecThreePoint.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage
              .alwaysUseFieldBuilders) {
        getDislikeFieldBuilder();
        getFeedbackFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      dislike_ = null;
      if (dislikeBuilder_ != null) {
        dislikeBuilder_.dispose();
        dislikeBuilder_ = null;
      }
      feedback_ = null;
      if (feedbackBuilder_ != null) {
        feedbackBuilder_.dispose();
        feedbackBuilder_ = null;
      }
      watchLater_ = false;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return bilibili.app.view.v1.ViewOuterClass.internal_static_bilibili_app_view_v1_RecThreePoint_descriptor;
    }

    @java.lang.Override
    public bilibili.app.view.v1.RecThreePoint getDefaultInstanceForType() {
      return bilibili.app.view.v1.RecThreePoint.getDefaultInstance();
    }

    @java.lang.Override
    public bilibili.app.view.v1.RecThreePoint build() {
      bilibili.app.view.v1.RecThreePoint result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public bilibili.app.view.v1.RecThreePoint buildPartial() {
      bilibili.app.view.v1.RecThreePoint result = new bilibili.app.view.v1.RecThreePoint(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(bilibili.app.view.v1.RecThreePoint result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.dislike_ = dislikeBuilder_ == null
            ? dislike_
            : dislikeBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.feedback_ = feedbackBuilder_ == null
            ? feedback_
            : feedbackBuilder_.build();
        to_bitField0_ |= 0x00000002;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.watchLater_ = watchLater_;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof bilibili.app.view.v1.RecThreePoint) {
        return mergeFrom((bilibili.app.view.v1.RecThreePoint)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(bilibili.app.view.v1.RecThreePoint other) {
      if (other == bilibili.app.view.v1.RecThreePoint.getDefaultInstance()) return this;
      if (other.hasDislike()) {
        mergeDislike(other.getDislike());
      }
      if (other.hasFeedback()) {
        mergeFeedback(other.getFeedback());
      }
      if (other.getWatchLater() != false) {
        setWatchLater(other.getWatchLater());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  getDislikeFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              input.readMessage(
                  getFeedbackFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 24: {
              watchLater_ = input.readBool();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private bilibili.app.view.v1.RecDislike dislike_;
    private com.google.protobuf.SingleFieldBuilder<
        bilibili.app.view.v1.RecDislike, bilibili.app.view.v1.RecDislike.Builder, bilibili.app.view.v1.RecDislikeOrBuilder> dislikeBuilder_;
    /**
     * <pre>
     * </pre>
     *
     * <code>.bilibili.app.view.v1.RecDislike dislike = 1;</code>
     * @return Whether the dislike field is set.
     */
    public boolean hasDislike() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     * </pre>
     *
     * <code>.bilibili.app.view.v1.RecDislike dislike = 1;</code>
     * @return The dislike.
     */
    public bilibili.app.view.v1.RecDislike getDislike() {
      if (dislikeBuilder_ == null) {
        return dislike_ == null ? bilibili.app.view.v1.RecDislike.getDefaultInstance() : dislike_;
      } else {
        return dislikeBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * </pre>
     *
     * <code>.bilibili.app.view.v1.RecDislike dislike = 1;</code>
     */
    public Builder setDislike(bilibili.app.view.v1.RecDislike value) {
      if (dislikeBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        dislike_ = value;
      } else {
        dislikeBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * </pre>
     *
     * <code>.bilibili.app.view.v1.RecDislike dislike = 1;</code>
     */
    public Builder setDislike(
        bilibili.app.view.v1.RecDislike.Builder builderForValue) {
      if (dislikeBuilder_ == null) {
        dislike_ = builderForValue.build();
      } else {
        dislikeBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * </pre>
     *
     * <code>.bilibili.app.view.v1.RecDislike dislike = 1;</code>
     */
    public Builder mergeDislike(bilibili.app.view.v1.RecDislike value) {
      if (dislikeBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
          dislike_ != null &&
          dislike_ != bilibili.app.view.v1.RecDislike.getDefaultInstance()) {
          getDislikeBuilder().mergeFrom(value);
        } else {
          dislike_ = value;
        }
      } else {
        dislikeBuilder_.mergeFrom(value);
      }
      if (dislike_ != null) {
        bitField0_ |= 0x00000001;
        onChanged();
      }
      return this;
    }
    /**
     * <pre>
     * </pre>
     *
     * <code>.bilibili.app.view.v1.RecDislike dislike = 1;</code>
     */
    public Builder clearDislike() {
      bitField0_ = (bitField0_ & ~0x00000001);
      dislike_ = null;
      if (dislikeBuilder_ != null) {
        dislikeBuilder_.dispose();
        dislikeBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <pre>
     * </pre>
     *
     * <code>.bilibili.app.view.v1.RecDislike dislike = 1;</code>
     */
    public bilibili.app.view.v1.RecDislike.Builder getDislikeBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return getDislikeFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * </pre>
     *
     * <code>.bilibili.app.view.v1.RecDislike dislike = 1;</code>
     */
    public bilibili.app.view.v1.RecDislikeOrBuilder getDislikeOrBuilder() {
      if (dislikeBuilder_ != null) {
        return dislikeBuilder_.getMessageOrBuilder();
      } else {
        return dislike_ == null ?
            bilibili.app.view.v1.RecDislike.getDefaultInstance() : dislike_;
      }
    }
    /**
     * <pre>
     * </pre>
     *
     * <code>.bilibili.app.view.v1.RecDislike dislike = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        bilibili.app.view.v1.RecDislike, bilibili.app.view.v1.RecDislike.Builder, bilibili.app.view.v1.RecDislikeOrBuilder> 
        getDislikeFieldBuilder() {
      if (dislikeBuilder_ == null) {
        dislikeBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            bilibili.app.view.v1.RecDislike, bilibili.app.view.v1.RecDislike.Builder, bilibili.app.view.v1.RecDislikeOrBuilder>(
                getDislike(),
                getParentForChildren(),
                isClean());
        dislike_ = null;
      }
      return dislikeBuilder_;
    }

    private bilibili.app.view.v1.RecDislike feedback_;
    private com.google.protobuf.SingleFieldBuilder<
        bilibili.app.view.v1.RecDislike, bilibili.app.view.v1.RecDislike.Builder, bilibili.app.view.v1.RecDislikeOrBuilder> feedbackBuilder_;
    /**
     * <pre>
     * </pre>
     *
     * <code>.bilibili.app.view.v1.RecDislike feedback = 2;</code>
     * @return Whether the feedback field is set.
     */
    public boolean hasFeedback() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <pre>
     * </pre>
     *
     * <code>.bilibili.app.view.v1.RecDislike feedback = 2;</code>
     * @return The feedback.
     */
    public bilibili.app.view.v1.RecDislike getFeedback() {
      if (feedbackBuilder_ == null) {
        return feedback_ == null ? bilibili.app.view.v1.RecDislike.getDefaultInstance() : feedback_;
      } else {
        return feedbackBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * </pre>
     *
     * <code>.bilibili.app.view.v1.RecDislike feedback = 2;</code>
     */
    public Builder setFeedback(bilibili.app.view.v1.RecDislike value) {
      if (feedbackBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        feedback_ = value;
      } else {
        feedbackBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * </pre>
     *
     * <code>.bilibili.app.view.v1.RecDislike feedback = 2;</code>
     */
    public Builder setFeedback(
        bilibili.app.view.v1.RecDislike.Builder builderForValue) {
      if (feedbackBuilder_ == null) {
        feedback_ = builderForValue.build();
      } else {
        feedbackBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * </pre>
     *
     * <code>.bilibili.app.view.v1.RecDislike feedback = 2;</code>
     */
    public Builder mergeFeedback(bilibili.app.view.v1.RecDislike value) {
      if (feedbackBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0) &&
          feedback_ != null &&
          feedback_ != bilibili.app.view.v1.RecDislike.getDefaultInstance()) {
          getFeedbackBuilder().mergeFrom(value);
        } else {
          feedback_ = value;
        }
      } else {
        feedbackBuilder_.mergeFrom(value);
      }
      if (feedback_ != null) {
        bitField0_ |= 0x00000002;
        onChanged();
      }
      return this;
    }
    /**
     * <pre>
     * </pre>
     *
     * <code>.bilibili.app.view.v1.RecDislike feedback = 2;</code>
     */
    public Builder clearFeedback() {
      bitField0_ = (bitField0_ & ~0x00000002);
      feedback_ = null;
      if (feedbackBuilder_ != null) {
        feedbackBuilder_.dispose();
        feedbackBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <pre>
     * </pre>
     *
     * <code>.bilibili.app.view.v1.RecDislike feedback = 2;</code>
     */
    public bilibili.app.view.v1.RecDislike.Builder getFeedbackBuilder() {
      bitField0_ |= 0x00000002;
      onChanged();
      return getFeedbackFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * </pre>
     *
     * <code>.bilibili.app.view.v1.RecDislike feedback = 2;</code>
     */
    public bilibili.app.view.v1.RecDislikeOrBuilder getFeedbackOrBuilder() {
      if (feedbackBuilder_ != null) {
        return feedbackBuilder_.getMessageOrBuilder();
      } else {
        return feedback_ == null ?
            bilibili.app.view.v1.RecDislike.getDefaultInstance() : feedback_;
      }
    }
    /**
     * <pre>
     * </pre>
     *
     * <code>.bilibili.app.view.v1.RecDislike feedback = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        bilibili.app.view.v1.RecDislike, bilibili.app.view.v1.RecDislike.Builder, bilibili.app.view.v1.RecDislikeOrBuilder> 
        getFeedbackFieldBuilder() {
      if (feedbackBuilder_ == null) {
        feedbackBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            bilibili.app.view.v1.RecDislike, bilibili.app.view.v1.RecDislike.Builder, bilibili.app.view.v1.RecDislikeOrBuilder>(
                getFeedback(),
                getParentForChildren(),
                isClean());
        feedback_ = null;
      }
      return feedbackBuilder_;
    }

    private boolean watchLater_ ;
    /**
     * <pre>
     * </pre>
     *
     * <code>bool watch_later = 3;</code>
     * @return The watchLater.
     */
    @java.lang.Override
    public boolean getWatchLater() {
      return watchLater_;
    }
    /**
     * <pre>
     * </pre>
     *
     * <code>bool watch_later = 3;</code>
     * @param value The watchLater to set.
     * @return This builder for chaining.
     */
    public Builder setWatchLater(boolean value) {

      watchLater_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * </pre>
     *
     * <code>bool watch_later = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearWatchLater() {
      bitField0_ = (bitField0_ & ~0x00000004);
      watchLater_ = false;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:bilibili.app.view.v1.RecThreePoint)
  }

  // @@protoc_insertion_point(class_scope:bilibili.app.view.v1.RecThreePoint)
  private static final bilibili.app.view.v1.RecThreePoint DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new bilibili.app.view.v1.RecThreePoint();
  }

  public static bilibili.app.view.v1.RecThreePoint getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<RecThreePoint>
      PARSER = new com.google.protobuf.AbstractParser<RecThreePoint>() {
    @java.lang.Override
    public RecThreePoint parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<RecThreePoint> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<RecThreePoint> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public bilibili.app.view.v1.RecThreePoint getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

