// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: bilibili/app/dynamic/v2/dynamic.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package bilibili.app.dynamic.v2;

@kotlin.jvm.JvmName("-initializecampusRcmdFeedReq")
public inline fun campusRcmdFeedReq(block: bilibili.app.dynamic.v2.CampusRcmdFeedReqKt.Dsl.() -> kotlin.Unit): bilibili.app.dynamic.v2.CampusRcmdFeedReq =
  bilibili.app.dynamic.v2.CampusRcmdFeedReqKt.Dsl._create(bilibili.app.dynamic.v2.CampusRcmdFeedReq.newBuilder()).apply { block() }._build()
/**
 * ```
 * ```
 *
 * Protobuf type `bilibili.app.dynamic.v2.CampusRcmdFeedReq`
 */
public object CampusRcmdFeedReqKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: bilibili.app.dynamic.v2.CampusRcmdFeedReq.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: bilibili.app.dynamic.v2.CampusRcmdFeedReq.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): bilibili.app.dynamic.v2.CampusRcmdFeedReq = _builder.build()

    /**
     * ```
     * ```
     *
     * `int64 campus_id = 1;`
     */
    public var campusId: kotlin.Long
      @JvmName("getCampusId")
      get() = _builder.getCampusId()
      @JvmName("setCampusId")
      set(value) {
        _builder.setCampusId(value)
      }
    /**
     * ```
     * ```
     *
     * `int64 campus_id = 1;`
     */
    public fun clearCampusId() {
      _builder.clearCampusId()
    }

    /**
     * ```
     * ```
     *
     * `int32 first_time = 2;`
     */
    public var firstTime: kotlin.Int
      @JvmName("getFirstTime")
      get() = _builder.getFirstTime()
      @JvmName("setFirstTime")
      set(value) {
        _builder.setFirstTime(value)
      }
    /**
     * ```
     * ```
     *
     * `int32 first_time = 2;`
     */
    public fun clearFirstTime() {
      _builder.clearFirstTime()
    }

    /**
     * ```
     * ```
     *
     * `.bilibili.app.archive.middleware.v1.PlayerArgs player_args = 3;`
     */
    public var playerArgs: bilibili.app.archive.middleware.v1.PlayerArgs
      @JvmName("getPlayerArgs")
      get() = _builder.getPlayerArgs()
      @JvmName("setPlayerArgs")
      set(value) {
        _builder.setPlayerArgs(value)
      }
    /**
     * ```
     * ```
     *
     * `.bilibili.app.archive.middleware.v1.PlayerArgs player_args = 3;`
     */
    public fun clearPlayerArgs() {
      _builder.clearPlayerArgs()
    }
    /**
     * ```
     * ```
     *
     * `.bilibili.app.archive.middleware.v1.PlayerArgs player_args = 3;`
     * @return Whether the playerArgs field is set.
     */
    public fun hasPlayerArgs(): kotlin.Boolean {
      return _builder.hasPlayerArgs()
    }
    public val CampusRcmdFeedReqKt.Dsl.playerArgsOrNull: bilibili.app.archive.middleware.v1.PlayerArgs?
      get() = _builder.playerArgsOrNull

    /**
     * ```
     * ```
     *
     * `int32 local_time = 4;`
     */
    public var localTime: kotlin.Int
      @JvmName("getLocalTime")
      get() = _builder.getLocalTime()
      @JvmName("setLocalTime")
      set(value) {
        _builder.setLocalTime(value)
      }
    /**
     * ```
     * ```
     *
     * `int32 local_time = 4;`
     */
    public fun clearLocalTime() {
      _builder.clearLocalTime()
    }

    /**
     * ```
     * ```
     *
     * `int32 page = 5;`
     */
    public var page: kotlin.Int
      @JvmName("getPage")
      get() = _builder.getPage()
      @JvmName("setPage")
      set(value) {
        _builder.setPage(value)
      }
    /**
     * ```
     * ```
     *
     * `int32 page = 5;`
     */
    public fun clearPage() {
      _builder.clearPage()
    }

    /**
     * ```
     * ```
     *
     * `int32 scroll = 6;`
     */
    public var scroll: kotlin.Int
      @JvmName("getScroll")
      get() = _builder.getScroll()
      @JvmName("setScroll")
      set(value) {
        _builder.setScroll(value)
      }
    /**
     * ```
     * ```
     *
     * `int32 scroll = 6;`
     */
    public fun clearScroll() {
      _builder.clearScroll()
    }

    /**
     * ```
     * ```
     *
     * `string view_dyn_id = 7;`
     */
    public var viewDynId: kotlin.String
      @JvmName("getViewDynId")
      get() = _builder.getViewDynId()
      @JvmName("setViewDynId")
      set(value) {
        _builder.setViewDynId(value)
      }
    /**
     * ```
     * ```
     *
     * `string view_dyn_id = 7;`
     */
    public fun clearViewDynId() {
      _builder.clearViewDynId()
    }

    /**
     * ```
     * ```
     *
     * `.bilibili.app.dynamic.v2.CampusReqFromType from_type = 8;`
     */
    public var fromType: bilibili.app.dynamic.v2.CampusReqFromType
      @JvmName("getFromType")
      get() = _builder.getFromType()
      @JvmName("setFromType")
      set(value) {
        _builder.setFromType(value)
      }
    public var fromTypeValue: kotlin.Int
      @JvmName("getFromTypeValue")
      get() = _builder.getFromTypeValue()
      @JvmName("setFromTypeValue")
      set(value) {
        _builder.setFromTypeValue(value)
      }
    /**
     * ```
     * ```
     *
     * `.bilibili.app.dynamic.v2.CampusReqFromType from_type = 8;`
     */
    public fun clearFromType() {
      _builder.clearFromType()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun bilibili.app.dynamic.v2.CampusRcmdFeedReq.copy(block: `bilibili.app.dynamic.v2`.CampusRcmdFeedReqKt.Dsl.() -> kotlin.Unit): bilibili.app.dynamic.v2.CampusRcmdFeedReq =
  `bilibili.app.dynamic.v2`.CampusRcmdFeedReqKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val bilibili.app.dynamic.v2.CampusRcmdFeedReqOrBuilder.playerArgsOrNull: bilibili.app.archive.middleware.v1.PlayerArgs?
  get() = if (hasPlayerArgs()) getPlayerArgs() else null

