// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: bilibili/app/dynamic/v2/dynamic.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package bilibili.app.dynamic.v2;

@kotlin.jvm.JvmName("-initializeiconBadge")
public inline fun iconBadge(block: bilibili.app.dynamic.v2.IconBadgeKt.Dsl.() -> kotlin.Unit): bilibili.app.dynamic.v2.IconBadge =
  bilibili.app.dynamic.v2.IconBadgeKt.Dsl._create(bilibili.app.dynamic.v2.IconBadge.newBuilder()).apply { block() }._build()
/**
 * ```
 * ```
 *
 * Protobuf type `bilibili.app.dynamic.v2.IconBadge`
 */
public object IconBadgeKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: bilibili.app.dynamic.v2.IconBadge.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: bilibili.app.dynamic.v2.IconBadge.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): bilibili.app.dynamic.v2.IconBadge = _builder.build()

    /**
     * ```
     * ```
     *
     * `string icon_bg_url = 1;`
     */
    public var iconBgUrl: kotlin.String
      @JvmName("getIconBgUrl")
      get() = _builder.getIconBgUrl()
      @JvmName("setIconBgUrl")
      set(value) {
        _builder.setIconBgUrl(value)
      }
    /**
     * ```
     * ```
     *
     * `string icon_bg_url = 1;`
     */
    public fun clearIconBgUrl() {
      _builder.clearIconBgUrl()
    }

    /**
     * ```
     * ```
     *
     * `string text = 2;`
     */
    public var text: kotlin.String
      @JvmName("getText")
      get() = _builder.getText()
      @JvmName("setText")
      set(value) {
        _builder.setText(value)
      }
    /**
     * ```
     * ```
     *
     * `string text = 2;`
     */
    public fun clearText() {
      _builder.clearText()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun bilibili.app.dynamic.v2.IconBadge.copy(block: `bilibili.app.dynamic.v2`.IconBadgeKt.Dsl.() -> kotlin.Unit): bilibili.app.dynamic.v2.IconBadge =
  `bilibili.app.dynamic.v2`.IconBadgeKt.Dsl._create(this.toBuilder()).apply { block() }._build()

