// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: bilibili/app/dynamic/v2/opus.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package bilibili.app.dynamic.v2;

@kotlin.jvm.JvmName("-initializeopusItem")
public inline fun opusItem(block: bilibili.app.dynamic.v2.OpusItemKt.Dsl.() -> kotlin.Unit): bilibili.app.dynamic.v2.OpusItem =
  bilibili.app.dynamic.v2.OpusItemKt.Dsl._create(bilibili.app.dynamic.v2.OpusItem.newBuilder()).apply { block() }._build()
/**
 * ```
 * ```
 *
 * Protobuf type `bilibili.app.dynamic.v2.OpusItem`
 */
public object OpusItemKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: bilibili.app.dynamic.v2.OpusItem.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: bilibili.app.dynamic.v2.OpusItem.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): bilibili.app.dynamic.v2.OpusItem = _builder.build()

    /**
     * ```
     * ```
     *
     * `int64 opus_id = 1;`
     */
    public var opusId: kotlin.Long
      @JvmName("getOpusId")
      get() = _builder.getOpusId()
      @JvmName("setOpusId")
      set(value) {
        _builder.setOpusId(value)
      }
    /**
     * ```
     * ```
     *
     * `int64 opus_id = 1;`
     */
    public fun clearOpusId() {
      _builder.clearOpusId()
    }

    /**
     * ```
     * ```
     *
     * `.bilibili.app.dynamic.v2.OpusType opus_type = 2;`
     */
    public var opusType: bilibili.app.dynamic.v2.OpusType
      @JvmName("getOpusType")
      get() = _builder.getOpusType()
      @JvmName("setOpusType")
      set(value) {
        _builder.setOpusType(value)
      }
    public var opusTypeValue: kotlin.Int
      @JvmName("getOpusTypeValue")
      get() = _builder.getOpusTypeValue()
      @JvmName("setOpusTypeValue")
      set(value) {
        _builder.setOpusTypeValue(value)
      }
    /**
     * ```
     * ```
     *
     * `.bilibili.app.dynamic.v2.OpusType opus_type = 2;`
     */
    public fun clearOpusType() {
      _builder.clearOpusType()
    }

    /**
     * ```
     * ```
     *
     * `int64 oid = 3;`
     */
    public var oid: kotlin.Long
      @JvmName("getOid")
      get() = _builder.getOid()
      @JvmName("setOid")
      set(value) {
        _builder.setOid(value)
      }
    /**
     * ```
     * ```
     *
     * `int64 oid = 3;`
     */
    public fun clearOid() {
      _builder.clearOid()
    }

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class ModulesProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * ```
     * ```
     *
     * `repeated .bilibili.app.dynamic.v2.Module modules = 4;`
     */
     public val modules: com.google.protobuf.kotlin.DslList<bilibili.app.dynamic.v2.Module, ModulesProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.getModulesList()
      )
    /**
     * ```
     * ```
     *
     * `repeated .bilibili.app.dynamic.v2.Module modules = 4;`
     * @param value The modules to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addModules")
    public fun com.google.protobuf.kotlin.DslList<bilibili.app.dynamic.v2.Module, ModulesProxy>.add(value: bilibili.app.dynamic.v2.Module) {
      _builder.addModules(value)
    }
    /**
     * ```
     * ```
     *
     * `repeated .bilibili.app.dynamic.v2.Module modules = 4;`
     * @param value The modules to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignModules")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<bilibili.app.dynamic.v2.Module, ModulesProxy>.plusAssign(value: bilibili.app.dynamic.v2.Module) {
      add(value)
    }
    /**
     * ```
     * ```
     *
     * `repeated .bilibili.app.dynamic.v2.Module modules = 4;`
     * @param values The modules to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllModules")
    public fun com.google.protobuf.kotlin.DslList<bilibili.app.dynamic.v2.Module, ModulesProxy>.addAll(values: kotlin.collections.Iterable<bilibili.app.dynamic.v2.Module>) {
      _builder.addAllModules(values)
    }
    /**
     * ```
     * ```
     *
     * `repeated .bilibili.app.dynamic.v2.Module modules = 4;`
     * @param values The modules to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllModules")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<bilibili.app.dynamic.v2.Module, ModulesProxy>.plusAssign(values: kotlin.collections.Iterable<bilibili.app.dynamic.v2.Module>) {
      addAll(values)
    }
    /**
     * ```
     * ```
     *
     * `repeated .bilibili.app.dynamic.v2.Module modules = 4;`
     * @param index The index to set the value at.
     * @param value The modules to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setModules")
    public operator fun com.google.protobuf.kotlin.DslList<bilibili.app.dynamic.v2.Module, ModulesProxy>.set(index: kotlin.Int, value: bilibili.app.dynamic.v2.Module) {
      _builder.setModules(index, value)
    }
    /**
     * ```
     * ```
     *
     * `repeated .bilibili.app.dynamic.v2.Module modules = 4;`
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearModules")
    public fun com.google.protobuf.kotlin.DslList<bilibili.app.dynamic.v2.Module, ModulesProxy>.clear() {
      _builder.clearModules()
    }


    /**
     * ```
     * ```
     *
     * `.bilibili.app.dynamic.v2.Extend extend = 5;`
     */
    public var extend: bilibili.app.dynamic.v2.Extend
      @JvmName("getExtend")
      get() = _builder.getExtend()
      @JvmName("setExtend")
      set(value) {
        _builder.setExtend(value)
      }
    /**
     * ```
     * ```
     *
     * `.bilibili.app.dynamic.v2.Extend extend = 5;`
     */
    public fun clearExtend() {
      _builder.clearExtend()
    }
    /**
     * ```
     * ```
     *
     * `.bilibili.app.dynamic.v2.Extend extend = 5;`
     * @return Whether the extend field is set.
     */
    public fun hasExtend(): kotlin.Boolean {
      return _builder.hasExtend()
    }
    public val OpusItemKt.Dsl.extendOrNull: bilibili.app.dynamic.v2.Extend?
      get() = _builder.extendOrNull
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun bilibili.app.dynamic.v2.OpusItem.copy(block: `bilibili.app.dynamic.v2`.OpusItemKt.Dsl.() -> kotlin.Unit): bilibili.app.dynamic.v2.OpusItem =
  `bilibili.app.dynamic.v2`.OpusItemKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val bilibili.app.dynamic.v2.OpusItemOrBuilder.extendOrNull: bilibili.app.dynamic.v2.Extend?
  get() = if (hasExtend()) getExtend() else null

