// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: bilibili/app/dynamic/v2/dynamic.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package bilibili.app.dynamic.v2;

@kotlin.jvm.JvmName("-initializesearchInfo")
public inline fun searchInfo(block: bilibili.app.dynamic.v2.SearchInfoKt.Dsl.() -> kotlin.Unit): bilibili.app.dynamic.v2.SearchInfo =
  bilibili.app.dynamic.v2.SearchInfoKt.Dsl._create(bilibili.app.dynamic.v2.SearchInfo.newBuilder()).apply { block() }._build()
/**
 * ```
 * ```
 *
 * Protobuf type `bilibili.app.dynamic.v2.SearchInfo`
 */
public object SearchInfoKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: bilibili.app.dynamic.v2.SearchInfo.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: bilibili.app.dynamic.v2.SearchInfo.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): bilibili.app.dynamic.v2.SearchInfo = _builder.build()

    /**
     * ```
     * ```
     *
     * `string title = 1;`
     */
    public var title: kotlin.String
      @JvmName("getTitle")
      get() = _builder.getTitle()
      @JvmName("setTitle")
      set(value) {
        _builder.setTitle(value)
      }
    /**
     * ```
     * ```
     *
     * `string title = 1;`
     */
    public fun clearTitle() {
      _builder.clearTitle()
    }

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class ListProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * ```
     * ```
     *
     * `repeated .bilibili.app.dynamic.v2.DynamicItem list = 2;`
     */
     public val list: com.google.protobuf.kotlin.DslList<bilibili.app.dynamic.v2.DynamicItem, ListProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.getListList()
      )
    /**
     * ```
     * ```
     *
     * `repeated .bilibili.app.dynamic.v2.DynamicItem list = 2;`
     * @param value The list to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addList")
    public fun com.google.protobuf.kotlin.DslList<bilibili.app.dynamic.v2.DynamicItem, ListProxy>.add(value: bilibili.app.dynamic.v2.DynamicItem) {
      _builder.addList(value)
    }
    /**
     * ```
     * ```
     *
     * `repeated .bilibili.app.dynamic.v2.DynamicItem list = 2;`
     * @param value The list to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignList")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<bilibili.app.dynamic.v2.DynamicItem, ListProxy>.plusAssign(value: bilibili.app.dynamic.v2.DynamicItem) {
      add(value)
    }
    /**
     * ```
     * ```
     *
     * `repeated .bilibili.app.dynamic.v2.DynamicItem list = 2;`
     * @param values The list to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllList")
    public fun com.google.protobuf.kotlin.DslList<bilibili.app.dynamic.v2.DynamicItem, ListProxy>.addAll(values: kotlin.collections.Iterable<bilibili.app.dynamic.v2.DynamicItem>) {
      _builder.addAllList(values)
    }
    /**
     * ```
     * ```
     *
     * `repeated .bilibili.app.dynamic.v2.DynamicItem list = 2;`
     * @param values The list to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllList")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<bilibili.app.dynamic.v2.DynamicItem, ListProxy>.plusAssign(values: kotlin.collections.Iterable<bilibili.app.dynamic.v2.DynamicItem>) {
      addAll(values)
    }
    /**
     * ```
     * ```
     *
     * `repeated .bilibili.app.dynamic.v2.DynamicItem list = 2;`
     * @param index The index to set the value at.
     * @param value The list to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setList")
    public operator fun com.google.protobuf.kotlin.DslList<bilibili.app.dynamic.v2.DynamicItem, ListProxy>.set(index: kotlin.Int, value: bilibili.app.dynamic.v2.DynamicItem) {
      _builder.setList(index, value)
    }
    /**
     * ```
     * ```
     *
     * `repeated .bilibili.app.dynamic.v2.DynamicItem list = 2;`
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearList")
    public fun com.google.protobuf.kotlin.DslList<bilibili.app.dynamic.v2.DynamicItem, ListProxy>.clear() {
      _builder.clearList()
    }


    /**
     * ```
     * ```
     *
     * `string track_id = 3;`
     */
    public var trackId: kotlin.String
      @JvmName("getTrackId")
      get() = _builder.getTrackId()
      @JvmName("setTrackId")
      set(value) {
        _builder.setTrackId(value)
      }
    /**
     * ```
     * ```
     *
     * `string track_id = 3;`
     */
    public fun clearTrackId() {
      _builder.clearTrackId()
    }

    /**
     * ```
     * ```
     *
     * `int64 total = 4;`
     */
    public var total: kotlin.Long
      @JvmName("getTotal")
      get() = _builder.getTotal()
      @JvmName("setTotal")
      set(value) {
        _builder.setTotal(value)
      }
    /**
     * ```
     * ```
     *
     * `int64 total = 4;`
     */
    public fun clearTotal() {
      _builder.clearTotal()
    }

    /**
     * ```
     * ```
     *
     * `bool has_more = 5;`
     */
    public var hasMore: kotlin.Boolean
      @JvmName("getHasMore")
      get() = _builder.getHasMore()
      @JvmName("setHasMore")
      set(value) {
        _builder.setHasMore(value)
      }
    /**
     * ```
     * ```
     *
     * `bool has_more = 5;`
     */
    public fun clearHasMore() {
      _builder.clearHasMore()
    }

    /**
     * ```
     * ```
     *
     * `string version = 6;`
     */
    public var version: kotlin.String
      @JvmName("getVersion")
      get() = _builder.getVersion()
      @JvmName("setVersion")
      set(value) {
        _builder.setVersion(value)
      }
    /**
     * ```
     * ```
     *
     * `string version = 6;`
     */
    public fun clearVersion() {
      _builder.clearVersion()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun bilibili.app.dynamic.v2.SearchInfo.copy(block: `bilibili.app.dynamic.v2`.SearchInfoKt.Dsl.() -> kotlin.Unit): bilibili.app.dynamic.v2.SearchInfo =
  `bilibili.app.dynamic.v2`.SearchInfoKt.Dsl._create(this.toBuilder()).apply { block() }._build()

