// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: bilibili/app/dynamic/v2/dynamic.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package bilibili.app.dynamic.v2;

@kotlin.jvm.JvmName("-initializesetRecentCampusReq")
public inline fun setRecentCampusReq(block: bilibili.app.dynamic.v2.SetRecentCampusReqKt.Dsl.() -> kotlin.Unit): bilibili.app.dynamic.v2.SetRecentCampusReq =
  bilibili.app.dynamic.v2.SetRecentCampusReqKt.Dsl._create(bilibili.app.dynamic.v2.SetRecentCampusReq.newBuilder()).apply { block() }._build()
/**
 * ```
 * ```
 *
 * Protobuf type `bilibili.app.dynamic.v2.SetRecentCampusReq`
 */
public object SetRecentCampusReqKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: bilibili.app.dynamic.v2.SetRecentCampusReq.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: bilibili.app.dynamic.v2.SetRecentCampusReq.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): bilibili.app.dynamic.v2.SetRecentCampusReq = _builder.build()

    /**
     * ```
     * ```
     *
     * `int64 campus_id = 1;`
     */
    public var campusId: kotlin.Long
      @JvmName("getCampusId")
      get() = _builder.getCampusId()
      @JvmName("setCampusId")
      set(value) {
        _builder.setCampusId(value)
      }
    /**
     * ```
     * ```
     *
     * `int64 campus_id = 1;`
     */
    public fun clearCampusId() {
      _builder.clearCampusId()
    }

    /**
     * ```
     * ```
     *
     * `string campus_name = 2;`
     */
    public var campusName: kotlin.String
      @JvmName("getCampusName")
      get() = _builder.getCampusName()
      @JvmName("setCampusName")
      set(value) {
        _builder.setCampusName(value)
      }
    /**
     * ```
     * ```
     *
     * `string campus_name = 2;`
     */
    public fun clearCampusName() {
      _builder.clearCampusName()
    }

    /**
     * ```
     * ```
     *
     * `.bilibili.app.dynamic.v2.CampusReqFromType from_type = 3;`
     */
    public var fromType: bilibili.app.dynamic.v2.CampusReqFromType
      @JvmName("getFromType")
      get() = _builder.getFromType()
      @JvmName("setFromType")
      set(value) {
        _builder.setFromType(value)
      }
    public var fromTypeValue: kotlin.Int
      @JvmName("getFromTypeValue")
      get() = _builder.getFromTypeValue()
      @JvmName("setFromTypeValue")
      set(value) {
        _builder.setFromTypeValue(value)
      }
    /**
     * ```
     * ```
     *
     * `.bilibili.app.dynamic.v2.CampusReqFromType from_type = 3;`
     */
    public fun clearFromType() {
      _builder.clearFromType()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun bilibili.app.dynamic.v2.SetRecentCampusReq.copy(block: `bilibili.app.dynamic.v2`.SetRecentCampusReqKt.Dsl.() -> kotlin.Unit): bilibili.app.dynamic.v2.SetRecentCampusReq =
  `bilibili.app.dynamic.v2`.SetRecentCampusReqKt.Dsl._create(this.toBuilder()).apply { block() }._build()

