// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: bilibili/app/dynamic/v2/dynamic.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package bilibili.app.dynamic.v2;

@kotlin.jvm.JvmName("-initializethreePointFavorite")
public inline fun threePointFavorite(block: bilibili.app.dynamic.v2.ThreePointFavoriteKt.Dsl.() -> kotlin.Unit): bilibili.app.dynamic.v2.ThreePointFavorite =
  bilibili.app.dynamic.v2.ThreePointFavoriteKt.Dsl._create(bilibili.app.dynamic.v2.ThreePointFavorite.newBuilder()).apply { block() }._build()
/**
 * ```
 * 三点-收藏
 * ```
 *
 * Protobuf type `bilibili.app.dynamic.v2.ThreePointFavorite`
 */
public object ThreePointFavoriteKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: bilibili.app.dynamic.v2.ThreePointFavorite.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: bilibili.app.dynamic.v2.ThreePointFavorite.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): bilibili.app.dynamic.v2.ThreePointFavorite = _builder.build()

    /**
     * ```
     * icon
     * ```
     *
     * `string icon = 1;`
     */
    public var icon: kotlin.String
      @JvmName("getIcon")
      get() = _builder.getIcon()
      @JvmName("setIcon")
      set(value) {
        _builder.setIcon(value)
      }
    /**
     * ```
     * icon
     * ```
     *
     * `string icon = 1;`
     */
    public fun clearIcon() {
      _builder.clearIcon()
    }

    /**
     * ```
     * 标题
     * ```
     *
     * `string title = 2;`
     */
    public var title: kotlin.String
      @JvmName("getTitle")
      get() = _builder.getTitle()
      @JvmName("setTitle")
      set(value) {
        _builder.setTitle(value)
      }
    /**
     * ```
     * 标题
     * ```
     *
     * `string title = 2;`
     */
    public fun clearTitle() {
      _builder.clearTitle()
    }

    /**
     * ```
     * 物料ID
     * ```
     *
     * `int64 id = 3;`
     */
    public var id: kotlin.Long
      @JvmName("getId")
      get() = _builder.getId()
      @JvmName("setId")
      set(value) {
        _builder.setId(value)
      }
    /**
     * ```
     * 物料ID
     * ```
     *
     * `int64 id = 3;`
     */
    public fun clearId() {
      _builder.clearId()
    }

    /**
     * ```
     * 是否订阅
     * ```
     *
     * `bool is_favourite = 4;`
     */
    public var isFavourite: kotlin.Boolean
      @JvmName("getIsFavourite")
      get() = _builder.getIsFavourite()
      @JvmName("setIsFavourite")
      set(value) {
        _builder.setIsFavourite(value)
      }
    /**
     * ```
     * 是否订阅
     * ```
     *
     * `bool is_favourite = 4;`
     */
    public fun clearIsFavourite() {
      _builder.clearIsFavourite()
    }

    /**
     * ```
     * 取消收藏图标
     * ```
     *
     * `string cancel_icon = 5;`
     */
    public var cancelIcon: kotlin.String
      @JvmName("getCancelIcon")
      get() = _builder.getCancelIcon()
      @JvmName("setCancelIcon")
      set(value) {
        _builder.setCancelIcon(value)
      }
    /**
     * ```
     * 取消收藏图标
     * ```
     *
     * `string cancel_icon = 5;`
     */
    public fun clearCancelIcon() {
      _builder.clearCancelIcon()
    }

    /**
     * ```
     * 取消收藏文案
     * ```
     *
     * `string cancel_title = 6;`
     */
    public var cancelTitle: kotlin.String
      @JvmName("getCancelTitle")
      get() = _builder.getCancelTitle()
      @JvmName("setCancelTitle")
      set(value) {
        _builder.setCancelTitle(value)
      }
    /**
     * ```
     * 取消收藏文案
     * ```
     *
     * `string cancel_title = 6;`
     */
    public fun clearCancelTitle() {
      _builder.clearCancelTitle()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun bilibili.app.dynamic.v2.ThreePointFavorite.copy(block: `bilibili.app.dynamic.v2`.ThreePointFavoriteKt.Dsl.() -> kotlin.Unit): bilibili.app.dynamic.v2.ThreePointFavorite =
  `bilibili.app.dynamic.v2`.ThreePointFavoriteKt.Dsl._create(this.toBuilder()).apply { block() }._build()

