// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: bilibili/app/dynamic/v2/dynamic.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package bilibili.app.dynamic.v2;

@kotlin.jvm.JvmName("-initializethreePointWait")
public inline fun threePointWait(block: bilibili.app.dynamic.v2.ThreePointWaitKt.Dsl.() -> kotlin.Unit): bilibili.app.dynamic.v2.ThreePointWait =
  bilibili.app.dynamic.v2.ThreePointWaitKt.Dsl._create(bilibili.app.dynamic.v2.ThreePointWait.newBuilder()).apply { block() }._build()
/**
 * ```
 * 三点-稍后在看
 * ```
 *
 * Protobuf type `bilibili.app.dynamic.v2.ThreePointWait`
 */
public object ThreePointWaitKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: bilibili.app.dynamic.v2.ThreePointWait.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: bilibili.app.dynamic.v2.ThreePointWait.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): bilibili.app.dynamic.v2.ThreePointWait = _builder.build()

    /**
     * ```
     * addition icon
     * ```
     *
     * `string addition_icon = 1;`
     */
    public var additionIcon: kotlin.String
      @JvmName("getAdditionIcon")
      get() = _builder.getAdditionIcon()
      @JvmName("setAdditionIcon")
      set(value) {
        _builder.setAdditionIcon(value)
      }
    /**
     * ```
     * addition icon
     * ```
     *
     * `string addition_icon = 1;`
     */
    public fun clearAdditionIcon() {
      _builder.clearAdditionIcon()
    }

    /**
     * ```
     * 已添加时的文案
     * ```
     *
     * `string addition_text = 2;`
     */
    public var additionText: kotlin.String
      @JvmName("getAdditionText")
      get() = _builder.getAdditionText()
      @JvmName("setAdditionText")
      set(value) {
        _builder.setAdditionText(value)
      }
    /**
     * ```
     * 已添加时的文案
     * ```
     *
     * `string addition_text = 2;`
     */
    public fun clearAdditionText() {
      _builder.clearAdditionText()
    }

    /**
     * ```
     * no addition icon
     * ```
     *
     * `string no_addition_icon = 3;`
     */
    public var noAdditionIcon: kotlin.String
      @JvmName("getNoAdditionIcon")
      get() = _builder.getNoAdditionIcon()
      @JvmName("setNoAdditionIcon")
      set(value) {
        _builder.setNoAdditionIcon(value)
      }
    /**
     * ```
     * no addition icon
     * ```
     *
     * `string no_addition_icon = 3;`
     */
    public fun clearNoAdditionIcon() {
      _builder.clearNoAdditionIcon()
    }

    /**
     * ```
     * 未添加时的文案
     * ```
     *
     * `string no_addition_text = 4;`
     */
    public var noAdditionText: kotlin.String
      @JvmName("getNoAdditionText")
      get() = _builder.getNoAdditionText()
      @JvmName("setNoAdditionText")
      set(value) {
        _builder.setNoAdditionText(value)
      }
    /**
     * ```
     * 未添加时的文案
     * ```
     *
     * `string no_addition_text = 4;`
     */
    public fun clearNoAdditionText() {
      _builder.clearNoAdditionText()
    }

    /**
     * ```
     * avid
     * ```
     *
     * `int64 id = 5;`
     */
    public var id: kotlin.Long
      @JvmName("getId")
      get() = _builder.getId()
      @JvmName("setId")
      set(value) {
        _builder.setId(value)
      }
    /**
     * ```
     * avid
     * ```
     *
     * `int64 id = 5;`
     */
    public fun clearId() {
      _builder.clearId()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun bilibili.app.dynamic.v2.ThreePointWait.copy(block: `bilibili.app.dynamic.v2`.ThreePointWaitKt.Dsl.() -> kotlin.Unit): bilibili.app.dynamic.v2.ThreePointWait =
  `bilibili.app.dynamic.v2`.ThreePointWaitKt.Dsl._create(this.toBuilder()).apply { block() }._build()

