// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: bilibili/community/service/dm/v1/dm.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package bilibili.community.service.dm.v1;

@kotlin.jvm.JvmName("-initializeclickButton")
public inline fun clickButton(block: bilibili.community.service.dm.v1.ClickButtonKt.Dsl.() -> kotlin.Unit): bilibili.community.service.dm.v1.ClickButton =
  bilibili.community.service.dm.v1.ClickButtonKt.Dsl._create(bilibili.community.service.dm.v1.ClickButton.newBuilder()).apply { block() }._build()
/**
 * ```
 * ```
 *
 * Protobuf type `bilibili.community.service.dm.v1.ClickButton`
 */
public object ClickButtonKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: bilibili.community.service.dm.v1.ClickButton.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: bilibili.community.service.dm.v1.ClickButton.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): bilibili.community.service.dm.v1.ClickButton = _builder.build()

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class PortraitTextProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * ```
     * ```
     *
     * `repeated string portrait_text = 1;`
     * @return A list containing the portraitText.
     */
    public val portraitText: com.google.protobuf.kotlin.DslList<kotlin.String, PortraitTextProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.getPortraitTextList()
      )
    /**
     * ```
     * ```
     *
     * `repeated string portrait_text = 1;`
     * @param value The portraitText to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addPortraitText")
    public fun com.google.protobuf.kotlin.DslList<kotlin.String, PortraitTextProxy>.add(value: kotlin.String) {
      _builder.addPortraitText(value)
    }
    /**
     * ```
     * ```
     *
     * `repeated string portrait_text = 1;`
     * @param value The portraitText to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignPortraitText")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<kotlin.String, PortraitTextProxy>.plusAssign(value: kotlin.String) {
      add(value)
    }
    /**
     * ```
     * ```
     *
     * `repeated string portrait_text = 1;`
     * @param values The portraitText to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllPortraitText")
    public fun com.google.protobuf.kotlin.DslList<kotlin.String, PortraitTextProxy>.addAll(values: kotlin.collections.Iterable<kotlin.String>) {
      _builder.addAllPortraitText(values)
    }
    /**
     * ```
     * ```
     *
     * `repeated string portrait_text = 1;`
     * @param values The portraitText to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllPortraitText")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<kotlin.String, PortraitTextProxy>.plusAssign(values: kotlin.collections.Iterable<kotlin.String>) {
      addAll(values)
    }
    /**
     * ```
     * ```
     *
     * `repeated string portrait_text = 1;`
     * @param index The index to set the value at.
     * @param value The portraitText to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setPortraitText")
    public operator fun com.google.protobuf.kotlin.DslList<kotlin.String, PortraitTextProxy>.set(index: kotlin.Int, value: kotlin.String) {
      _builder.setPortraitText(index, value)
    }/**
     * ```
     * ```
     *
     * `repeated string portrait_text = 1;`
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearPortraitText")
    public fun com.google.protobuf.kotlin.DslList<kotlin.String, PortraitTextProxy>.clear() {
      _builder.clearPortraitText()
    }
    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class LandscapeTextProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * ```
     * ```
     *
     * `repeated string landscape_text = 2;`
     * @return A list containing the landscapeText.
     */
    public val landscapeText: com.google.protobuf.kotlin.DslList<kotlin.String, LandscapeTextProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.getLandscapeTextList()
      )
    /**
     * ```
     * ```
     *
     * `repeated string landscape_text = 2;`
     * @param value The landscapeText to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addLandscapeText")
    public fun com.google.protobuf.kotlin.DslList<kotlin.String, LandscapeTextProxy>.add(value: kotlin.String) {
      _builder.addLandscapeText(value)
    }
    /**
     * ```
     * ```
     *
     * `repeated string landscape_text = 2;`
     * @param value The landscapeText to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignLandscapeText")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<kotlin.String, LandscapeTextProxy>.plusAssign(value: kotlin.String) {
      add(value)
    }
    /**
     * ```
     * ```
     *
     * `repeated string landscape_text = 2;`
     * @param values The landscapeText to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllLandscapeText")
    public fun com.google.protobuf.kotlin.DslList<kotlin.String, LandscapeTextProxy>.addAll(values: kotlin.collections.Iterable<kotlin.String>) {
      _builder.addAllLandscapeText(values)
    }
    /**
     * ```
     * ```
     *
     * `repeated string landscape_text = 2;`
     * @param values The landscapeText to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllLandscapeText")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<kotlin.String, LandscapeTextProxy>.plusAssign(values: kotlin.collections.Iterable<kotlin.String>) {
      addAll(values)
    }
    /**
     * ```
     * ```
     *
     * `repeated string landscape_text = 2;`
     * @param index The index to set the value at.
     * @param value The landscapeText to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setLandscapeText")
    public operator fun com.google.protobuf.kotlin.DslList<kotlin.String, LandscapeTextProxy>.set(index: kotlin.Int, value: kotlin.String) {
      _builder.setLandscapeText(index, value)
    }/**
     * ```
     * ```
     *
     * `repeated string landscape_text = 2;`
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearLandscapeText")
    public fun com.google.protobuf.kotlin.DslList<kotlin.String, LandscapeTextProxy>.clear() {
      _builder.clearLandscapeText()
    }
    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class PortraitTextFocusProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * ```
     * ```
     *
     * `repeated string portrait_text_focus = 3;`
     * @return A list containing the portraitTextFocus.
     */
    public val portraitTextFocus: com.google.protobuf.kotlin.DslList<kotlin.String, PortraitTextFocusProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.getPortraitTextFocusList()
      )
    /**
     * ```
     * ```
     *
     * `repeated string portrait_text_focus = 3;`
     * @param value The portraitTextFocus to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addPortraitTextFocus")
    public fun com.google.protobuf.kotlin.DslList<kotlin.String, PortraitTextFocusProxy>.add(value: kotlin.String) {
      _builder.addPortraitTextFocus(value)
    }
    /**
     * ```
     * ```
     *
     * `repeated string portrait_text_focus = 3;`
     * @param value The portraitTextFocus to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignPortraitTextFocus")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<kotlin.String, PortraitTextFocusProxy>.plusAssign(value: kotlin.String) {
      add(value)
    }
    /**
     * ```
     * ```
     *
     * `repeated string portrait_text_focus = 3;`
     * @param values The portraitTextFocus to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllPortraitTextFocus")
    public fun com.google.protobuf.kotlin.DslList<kotlin.String, PortraitTextFocusProxy>.addAll(values: kotlin.collections.Iterable<kotlin.String>) {
      _builder.addAllPortraitTextFocus(values)
    }
    /**
     * ```
     * ```
     *
     * `repeated string portrait_text_focus = 3;`
     * @param values The portraitTextFocus to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllPortraitTextFocus")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<kotlin.String, PortraitTextFocusProxy>.plusAssign(values: kotlin.collections.Iterable<kotlin.String>) {
      addAll(values)
    }
    /**
     * ```
     * ```
     *
     * `repeated string portrait_text_focus = 3;`
     * @param index The index to set the value at.
     * @param value The portraitTextFocus to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setPortraitTextFocus")
    public operator fun com.google.protobuf.kotlin.DslList<kotlin.String, PortraitTextFocusProxy>.set(index: kotlin.Int, value: kotlin.String) {
      _builder.setPortraitTextFocus(index, value)
    }/**
     * ```
     * ```
     *
     * `repeated string portrait_text_focus = 3;`
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearPortraitTextFocus")
    public fun com.google.protobuf.kotlin.DslList<kotlin.String, PortraitTextFocusProxy>.clear() {
      _builder.clearPortraitTextFocus()
    }
    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class LandscapeTextFocusProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * ```
     * ```
     *
     * `repeated string landscape_text_focus = 4;`
     * @return A list containing the landscapeTextFocus.
     */
    public val landscapeTextFocus: com.google.protobuf.kotlin.DslList<kotlin.String, LandscapeTextFocusProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.getLandscapeTextFocusList()
      )
    /**
     * ```
     * ```
     *
     * `repeated string landscape_text_focus = 4;`
     * @param value The landscapeTextFocus to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addLandscapeTextFocus")
    public fun com.google.protobuf.kotlin.DslList<kotlin.String, LandscapeTextFocusProxy>.add(value: kotlin.String) {
      _builder.addLandscapeTextFocus(value)
    }
    /**
     * ```
     * ```
     *
     * `repeated string landscape_text_focus = 4;`
     * @param value The landscapeTextFocus to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignLandscapeTextFocus")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<kotlin.String, LandscapeTextFocusProxy>.plusAssign(value: kotlin.String) {
      add(value)
    }
    /**
     * ```
     * ```
     *
     * `repeated string landscape_text_focus = 4;`
     * @param values The landscapeTextFocus to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllLandscapeTextFocus")
    public fun com.google.protobuf.kotlin.DslList<kotlin.String, LandscapeTextFocusProxy>.addAll(values: kotlin.collections.Iterable<kotlin.String>) {
      _builder.addAllLandscapeTextFocus(values)
    }
    /**
     * ```
     * ```
     *
     * `repeated string landscape_text_focus = 4;`
     * @param values The landscapeTextFocus to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllLandscapeTextFocus")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<kotlin.String, LandscapeTextFocusProxy>.plusAssign(values: kotlin.collections.Iterable<kotlin.String>) {
      addAll(values)
    }
    /**
     * ```
     * ```
     *
     * `repeated string landscape_text_focus = 4;`
     * @param index The index to set the value at.
     * @param value The landscapeTextFocus to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setLandscapeTextFocus")
    public operator fun com.google.protobuf.kotlin.DslList<kotlin.String, LandscapeTextFocusProxy>.set(index: kotlin.Int, value: kotlin.String) {
      _builder.setLandscapeTextFocus(index, value)
    }/**
     * ```
     * ```
     *
     * `repeated string landscape_text_focus = 4;`
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearLandscapeTextFocus")
    public fun com.google.protobuf.kotlin.DslList<kotlin.String, LandscapeTextFocusProxy>.clear() {
      _builder.clearLandscapeTextFocus()
    }
    /**
     * ```
     * ```
     *
     * `.bilibili.community.service.dm.v1.RenderType render_type = 5;`
     */
    public var renderType: bilibili.community.service.dm.v1.RenderType
      @JvmName("getRenderType")
      get() = _builder.getRenderType()
      @JvmName("setRenderType")
      set(value) {
        _builder.setRenderType(value)
      }
    public var renderTypeValue: kotlin.Int
      @JvmName("getRenderTypeValue")
      get() = _builder.getRenderTypeValue()
      @JvmName("setRenderTypeValue")
      set(value) {
        _builder.setRenderTypeValue(value)
      }
    /**
     * ```
     * ```
     *
     * `.bilibili.community.service.dm.v1.RenderType render_type = 5;`
     */
    public fun clearRenderType() {
      _builder.clearRenderType()
    }

    /**
     * ```
     * ```
     *
     * `bool show = 6;`
     */
    public var show: kotlin.Boolean
      @JvmName("getShow")
      get() = _builder.getShow()
      @JvmName("setShow")
      set(value) {
        _builder.setShow(value)
      }
    /**
     * ```
     * ```
     *
     * `bool show = 6;`
     */
    public fun clearShow() {
      _builder.clearShow()
    }

    /**
     * ```
     * ```
     *
     * `.bilibili.community.service.dm.v1.Bubble bubble = 7;`
     */
    public var bubble: bilibili.community.service.dm.v1.Bubble
      @JvmName("getBubble")
      get() = _builder.getBubble()
      @JvmName("setBubble")
      set(value) {
        _builder.setBubble(value)
      }
    /**
     * ```
     * ```
     *
     * `.bilibili.community.service.dm.v1.Bubble bubble = 7;`
     */
    public fun clearBubble() {
      _builder.clearBubble()
    }
    /**
     * ```
     * ```
     *
     * `.bilibili.community.service.dm.v1.Bubble bubble = 7;`
     * @return Whether the bubble field is set.
     */
    public fun hasBubble(): kotlin.Boolean {
      return _builder.hasBubble()
    }
    public val ClickButtonKt.Dsl.bubbleOrNull: bilibili.community.service.dm.v1.Bubble?
      get() = _builder.bubbleOrNull
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun bilibili.community.service.dm.v1.ClickButton.copy(block: `bilibili.community.service.dm.v1`.ClickButtonKt.Dsl.() -> kotlin.Unit): bilibili.community.service.dm.v1.ClickButton =
  `bilibili.community.service.dm.v1`.ClickButtonKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val bilibili.community.service.dm.v1.ClickButtonOrBuilder.bubbleOrNull: bilibili.community.service.dm.v1.Bubble?
  get() = if (hasBubble()) getBubble() else null

