// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: bilibili/community/service/dm/v1/dm.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package bilibili.community.service.dm.v1;

@kotlin.jvm.JvmName("-initializedanmakuFlagConfig")
public inline fun danmakuFlagConfig(block: bilibili.community.service.dm.v1.DanmakuFlagConfigKt.Dsl.() -> kotlin.Unit): bilibili.community.service.dm.v1.DanmakuFlagConfig =
  bilibili.community.service.dm.v1.DanmakuFlagConfigKt.Dsl._create(bilibili.community.service.dm.v1.DanmakuFlagConfig.newBuilder()).apply { block() }._build()
/**
 * ```
 * 云屏蔽配置信息
 * ```
 *
 * Protobuf type `bilibili.community.service.dm.v1.DanmakuFlagConfig`
 */
public object DanmakuFlagConfigKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: bilibili.community.service.dm.v1.DanmakuFlagConfig.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: bilibili.community.service.dm.v1.DanmakuFlagConfig.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): bilibili.community.service.dm.v1.DanmakuFlagConfig = _builder.build()

    /**
     * ```
     * 云屏蔽等级
     * ```
     *
     * `int32 rec_flag = 1;`
     */
    public var recFlag: kotlin.Int
      @JvmName("getRecFlag")
      get() = _builder.getRecFlag()
      @JvmName("setRecFlag")
      set(value) {
        _builder.setRecFlag(value)
      }
    /**
     * ```
     * 云屏蔽等级
     * ```
     *
     * `int32 rec_flag = 1;`
     */
    public fun clearRecFlag() {
      _builder.clearRecFlag()
    }

    /**
     * ```
     * 云屏蔽文案
     * ```
     *
     * `string rec_text = 2;`
     */
    public var recText: kotlin.String
      @JvmName("getRecText")
      get() = _builder.getRecText()
      @JvmName("setRecText")
      set(value) {
        _builder.setRecText(value)
      }
    /**
     * ```
     * 云屏蔽文案
     * ```
     *
     * `string rec_text = 2;`
     */
    public fun clearRecText() {
      _builder.clearRecText()
    }

    /**
     * ```
     * 云屏蔽开关
     * ```
     *
     * `int32 rec_switch = 3;`
     */
    public var recSwitch: kotlin.Int
      @JvmName("getRecSwitch")
      get() = _builder.getRecSwitch()
      @JvmName("setRecSwitch")
      set(value) {
        _builder.setRecSwitch(value)
      }
    /**
     * ```
     * 云屏蔽开关
     * ```
     *
     * `int32 rec_switch = 3;`
     */
    public fun clearRecSwitch() {
      _builder.clearRecSwitch()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun bilibili.community.service.dm.v1.DanmakuFlagConfig.copy(block: `bilibili.community.service.dm.v1`.DanmakuFlagConfigKt.Dsl.() -> kotlin.Unit): bilibili.community.service.dm.v1.DanmakuFlagConfig =
  `bilibili.community.service.dm.v1`.DanmakuFlagConfigKt.Dsl._create(this.toBuilder()).apply { block() }._build()

