// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: bilibili/community/service/dm/v1/dm.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package bilibili.community.service.dm.v1;

@kotlin.jvm.JvmName("-initializeplayerDanmakuBlockscroll")
public inline fun playerDanmakuBlockscroll(block: bilibili.community.service.dm.v1.PlayerDanmakuBlockscrollKt.Dsl.() -> kotlin.Unit): bilibili.community.service.dm.v1.PlayerDanmakuBlockscroll =
  bilibili.community.service.dm.v1.PlayerDanmakuBlockscrollKt.Dsl._create(bilibili.community.service.dm.v1.PlayerDanmakuBlockscroll.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `bilibili.community.service.dm.v1.PlayerDanmakuBlockscroll`
 */
public object PlayerDanmakuBlockscrollKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: bilibili.community.service.dm.v1.PlayerDanmakuBlockscroll.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: bilibili.community.service.dm.v1.PlayerDanmakuBlockscroll.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): bilibili.community.service.dm.v1.PlayerDanmakuBlockscroll = _builder.build()

    /**
     * `bool value = 1;`
     */
    public var value: kotlin.Boolean
      @JvmName("getValue")
      get() = _builder.getValue()
      @JvmName("setValue")
      set(value) {
        _builder.setValue(value)
      }
    /**
     * `bool value = 1;`
     */
    public fun clearValue() {
      _builder.clearValue()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun bilibili.community.service.dm.v1.PlayerDanmakuBlockscroll.copy(block: `bilibili.community.service.dm.v1`.PlayerDanmakuBlockscrollKt.Dsl.() -> kotlin.Unit): bilibili.community.service.dm.v1.PlayerDanmakuBlockscroll =
  `bilibili.community.service.dm.v1`.PlayerDanmakuBlockscrollKt.Dsl._create(this.toBuilder()).apply { block() }._build()

