// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bilibili/app/viewunite/v1/viewunite.proto

// Protobuf Java Version: 4.26.1
package bilibili.app.viewunite.v1;

/**
 * <pre>
 * 评论区/弹幕 Tab 控制
 * </pre>
 *
 * Protobuf type {@code bilibili.app.viewunite.v1.TabControl}
 */
public final class TabControl extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:bilibili.app.viewunite.v1.TabControl)
    TabControlOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 26,
      /* patch= */ 1,
      /* suffix= */ "",
      TabControl.class.getName());
  }
  // Use TabControl.newBuilder() to construct.
  private TabControl(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private TabControl() {
    disableClickTip_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return bilibili.app.viewunite.v1.Viewunite.internal_static_bilibili_app_viewunite_v1_TabControl_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return bilibili.app.viewunite.v1.Viewunite.internal_static_bilibili_app_viewunite_v1_TabControl_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            bilibili.app.viewunite.v1.TabControl.class, bilibili.app.viewunite.v1.TabControl.Builder.class);
  }

  public static final int LIMIT_FIELD_NUMBER = 1;
  private boolean limit_ = false;
  /**
   * <pre>
   * </pre>
   *
   * <code>bool limit = 1;</code>
   * @return The limit.
   */
  @java.lang.Override
  public boolean getLimit() {
    return limit_;
  }

  public static final int DISABLE_FIELD_NUMBER = 2;
  private boolean disable_ = false;
  /**
   * <pre>
   * </pre>
   *
   * <code>bool disable = 2;</code>
   * @return The disable.
   */
  @java.lang.Override
  public boolean getDisable() {
    return disable_;
  }

  public static final int DISABLE_CLICK_TIP_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object disableClickTip_ = "";
  /**
   * <pre>
   * </pre>
   *
   * <code>string disable_click_tip = 3;</code>
   * @return The disableClickTip.
   */
  @java.lang.Override
  public java.lang.String getDisableClickTip() {
    java.lang.Object ref = disableClickTip_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      disableClickTip_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * </pre>
   *
   * <code>string disable_click_tip = 3;</code>
   * @return The bytes for disableClickTip.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getDisableClickTipBytes() {
    java.lang.Object ref = disableClickTip_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      disableClickTip_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (limit_ != false) {
      output.writeBool(1, limit_);
    }
    if (disable_ != false) {
      output.writeBool(2, disable_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(disableClickTip_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 3, disableClickTip_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (limit_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(1, limit_);
    }
    if (disable_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(2, disable_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(disableClickTip_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(3, disableClickTip_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof bilibili.app.viewunite.v1.TabControl)) {
      return super.equals(obj);
    }
    bilibili.app.viewunite.v1.TabControl other = (bilibili.app.viewunite.v1.TabControl) obj;

    if (getLimit()
        != other.getLimit()) return false;
    if (getDisable()
        != other.getDisable()) return false;
    if (!getDisableClickTip()
        .equals(other.getDisableClickTip())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + LIMIT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getLimit());
    hash = (37 * hash) + DISABLE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getDisable());
    hash = (37 * hash) + DISABLE_CLICK_TIP_FIELD_NUMBER;
    hash = (53 * hash) + getDisableClickTip().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static bilibili.app.viewunite.v1.TabControl parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static bilibili.app.viewunite.v1.TabControl parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static bilibili.app.viewunite.v1.TabControl parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static bilibili.app.viewunite.v1.TabControl parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static bilibili.app.viewunite.v1.TabControl parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static bilibili.app.viewunite.v1.TabControl parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static bilibili.app.viewunite.v1.TabControl parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static bilibili.app.viewunite.v1.TabControl parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static bilibili.app.viewunite.v1.TabControl parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static bilibili.app.viewunite.v1.TabControl parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static bilibili.app.viewunite.v1.TabControl parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static bilibili.app.viewunite.v1.TabControl parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(bilibili.app.viewunite.v1.TabControl prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * 评论区/弹幕 Tab 控制
   * </pre>
   *
   * Protobuf type {@code bilibili.app.viewunite.v1.TabControl}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:bilibili.app.viewunite.v1.TabControl)
      bilibili.app.viewunite.v1.TabControlOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return bilibili.app.viewunite.v1.Viewunite.internal_static_bilibili_app_viewunite_v1_TabControl_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return bilibili.app.viewunite.v1.Viewunite.internal_static_bilibili_app_viewunite_v1_TabControl_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              bilibili.app.viewunite.v1.TabControl.class, bilibili.app.viewunite.v1.TabControl.Builder.class);
    }

    // Construct using bilibili.app.viewunite.v1.TabControl.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      limit_ = false;
      disable_ = false;
      disableClickTip_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return bilibili.app.viewunite.v1.Viewunite.internal_static_bilibili_app_viewunite_v1_TabControl_descriptor;
    }

    @java.lang.Override
    public bilibili.app.viewunite.v1.TabControl getDefaultInstanceForType() {
      return bilibili.app.viewunite.v1.TabControl.getDefaultInstance();
    }

    @java.lang.Override
    public bilibili.app.viewunite.v1.TabControl build() {
      bilibili.app.viewunite.v1.TabControl result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public bilibili.app.viewunite.v1.TabControl buildPartial() {
      bilibili.app.viewunite.v1.TabControl result = new bilibili.app.viewunite.v1.TabControl(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(bilibili.app.viewunite.v1.TabControl result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.limit_ = limit_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.disable_ = disable_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.disableClickTip_ = disableClickTip_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof bilibili.app.viewunite.v1.TabControl) {
        return mergeFrom((bilibili.app.viewunite.v1.TabControl)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(bilibili.app.viewunite.v1.TabControl other) {
      if (other == bilibili.app.viewunite.v1.TabControl.getDefaultInstance()) return this;
      if (other.getLimit() != false) {
        setLimit(other.getLimit());
      }
      if (other.getDisable() != false) {
        setDisable(other.getDisable());
      }
      if (!other.getDisableClickTip().isEmpty()) {
        disableClickTip_ = other.disableClickTip_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              limit_ = input.readBool();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 16: {
              disable_ = input.readBool();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 26: {
              disableClickTip_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private boolean limit_ ;
    /**
     * <pre>
     * </pre>
     *
     * <code>bool limit = 1;</code>
     * @return The limit.
     */
    @java.lang.Override
    public boolean getLimit() {
      return limit_;
    }
    /**
     * <pre>
     * </pre>
     *
     * <code>bool limit = 1;</code>
     * @param value The limit to set.
     * @return This builder for chaining.
     */
    public Builder setLimit(boolean value) {

      limit_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * </pre>
     *
     * <code>bool limit = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearLimit() {
      bitField0_ = (bitField0_ & ~0x00000001);
      limit_ = false;
      onChanged();
      return this;
    }

    private boolean disable_ ;
    /**
     * <pre>
     * </pre>
     *
     * <code>bool disable = 2;</code>
     * @return The disable.
     */
    @java.lang.Override
    public boolean getDisable() {
      return disable_;
    }
    /**
     * <pre>
     * </pre>
     *
     * <code>bool disable = 2;</code>
     * @param value The disable to set.
     * @return This builder for chaining.
     */
    public Builder setDisable(boolean value) {

      disable_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * </pre>
     *
     * <code>bool disable = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearDisable() {
      bitField0_ = (bitField0_ & ~0x00000002);
      disable_ = false;
      onChanged();
      return this;
    }

    private java.lang.Object disableClickTip_ = "";
    /**
     * <pre>
     * </pre>
     *
     * <code>string disable_click_tip = 3;</code>
     * @return The disableClickTip.
     */
    public java.lang.String getDisableClickTip() {
      java.lang.Object ref = disableClickTip_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        disableClickTip_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * </pre>
     *
     * <code>string disable_click_tip = 3;</code>
     * @return The bytes for disableClickTip.
     */
    public com.google.protobuf.ByteString
        getDisableClickTipBytes() {
      java.lang.Object ref = disableClickTip_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        disableClickTip_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * </pre>
     *
     * <code>string disable_click_tip = 3;</code>
     * @param value The disableClickTip to set.
     * @return This builder for chaining.
     */
    public Builder setDisableClickTip(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      disableClickTip_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * </pre>
     *
     * <code>string disable_click_tip = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearDisableClickTip() {
      disableClickTip_ = getDefaultInstance().getDisableClickTip();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * </pre>
     *
     * <code>string disable_click_tip = 3;</code>
     * @param value The bytes for disableClickTip to set.
     * @return This builder for chaining.
     */
    public Builder setDisableClickTipBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      disableClickTip_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:bilibili.app.viewunite.v1.TabControl)
  }

  // @@protoc_insertion_point(class_scope:bilibili.app.viewunite.v1.TabControl)
  private static final bilibili.app.viewunite.v1.TabControl DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new bilibili.app.viewunite.v1.TabControl();
  }

  public static bilibili.app.viewunite.v1.TabControl getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<TabControl>
      PARSER = new com.google.protobuf.AbstractParser<TabControl>() {
    @java.lang.Override
    public TabControl parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<TabControl> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<TabControl> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public bilibili.app.viewunite.v1.TabControl getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

