// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: bilibili/main/common/arch/doll/v1/doll.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package bilibili.main.common.arch.doll.v1;

