// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: bilibili/app/topic/v1/topic.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package bilibili.app.topic.v1;

@kotlin.jvm.JvmName("-initializerightTopLiveBadge")
public inline fun rightTopLiveBadge(block: bilibili.app.topic.v1.RightTopLiveBadgeKt.Dsl.() -> kotlin.Unit): bilibili.app.topic.v1.RightTopLiveBadge =
  bilibili.app.topic.v1.RightTopLiveBadgeKt.Dsl._create(bilibili.app.topic.v1.RightTopLiveBadge.newBuilder()).apply { block() }._build()
/**
 * ```
 * ```
 *
 * Protobuf type `bilibili.app.topic.v1.RightTopLiveBadge`
 */
public object RightTopLiveBadgeKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: bilibili.app.topic.v1.RightTopLiveBadge.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: bilibili.app.topic.v1.RightTopLiveBadge.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): bilibili.app.topic.v1.RightTopLiveBadge = _builder.build()

    /**
     * ```
     * ```
     *
     * `int64 live_status = 1;`
     */
    public var liveStatus: kotlin.Long
      @JvmName("getLiveStatus")
      get() = _builder.getLiveStatus()
      @JvmName("setLiveStatus")
      set(value) {
        _builder.setLiveStatus(value)
      }
    /**
     * ```
     * ```
     *
     * `int64 live_status = 1;`
     */
    public fun clearLiveStatus() {
      _builder.clearLiveStatus()
    }

    /**
     * ```
     * ```
     *
     * `.bilibili.app.topic.v1.LiveBadgeResource in_live = 2;`
     */
    public var inLive: bilibili.app.topic.v1.LiveBadgeResource
      @JvmName("getInLive")
      get() = _builder.getInLive()
      @JvmName("setInLive")
      set(value) {
        _builder.setInLive(value)
      }
    /**
     * ```
     * ```
     *
     * `.bilibili.app.topic.v1.LiveBadgeResource in_live = 2;`
     */
    public fun clearInLive() {
      _builder.clearInLive()
    }
    /**
     * ```
     * ```
     *
     * `.bilibili.app.topic.v1.LiveBadgeResource in_live = 2;`
     * @return Whether the inLive field is set.
     */
    public fun hasInLive(): kotlin.Boolean {
      return _builder.hasInLive()
    }
    public val RightTopLiveBadgeKt.Dsl.inLiveOrNull: bilibili.app.topic.v1.LiveBadgeResource?
      get() = _builder.inLiveOrNull

    /**
     * ```
     * ```
     *
     * `string live_stats_desc = 3;`
     */
    public var liveStatsDesc: kotlin.String
      @JvmName("getLiveStatsDesc")
      get() = _builder.getLiveStatsDesc()
      @JvmName("setLiveStatsDesc")
      set(value) {
        _builder.setLiveStatsDesc(value)
      }
    /**
     * ```
     * ```
     *
     * `string live_stats_desc = 3;`
     */
    public fun clearLiveStatsDesc() {
      _builder.clearLiveStatsDesc()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun bilibili.app.topic.v1.RightTopLiveBadge.copy(block: `bilibili.app.topic.v1`.RightTopLiveBadgeKt.Dsl.() -> kotlin.Unit): bilibili.app.topic.v1.RightTopLiveBadge =
  `bilibili.app.topic.v1`.RightTopLiveBadgeKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val bilibili.app.topic.v1.RightTopLiveBadgeOrBuilder.inLiveOrNull: bilibili.app.topic.v1.LiveBadgeResource?
  get() = if (hasInLive()) getInLive() else null

