// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: bilibili/im/interfaces/v1/im.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package bilibili.im.interface1.v1;

@kotlin.jvm.JvmName("-initializereqGetSpecificSessions")
public inline fun reqGetSpecificSessions(block: bilibili.im.interface1.v1.ReqGetSpecificSessionsKt.Dsl.() -> kotlin.Unit): bilibili.im.interface1.v1.ReqGetSpecificSessions =
  bilibili.im.interface1.v1.ReqGetSpecificSessionsKt.Dsl._create(bilibili.im.interface1.v1.ReqGetSpecificSessions.newBuilder()).apply { block() }._build()
/**
 * ```
 * -请求
 * ```
 *
 * Protobuf type `bilibili.im.interface.v1.ReqGetSpecificSessions`
 */
public object ReqGetSpecificSessionsKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: bilibili.im.interface1.v1.ReqGetSpecificSessions.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: bilibili.im.interface1.v1.ReqGetSpecificSessions.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): bilibili.im.interface1.v1.ReqGetSpecificSessions = _builder.build()

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class TalkerSessionsProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * ```
     * 具体会话详情
     * ```
     *
     * `repeated .bilibili.im.interface.v1.SimpleSession talker_sessions = 1;`
     */
     public val talkerSessions: com.google.protobuf.kotlin.DslList<bilibili.im.interface1.v1.SimpleSession, TalkerSessionsProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.getTalkerSessionsList()
      )
    /**
     * ```
     * 具体会话详情
     * ```
     *
     * `repeated .bilibili.im.interface.v1.SimpleSession talker_sessions = 1;`
     * @param value The talkerSessions to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addTalkerSessions")
    public fun com.google.protobuf.kotlin.DslList<bilibili.im.interface1.v1.SimpleSession, TalkerSessionsProxy>.add(value: bilibili.im.interface1.v1.SimpleSession) {
      _builder.addTalkerSessions(value)
    }
    /**
     * ```
     * 具体会话详情
     * ```
     *
     * `repeated .bilibili.im.interface.v1.SimpleSession talker_sessions = 1;`
     * @param value The talkerSessions to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignTalkerSessions")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<bilibili.im.interface1.v1.SimpleSession, TalkerSessionsProxy>.plusAssign(value: bilibili.im.interface1.v1.SimpleSession) {
      add(value)
    }
    /**
     * ```
     * 具体会话详情
     * ```
     *
     * `repeated .bilibili.im.interface.v1.SimpleSession talker_sessions = 1;`
     * @param values The talkerSessions to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllTalkerSessions")
    public fun com.google.protobuf.kotlin.DslList<bilibili.im.interface1.v1.SimpleSession, TalkerSessionsProxy>.addAll(values: kotlin.collections.Iterable<bilibili.im.interface1.v1.SimpleSession>) {
      _builder.addAllTalkerSessions(values)
    }
    /**
     * ```
     * 具体会话详情
     * ```
     *
     * `repeated .bilibili.im.interface.v1.SimpleSession talker_sessions = 1;`
     * @param values The talkerSessions to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllTalkerSessions")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<bilibili.im.interface1.v1.SimpleSession, TalkerSessionsProxy>.plusAssign(values: kotlin.collections.Iterable<bilibili.im.interface1.v1.SimpleSession>) {
      addAll(values)
    }
    /**
     * ```
     * 具体会话详情
     * ```
     *
     * `repeated .bilibili.im.interface.v1.SimpleSession talker_sessions = 1;`
     * @param index The index to set the value at.
     * @param value The talkerSessions to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setTalkerSessions")
    public operator fun com.google.protobuf.kotlin.DslList<bilibili.im.interface1.v1.SimpleSession, TalkerSessionsProxy>.set(index: kotlin.Int, value: bilibili.im.interface1.v1.SimpleSession) {
      _builder.setTalkerSessions(index, value)
    }
    /**
     * ```
     * 具体会话详情
     * ```
     *
     * `repeated .bilibili.im.interface.v1.SimpleSession talker_sessions = 1;`
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearTalkerSessions")
    public fun com.google.protobuf.kotlin.DslList<bilibili.im.interface1.v1.SimpleSession, TalkerSessionsProxy>.clear() {
      _builder.clearTalkerSessions()
    }

  }
}
@kotlin.jvm.JvmSynthetic
public inline fun bilibili.im.interface1.v1.ReqGetSpecificSessions.copy(block: `bilibili.im.interface1.v1`.ReqGetSpecificSessionsKt.Dsl.() -> kotlin.Unit): bilibili.im.interface1.v1.ReqGetSpecificSessions =
  `bilibili.im.interface1.v1`.ReqGetSpecificSessionsKt.Dsl._create(this.toBuilder()).apply { block() }._build()

