// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: bilibili/im/interfaces/v1/im.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package bilibili.im.interface1.v1;

@kotlin.jvm.JvmName("-initializereqTotalUnread")
public inline fun reqTotalUnread(block: bilibili.im.interface1.v1.ReqTotalUnreadKt.Dsl.() -> kotlin.Unit): bilibili.im.interface1.v1.ReqTotalUnread =
  bilibili.im.interface1.v1.ReqTotalUnreadKt.Dsl._create(bilibili.im.interface1.v1.ReqTotalUnread.newBuilder()).apply { block() }._build()
/**
 * ```
 * ```
 *
 * Protobuf type `bilibili.im.interface.v1.ReqTotalUnread`
 */
public object ReqTotalUnreadKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: bilibili.im.interface1.v1.ReqTotalUnread.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: bilibili.im.interface1.v1.ReqTotalUnread.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): bilibili.im.interface1.v1.ReqTotalUnread = _builder.build()

    /**
     * ```
     * ```
     *
     * `int32 unread_type = 1;`
     */
    public var unreadType: kotlin.Int
      @JvmName("getUnreadType")
      get() = _builder.getUnreadType()
      @JvmName("setUnreadType")
      set(value) {
        _builder.setUnreadType(value)
      }
    /**
     * ```
     * ```
     *
     * `int32 unread_type = 1;`
     */
    public fun clearUnreadType() {
      _builder.clearUnreadType()
    }

    /**
     * ```
     * ```
     *
     * `int32 show_unfollow_list = 2;`
     */
    public var showUnfollowList: kotlin.Int
      @JvmName("getShowUnfollowList")
      get() = _builder.getShowUnfollowList()
      @JvmName("setShowUnfollowList")
      set(value) {
        _builder.setShowUnfollowList(value)
      }
    /**
     * ```
     * ```
     *
     * `int32 show_unfollow_list = 2;`
     */
    public fun clearShowUnfollowList() {
      _builder.clearShowUnfollowList()
    }

    /**
     * ```
     * ```
     *
     * `int64 uid = 3;`
     */
    public var uid: kotlin.Long
      @JvmName("getUid")
      get() = _builder.getUid()
      @JvmName("setUid")
      set(value) {
        _builder.setUid(value)
      }
    /**
     * ```
     * ```
     *
     * `int64 uid = 3;`
     */
    public fun clearUid() {
      _builder.clearUid()
    }

    /**
     * ```
     * ```
     *
     * `int32 show_dustbin = 4;`
     */
    public var showDustbin: kotlin.Int
      @JvmName("getShowDustbin")
      get() = _builder.getShowDustbin()
      @JvmName("setShowDustbin")
      set(value) {
        _builder.setShowDustbin(value)
      }
    /**
     * ```
     * ```
     *
     * `int32 show_dustbin = 4;`
     */
    public fun clearShowDustbin() {
      _builder.clearShowDustbin()
    }

    /**
     * ```
     * ```
     *
     * `int32 singleunread_on = 5;`
     */
    public var singleunreadOn: kotlin.Int
      @JvmName("getSingleunreadOn")
      get() = _builder.getSingleunreadOn()
      @JvmName("setSingleunreadOn")
      set(value) {
        _builder.setSingleunreadOn(value)
      }
    /**
     * ```
     * ```
     *
     * `int32 singleunread_on = 5;`
     */
    public fun clearSingleunreadOn() {
      _builder.clearSingleunreadOn()
    }

    /**
     * ```
     * ```
     *
     * `int32 msgfeed_on = 6;`
     */
    public var msgfeedOn: kotlin.Int
      @JvmName("getMsgfeedOn")
      get() = _builder.getMsgfeedOn()
      @JvmName("setMsgfeedOn")
      set(value) {
        _builder.setMsgfeedOn(value)
      }
    /**
     * ```
     * ```
     *
     * `int32 msgfeed_on = 6;`
     */
    public fun clearMsgfeedOn() {
      _builder.clearMsgfeedOn()
    }

    /**
     * ```
     * ```
     *
     * `int32 sysup_on = 7;`
     */
    public var sysupOn: kotlin.Int
      @JvmName("getSysupOn")
      get() = _builder.getSysupOn()
      @JvmName("setSysupOn")
      set(value) {
        _builder.setSysupOn(value)
      }
    /**
     * ```
     * ```
     *
     * `int32 sysup_on = 7;`
     */
    public fun clearSysupOn() {
      _builder.clearSysupOn()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun bilibili.im.interface1.v1.ReqTotalUnread.copy(block: `bilibili.im.interface1.v1`.ReqTotalUnreadKt.Dsl.() -> kotlin.Unit): bilibili.im.interface1.v1.ReqTotalUnread =
  `bilibili.im.interface1.v1`.ReqTotalUnreadKt.Dsl._create(this.toBuilder()).apply { block() }._build()

