// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: bilibili/pgc/gateway/player/v2/playurl.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package bilibili.pgc.gateway.player.v2;

@kotlin.jvm.JvmName("-initializecouponToast")
public inline fun couponToast(block: bilibili.pgc.gateway.player.v2.CouponToastKt.Dsl.() -> kotlin.Unit): bilibili.pgc.gateway.player.v2.CouponToast =
  bilibili.pgc.gateway.player.v2.CouponToastKt.Dsl._create(bilibili.pgc.gateway.player.v2.CouponToast.newBuilder()).apply { block() }._build()
/**
 * ```
 * 优惠券提示框信息
 * ```
 *
 * Protobuf type `bilibili.pgc.gateway.player.v2.CouponToast`
 */
public object CouponToastKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: bilibili.pgc.gateway.player.v2.CouponToast.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: bilibili.pgc.gateway.player.v2.CouponToast.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): bilibili.pgc.gateway.player.v2.CouponToast = _builder.build()

    /**
     * ```
     * 提示框文案信息
     * ```
     *
     * `.bilibili.pgc.gateway.player.v2.CouponTextInfo text_info = 1;`
     */
    public var textInfo: bilibili.pgc.gateway.player.v2.CouponTextInfo
      @JvmName("getTextInfo")
      get() = _builder.getTextInfo()
      @JvmName("setTextInfo")
      set(value) {
        _builder.setTextInfo(value)
      }
    /**
     * ```
     * 提示框文案信息
     * ```
     *
     * `.bilibili.pgc.gateway.player.v2.CouponTextInfo text_info = 1;`
     */
    public fun clearTextInfo() {
      _builder.clearTextInfo()
    }
    /**
     * ```
     * 提示框文案信息
     * ```
     *
     * `.bilibili.pgc.gateway.player.v2.CouponTextInfo text_info = 1;`
     * @return Whether the textInfo field is set.
     */
    public fun hasTextInfo(): kotlin.Boolean {
      return _builder.hasTextInfo()
    }
    public val CouponToastKt.Dsl.textInfoOrNull: bilibili.pgc.gateway.player.v2.CouponTextInfo?
      get() = _builder.textInfoOrNull

    /**
     * ```
     * 提示框按钮
     * ```
     *
     * `.bilibili.pgc.gateway.player.v2.ButtonInfo button = 2;`
     */
    public var button: bilibili.pgc.gateway.player.v2.ButtonInfo
      @JvmName("getButton")
      get() = _builder.getButton()
      @JvmName("setButton")
      set(value) {
        _builder.setButton(value)
      }
    /**
     * ```
     * 提示框按钮
     * ```
     *
     * `.bilibili.pgc.gateway.player.v2.ButtonInfo button = 2;`
     */
    public fun clearButton() {
      _builder.clearButton()
    }
    /**
     * ```
     * 提示框按钮
     * ```
     *
     * `.bilibili.pgc.gateway.player.v2.ButtonInfo button = 2;`
     * @return Whether the button field is set.
     */
    public fun hasButton(): kotlin.Boolean {
      return _builder.hasButton()
    }
    public val CouponToastKt.Dsl.buttonOrNull: bilibili.pgc.gateway.player.v2.ButtonInfo?
      get() = _builder.buttonOrNull
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun bilibili.pgc.gateway.player.v2.CouponToast.copy(block: `bilibili.pgc.gateway.player.v2`.CouponToastKt.Dsl.() -> kotlin.Unit): bilibili.pgc.gateway.player.v2.CouponToast =
  `bilibili.pgc.gateway.player.v2`.CouponToastKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val bilibili.pgc.gateway.player.v2.CouponToastOrBuilder.textInfoOrNull: bilibili.pgc.gateway.player.v2.CouponTextInfo?
  get() = if (hasTextInfo()) getTextInfo() else null

public val bilibili.pgc.gateway.player.v2.CouponToastOrBuilder.buttonOrNull: bilibili.pgc.gateway.player.v2.ButtonInfo?
  get() = if (hasButton()) getButton() else null

