// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: bilibili/pgc/gateway/player/v2/playurl.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package bilibili.pgc.gateway.player.v2;

@kotlin.jvm.JvmName("-initializeplayViewReply")
public inline fun playViewReply(block: bilibili.pgc.gateway.player.v2.PlayViewReplyKt.Dsl.() -> kotlin.Unit): bilibili.pgc.gateway.player.v2.PlayViewReply =
  bilibili.pgc.gateway.player.v2.PlayViewReplyKt.Dsl._create(bilibili.pgc.gateway.player.v2.PlayViewReply.newBuilder()).apply { block() }._build()
/**
 * ```
 * 播放页信息-响应
 * ```
 *
 * Protobuf type `bilibili.pgc.gateway.player.v2.PlayViewReply`
 */
public object PlayViewReplyKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: bilibili.pgc.gateway.player.v2.PlayViewReply.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: bilibili.pgc.gateway.player.v2.PlayViewReply.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): bilibili.pgc.gateway.player.v2.PlayViewReply = _builder.build()

    /**
     * ```
     * 视频流信息
     * ```
     *
     * `.bilibili.pgc.gateway.player.v2.VideoInfo video_info = 1;`
     */
    public var videoInfo: bilibili.pgc.gateway.player.v2.VideoInfo
      @JvmName("getVideoInfo")
      get() = _builder.getVideoInfo()
      @JvmName("setVideoInfo")
      set(value) {
        _builder.setVideoInfo(value)
      }
    /**
     * ```
     * 视频流信息
     * ```
     *
     * `.bilibili.pgc.gateway.player.v2.VideoInfo video_info = 1;`
     */
    public fun clearVideoInfo() {
      _builder.clearVideoInfo()
    }
    /**
     * ```
     * 视频流信息
     * ```
     *
     * `.bilibili.pgc.gateway.player.v2.VideoInfo video_info = 1;`
     * @return Whether the videoInfo field is set.
     */
    public fun hasVideoInfo(): kotlin.Boolean {
      return _builder.hasVideoInfo()
    }
    public val PlayViewReplyKt.Dsl.videoInfoOrNull: bilibili.pgc.gateway.player.v2.VideoInfo?
      get() = _builder.videoInfoOrNull

    /**
     * ```
     * 播放控件用户自定义配置
     * ```
     *
     * `.bilibili.pgc.gateway.player.v2.PlayAbilityConf play_conf = 2;`
     */
    public var playConf: bilibili.pgc.gateway.player.v2.PlayAbilityConf
      @JvmName("getPlayConf")
      get() = _builder.getPlayConf()
      @JvmName("setPlayConf")
      set(value) {
        _builder.setPlayConf(value)
      }
    /**
     * ```
     * 播放控件用户自定义配置
     * ```
     *
     * `.bilibili.pgc.gateway.player.v2.PlayAbilityConf play_conf = 2;`
     */
    public fun clearPlayConf() {
      _builder.clearPlayConf()
    }
    /**
     * ```
     * 播放控件用户自定义配置
     * ```
     *
     * `.bilibili.pgc.gateway.player.v2.PlayAbilityConf play_conf = 2;`
     * @return Whether the playConf field is set.
     */
    public fun hasPlayConf(): kotlin.Boolean {
      return _builder.hasPlayConf()
    }
    public val PlayViewReplyKt.Dsl.playConfOrNull: bilibili.pgc.gateway.player.v2.PlayAbilityConf?
      get() = _builder.playConfOrNull

    /**
     * ```
     * 业务需要的其他信息
     * ```
     *
     * `.bilibili.pgc.gateway.player.v2.PlayViewBusinessInfo business = 3;`
     */
    public var business: bilibili.pgc.gateway.player.v2.PlayViewBusinessInfo
      @JvmName("getBusiness")
      get() = _builder.getBusiness()
      @JvmName("setBusiness")
      set(value) {
        _builder.setBusiness(value)
      }
    /**
     * ```
     * 业务需要的其他信息
     * ```
     *
     * `.bilibili.pgc.gateway.player.v2.PlayViewBusinessInfo business = 3;`
     */
    public fun clearBusiness() {
      _builder.clearBusiness()
    }
    /**
     * ```
     * 业务需要的其他信息
     * ```
     *
     * `.bilibili.pgc.gateway.player.v2.PlayViewBusinessInfo business = 3;`
     * @return Whether the business field is set.
     */
    public fun hasBusiness(): kotlin.Boolean {
      return _builder.hasBusiness()
    }
    public val PlayViewReplyKt.Dsl.businessOrNull: bilibili.pgc.gateway.player.v2.PlayViewBusinessInfo?
      get() = _builder.businessOrNull

    /**
     * ```
     * 事件
     * ```
     *
     * `.bilibili.pgc.gateway.player.v2.Event event = 4;`
     */
    public var event: bilibili.pgc.gateway.player.v2.Event
      @JvmName("getEvent")
      get() = _builder.getEvent()
      @JvmName("setEvent")
      set(value) {
        _builder.setEvent(value)
      }
    /**
     * ```
     * 事件
     * ```
     *
     * `.bilibili.pgc.gateway.player.v2.Event event = 4;`
     */
    public fun clearEvent() {
      _builder.clearEvent()
    }
    /**
     * ```
     * 事件
     * ```
     *
     * `.bilibili.pgc.gateway.player.v2.Event event = 4;`
     * @return Whether the event field is set.
     */
    public fun hasEvent(): kotlin.Boolean {
      return _builder.hasEvent()
    }
    public val PlayViewReplyKt.Dsl.eventOrNull: bilibili.pgc.gateway.player.v2.Event?
      get() = _builder.eventOrNull

    /**
     * ```
     * 展示信息
     * ```
     *
     * `.bilibili.pgc.gateway.player.v2.ViewInfo view_info = 5;`
     */
    public var viewInfo: bilibili.pgc.gateway.player.v2.ViewInfo
      @JvmName("getViewInfo")
      get() = _builder.getViewInfo()
      @JvmName("setViewInfo")
      set(value) {
        _builder.setViewInfo(value)
      }
    /**
     * ```
     * 展示信息
     * ```
     *
     * `.bilibili.pgc.gateway.player.v2.ViewInfo view_info = 5;`
     */
    public fun clearViewInfo() {
      _builder.clearViewInfo()
    }
    /**
     * ```
     * 展示信息
     * ```
     *
     * `.bilibili.pgc.gateway.player.v2.ViewInfo view_info = 5;`
     * @return Whether the viewInfo field is set.
     */
    public fun hasViewInfo(): kotlin.Boolean {
      return _builder.hasViewInfo()
    }
    public val PlayViewReplyKt.Dsl.viewInfoOrNull: bilibili.pgc.gateway.player.v2.ViewInfo?
      get() = _builder.viewInfoOrNull

    /**
     * ```
     * 自定义配置扩展信息
     * ```
     *
     * `.bilibili.pgc.gateway.player.v2.PlayAbilityExtConf play_ext_conf = 6;`
     */
    public var playExtConf: bilibili.pgc.gateway.player.v2.PlayAbilityExtConf
      @JvmName("getPlayExtConf")
      get() = _builder.getPlayExtConf()
      @JvmName("setPlayExtConf")
      set(value) {
        _builder.setPlayExtConf(value)
      }
    /**
     * ```
     * 自定义配置扩展信息
     * ```
     *
     * `.bilibili.pgc.gateway.player.v2.PlayAbilityExtConf play_ext_conf = 6;`
     */
    public fun clearPlayExtConf() {
      _builder.clearPlayExtConf()
    }
    /**
     * ```
     * 自定义配置扩展信息
     * ```
     *
     * `.bilibili.pgc.gateway.player.v2.PlayAbilityExtConf play_ext_conf = 6;`
     * @return Whether the playExtConf field is set.
     */
    public fun hasPlayExtConf(): kotlin.Boolean {
      return _builder.hasPlayExtConf()
    }
    public val PlayViewReplyKt.Dsl.playExtConfOrNull: bilibili.pgc.gateway.player.v2.PlayAbilityExtConf?
      get() = _builder.playExtConfOrNull

    /**
     * ```
     * 播放扩展信息
     * ```
     *
     * `.bilibili.pgc.gateway.player.v2.PlayExtInfo play_ext_info = 7;`
     */
    public var playExtInfo: bilibili.pgc.gateway.player.v2.PlayExtInfo
      @JvmName("getPlayExtInfo")
      get() = _builder.getPlayExtInfo()
      @JvmName("setPlayExtInfo")
      set(value) {
        _builder.setPlayExtInfo(value)
      }
    /**
     * ```
     * 播放扩展信息
     * ```
     *
     * `.bilibili.pgc.gateway.player.v2.PlayExtInfo play_ext_info = 7;`
     */
    public fun clearPlayExtInfo() {
      _builder.clearPlayExtInfo()
    }
    /**
     * ```
     * 播放扩展信息
     * ```
     *
     * `.bilibili.pgc.gateway.player.v2.PlayExtInfo play_ext_info = 7;`
     * @return Whether the playExtInfo field is set.
     */
    public fun hasPlayExtInfo(): kotlin.Boolean {
      return _builder.hasPlayExtInfo()
    }
    public val PlayViewReplyKt.Dsl.playExtInfoOrNull: bilibili.pgc.gateway.player.v2.PlayExtInfo?
      get() = _builder.playExtInfoOrNull
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun bilibili.pgc.gateway.player.v2.PlayViewReply.copy(block: `bilibili.pgc.gateway.player.v2`.PlayViewReplyKt.Dsl.() -> kotlin.Unit): bilibili.pgc.gateway.player.v2.PlayViewReply =
  `bilibili.pgc.gateway.player.v2`.PlayViewReplyKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val bilibili.pgc.gateway.player.v2.PlayViewReplyOrBuilder.videoInfoOrNull: bilibili.pgc.gateway.player.v2.VideoInfo?
  get() = if (hasVideoInfo()) getVideoInfo() else null

public val bilibili.pgc.gateway.player.v2.PlayViewReplyOrBuilder.playConfOrNull: bilibili.pgc.gateway.player.v2.PlayAbilityConf?
  get() = if (hasPlayConf()) getPlayConf() else null

public val bilibili.pgc.gateway.player.v2.PlayViewReplyOrBuilder.businessOrNull: bilibili.pgc.gateway.player.v2.PlayViewBusinessInfo?
  get() = if (hasBusiness()) getBusiness() else null

public val bilibili.pgc.gateway.player.v2.PlayViewReplyOrBuilder.eventOrNull: bilibili.pgc.gateway.player.v2.Event?
  get() = if (hasEvent()) getEvent() else null

public val bilibili.pgc.gateway.player.v2.PlayViewReplyOrBuilder.viewInfoOrNull: bilibili.pgc.gateway.player.v2.ViewInfo?
  get() = if (hasViewInfo()) getViewInfo() else null

public val bilibili.pgc.gateway.player.v2.PlayViewReplyOrBuilder.playExtConfOrNull: bilibili.pgc.gateway.player.v2.PlayAbilityExtConf?
  get() = if (hasPlayExtConf()) getPlayExtConf() else null

public val bilibili.pgc.gateway.player.v2.PlayViewReplyOrBuilder.playExtInfoOrNull: bilibili.pgc.gateway.player.v2.PlayExtInfo?
  get() = if (hasPlayExtInfo()) getPlayExtInfo() else null

