// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: bilibili/pgc/gateway/player/v2/playurl.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package bilibili.pgc.gateway.player.v2;

@kotlin.jvm.JvmName("-initializeroleAudioProto")
public inline fun roleAudioProto(block: bilibili.pgc.gateway.player.v2.RoleAudioProtoKt.Dsl.() -> kotlin.Unit): bilibili.pgc.gateway.player.v2.RoleAudioProto =
  bilibili.pgc.gateway.player.v2.RoleAudioProtoKt.Dsl._create(bilibili.pgc.gateway.player.v2.RoleAudioProto.newBuilder()).apply { block() }._build()
/**
 * ```
 * 角色配音信息
 * ```
 *
 * Protobuf type `bilibili.pgc.gateway.player.v2.RoleAudioProto`
 */
public object RoleAudioProtoKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: bilibili.pgc.gateway.player.v2.RoleAudioProto.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: bilibili.pgc.gateway.player.v2.RoleAudioProto.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): bilibili.pgc.gateway.player.v2.RoleAudioProto = _builder.build()

    /**
     * ```
     * 角色ID
     * ```
     *
     * `int64 role_id = 1;`
     */
    public var roleId: kotlin.Long
      @JvmName("getRoleId")
      get() = _builder.getRoleId()
      @JvmName("setRoleId")
      set(value) {
        _builder.setRoleId(value)
      }
    /**
     * ```
     * 角色ID
     * ```
     *
     * `int64 role_id = 1;`
     */
    public fun clearRoleId() {
      _builder.clearRoleId()
    }

    /**
     * ```
     * 角色名称
     * ```
     *
     * `string role_name = 2;`
     */
    public var roleName: kotlin.String
      @JvmName("getRoleName")
      get() = _builder.getRoleName()
      @JvmName("setRoleName")
      set(value) {
        _builder.setRoleName(value)
      }
    /**
     * ```
     * 角色名称
     * ```
     *
     * `string role_name = 2;`
     */
    public fun clearRoleName() {
      _builder.clearRoleName()
    }

    /**
     * ```
     * 角色头像
     * ```
     *
     * `string role_avatar = 3;`
     */
    public var roleAvatar: kotlin.String
      @JvmName("getRoleAvatar")
      get() = _builder.getRoleAvatar()
      @JvmName("setRoleAvatar")
      set(value) {
        _builder.setRoleAvatar(value)
      }
    /**
     * ```
     * 角色头像
     * ```
     *
     * `string role_avatar = 3;`
     */
    public fun clearRoleAvatar() {
      _builder.clearRoleAvatar()
    }

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class AudioMaterialListProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * ```
     * 音频素材列表
     * ```
     *
     * `repeated .bilibili.pgc.gateway.player.v2.AudioMaterialProto audio_material_list = 4;`
     */
     public val audioMaterialList: com.google.protobuf.kotlin.DslList<bilibili.pgc.gateway.player.v2.AudioMaterialProto, AudioMaterialListProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.getAudioMaterialListList()
      )
    /**
     * ```
     * 音频素材列表
     * ```
     *
     * `repeated .bilibili.pgc.gateway.player.v2.AudioMaterialProto audio_material_list = 4;`
     * @param value The audioMaterialList to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAudioMaterialList")
    public fun com.google.protobuf.kotlin.DslList<bilibili.pgc.gateway.player.v2.AudioMaterialProto, AudioMaterialListProxy>.add(value: bilibili.pgc.gateway.player.v2.AudioMaterialProto) {
      _builder.addAudioMaterialList(value)
    }
    /**
     * ```
     * 音频素材列表
     * ```
     *
     * `repeated .bilibili.pgc.gateway.player.v2.AudioMaterialProto audio_material_list = 4;`
     * @param value The audioMaterialList to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAudioMaterialList")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<bilibili.pgc.gateway.player.v2.AudioMaterialProto, AudioMaterialListProxy>.plusAssign(value: bilibili.pgc.gateway.player.v2.AudioMaterialProto) {
      add(value)
    }
    /**
     * ```
     * 音频素材列表
     * ```
     *
     * `repeated .bilibili.pgc.gateway.player.v2.AudioMaterialProto audio_material_list = 4;`
     * @param values The audioMaterialList to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllAudioMaterialList")
    public fun com.google.protobuf.kotlin.DslList<bilibili.pgc.gateway.player.v2.AudioMaterialProto, AudioMaterialListProxy>.addAll(values: kotlin.collections.Iterable<bilibili.pgc.gateway.player.v2.AudioMaterialProto>) {
      _builder.addAllAudioMaterialList(values)
    }
    /**
     * ```
     * 音频素材列表
     * ```
     *
     * `repeated .bilibili.pgc.gateway.player.v2.AudioMaterialProto audio_material_list = 4;`
     * @param values The audioMaterialList to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllAudioMaterialList")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<bilibili.pgc.gateway.player.v2.AudioMaterialProto, AudioMaterialListProxy>.plusAssign(values: kotlin.collections.Iterable<bilibili.pgc.gateway.player.v2.AudioMaterialProto>) {
      addAll(values)
    }
    /**
     * ```
     * 音频素材列表
     * ```
     *
     * `repeated .bilibili.pgc.gateway.player.v2.AudioMaterialProto audio_material_list = 4;`
     * @param index The index to set the value at.
     * @param value The audioMaterialList to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setAudioMaterialList")
    public operator fun com.google.protobuf.kotlin.DslList<bilibili.pgc.gateway.player.v2.AudioMaterialProto, AudioMaterialListProxy>.set(index: kotlin.Int, value: bilibili.pgc.gateway.player.v2.AudioMaterialProto) {
      _builder.setAudioMaterialList(index, value)
    }
    /**
     * ```
     * 音频素材列表
     * ```
     *
     * `repeated .bilibili.pgc.gateway.player.v2.AudioMaterialProto audio_material_list = 4;`
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearAudioMaterialList")
    public fun com.google.protobuf.kotlin.DslList<bilibili.pgc.gateway.player.v2.AudioMaterialProto, AudioMaterialListProxy>.clear() {
      _builder.clearAudioMaterialList()
    }

  }
}
@kotlin.jvm.JvmSynthetic
public inline fun bilibili.pgc.gateway.player.v2.RoleAudioProto.copy(block: `bilibili.pgc.gateway.player.v2`.RoleAudioProtoKt.Dsl.() -> kotlin.Unit): bilibili.pgc.gateway.player.v2.RoleAudioProto =
  `bilibili.pgc.gateway.player.v2`.RoleAudioProtoKt.Dsl._create(this.toBuilder()).apply { block() }._build()

