// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: bilibili/pgc/gateway/player/v2/playurl.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package bilibili.pgc.gateway.player.v2;

@kotlin.jvm.JvmName("-initializetextInfo")
public inline fun textInfo(block: bilibili.pgc.gateway.player.v2.TextInfoKt.Dsl.() -> kotlin.Unit): bilibili.pgc.gateway.player.v2.TextInfo =
  bilibili.pgc.gateway.player.v2.TextInfoKt.Dsl._create(bilibili.pgc.gateway.player.v2.TextInfo.newBuilder()).apply { block() }._build()
/**
 * ```
 * 文案信息
 * ```
 *
 * Protobuf type `bilibili.pgc.gateway.player.v2.TextInfo`
 */
public object TextInfoKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: bilibili.pgc.gateway.player.v2.TextInfo.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: bilibili.pgc.gateway.player.v2.TextInfo.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): bilibili.pgc.gateway.player.v2.TextInfo = _builder.build()

    /**
     * ```
     * 文案
     * ```
     *
     * `string text = 1;`
     */
    public var text: kotlin.String
      @JvmName("getText")
      get() = _builder.getText()
      @JvmName("setText")
      set(value) {
        _builder.setText(value)
      }
    /**
     * ```
     * 文案
     * ```
     *
     * `string text = 1;`
     */
    public fun clearText() {
      _builder.clearText()
    }

    /**
     * ```
     * 字体色值
     * ```
     *
     * `string text_color = 2;`
     */
    public var textColor: kotlin.String
      @JvmName("getTextColor")
      get() = _builder.getTextColor()
      @JvmName("setTextColor")
      set(value) {
        _builder.setTextColor(value)
      }
    /**
     * ```
     * 字体色值
     * ```
     *
     * `string text_color = 2;`
     */
    public fun clearTextColor() {
      _builder.clearTextColor()
    }

    /**
     * ```
     * 字体色值-夜间模式
     * ```
     *
     * `string text_color_night = 3;`
     */
    public var textColorNight: kotlin.String
      @JvmName("getTextColorNight")
      get() = _builder.getTextColorNight()
      @JvmName("setTextColorNight")
      set(value) {
        _builder.setTextColorNight(value)
      }
    /**
     * ```
     * 字体色值-夜间模式
     * ```
     *
     * `string text_color_night = 3;`
     */
    public fun clearTextColorNight() {
      _builder.clearTextColorNight()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun bilibili.pgc.gateway.player.v2.TextInfo.copy(block: `bilibili.pgc.gateway.player.v2`.TextInfoKt.Dsl.() -> kotlin.Unit): bilibili.pgc.gateway.player.v2.TextInfo =
  `bilibili.pgc.gateway.player.v2`.TextInfoKt.Dsl._create(this.toBuilder()).apply { block() }._build()

