// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: bilibili/polymer/app/search/v1/search.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package bilibili.polymer.app.search.v1;

@kotlin.jvm.JvmName("-initializefollowButton")
public inline fun followButton(block: bilibili.polymer.app.search.v1.FollowButtonKt.Dsl.() -> kotlin.Unit): bilibili.polymer.app.search.v1.FollowButton =
  bilibili.polymer.app.search.v1.FollowButtonKt.Dsl._create(bilibili.polymer.app.search.v1.FollowButton.newBuilder()).apply { block() }._build()
/**
 * ```
 * ```
 *
 * Protobuf type `bilibili.polymer.app.search.v1.FollowButton`
 */
public object FollowButtonKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: bilibili.polymer.app.search.v1.FollowButton.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: bilibili.polymer.app.search.v1.FollowButton.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): bilibili.polymer.app.search.v1.FollowButton = _builder.build()

    /**
     * ```
     * ```
     *
     * `string icon = 1;`
     */
    public var icon: kotlin.String
      @JvmName("getIcon")
      get() = _builder.getIcon()
      @JvmName("setIcon")
      set(value) {
        _builder.setIcon(value)
      }
    /**
     * ```
     * ```
     *
     * `string icon = 1;`
     */
    public fun clearIcon() {
      _builder.clearIcon()
    }

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class TextsProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * ```
     * ```
     *
     * `map<string, string> texts = 2;`
     */
     public val texts: com.google.protobuf.kotlin.DslMap<kotlin.String, kotlin.String, TextsProxy>
      @kotlin.jvm.JvmSynthetic
      @JvmName("getTextsMap")
      get() = com.google.protobuf.kotlin.DslMap(
        _builder.getTextsMap()
      )
    /**
     * ```
     * ```
     *
     * `map<string, string> texts = 2;`
     */
    @JvmName("putTexts")
    public fun com.google.protobuf.kotlin.DslMap<kotlin.String, kotlin.String, TextsProxy>
      .put(key: kotlin.String, value: kotlin.String) {
         _builder.putTexts(key, value)
       }
    /**
     * ```
     * ```
     *
     * `map<string, string> texts = 2;`
     */
    @kotlin.jvm.JvmSynthetic
    @JvmName("setTexts")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslMap<kotlin.String, kotlin.String, TextsProxy>
      .set(key: kotlin.String, value: kotlin.String) {
         put(key, value)
       }
    /**
     * ```
     * ```
     *
     * `map<string, string> texts = 2;`
     */
    @kotlin.jvm.JvmSynthetic
    @JvmName("removeTexts")
    public fun com.google.protobuf.kotlin.DslMap<kotlin.String, kotlin.String, TextsProxy>
      .remove(key: kotlin.String) {
         _builder.removeTexts(key)
       }
    /**
     * ```
     * ```
     *
     * `map<string, string> texts = 2;`
     */
    @kotlin.jvm.JvmSynthetic
    @JvmName("putAllTexts")
    public fun com.google.protobuf.kotlin.DslMap<kotlin.String, kotlin.String, TextsProxy>
      .putAll(map: kotlin.collections.Map<kotlin.String, kotlin.String>) {
         _builder.putAllTexts(map)
       }
    /**
     * ```
     * ```
     *
     * `map<string, string> texts = 2;`
     */
    @kotlin.jvm.JvmSynthetic
    @JvmName("clearTexts")
    public fun com.google.protobuf.kotlin.DslMap<kotlin.String, kotlin.String, TextsProxy>
      .clear() {
         _builder.clearTexts()
       }

    /**
     * ```
     * ```
     *
     * `string status_report = 3;`
     */
    public var statusReport: kotlin.String
      @JvmName("getStatusReport")
      get() = _builder.getStatusReport()
      @JvmName("setStatusReport")
      set(value) {
        _builder.setStatusReport(value)
      }
    /**
     * ```
     * ```
     *
     * `string status_report = 3;`
     */
    public fun clearStatusReport() {
      _builder.clearStatusReport()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun bilibili.polymer.app.search.v1.FollowButton.copy(block: `bilibili.polymer.app.search.v1`.FollowButtonKt.Dsl.() -> kotlin.Unit): bilibili.polymer.app.search.v1.FollowButton =
  `bilibili.polymer.app.search.v1`.FollowButtonKt.Dsl._create(this.toBuilder()).apply { block() }._build()

