// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: bilibili/polymer/app/search/v1/search.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package bilibili.polymer.app.search.v1;

@kotlin.jvm.JvmName("-initializercmdReason")
public inline fun rcmdReason(block: bilibili.polymer.app.search.v1.RcmdReasonKt.Dsl.() -> kotlin.Unit): bilibili.polymer.app.search.v1.RcmdReason =
  bilibili.polymer.app.search.v1.RcmdReasonKt.Dsl._create(bilibili.polymer.app.search.v1.RcmdReason.newBuilder()).apply { block() }._build()
/**
 * ```
 * ```
 *
 * Protobuf type `bilibili.polymer.app.search.v1.RcmdReason`
 */
public object RcmdReasonKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: bilibili.polymer.app.search.v1.RcmdReason.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: bilibili.polymer.app.search.v1.RcmdReason.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): bilibili.polymer.app.search.v1.RcmdReason = _builder.build()

    /**
     * ```
     * ```
     *
     * `string content = 1;`
     */
    public var content: kotlin.String
      @JvmName("getContent")
      get() = _builder.getContent()
      @JvmName("setContent")
      set(value) {
        _builder.setContent(value)
      }
    /**
     * ```
     * ```
     *
     * `string content = 1;`
     */
    public fun clearContent() {
      _builder.clearContent()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun bilibili.polymer.app.search.v1.RcmdReason.copy(block: `bilibili.polymer.app.search.v1`.RcmdReasonKt.Dsl.() -> kotlin.Unit): bilibili.polymer.app.search.v1.RcmdReason =
  `bilibili.polymer.app.search.v1`.RcmdReasonKt.Dsl._create(this.toBuilder()).apply { block() }._build()

