// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: bilibili/app/view/v1/view.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package bilibili.app.view.v1;

@kotlin.jvm.JvmName("-initializebizFavSeasonParam")
public inline fun bizFavSeasonParam(block: bilibili.app.view.v1.BizFavSeasonParamKt.Dsl.() -> kotlin.Unit): bilibili.app.view.v1.BizFavSeasonParam =
  bilibili.app.view.v1.BizFavSeasonParamKt.Dsl._create(bilibili.app.view.v1.BizFavSeasonParam.newBuilder()).apply { block() }._build()
/**
 * ```
 * 收藏合集参数
 * ```
 *
 * Protobuf type `bilibili.app.view.v1.BizFavSeasonParam`
 */
public object BizFavSeasonParamKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: bilibili.app.view.v1.BizFavSeasonParam.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: bilibili.app.view.v1.BizFavSeasonParam.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): bilibili.app.view.v1.BizFavSeasonParam = _builder.build()

    /**
     * ```
     * 合集id
     * ```
     *
     * `int64 season_id = 1;`
     */
    public var seasonId: kotlin.Long
      @JvmName("getSeasonId")
      get() = _builder.getSeasonId()
      @JvmName("setSeasonId")
      set(value) {
        _builder.setSeasonId(value)
      }
    /**
     * ```
     * 合集id
     * ```
     *
     * `int64 season_id = 1;`
     */
    public fun clearSeasonId() {
      _builder.clearSeasonId()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun bilibili.app.view.v1.BizFavSeasonParam.copy(block: `bilibili.app.view.v1`.BizFavSeasonParamKt.Dsl.() -> kotlin.Unit): bilibili.app.view.v1.BizFavSeasonParam =
  `bilibili.app.view.v1`.BizFavSeasonParamKt.Dsl._create(this.toBuilder()).apply { block() }._build()

