// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: bilibili/app/view/v1/view.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package bilibili.app.view.v1;

@kotlin.jvm.JvmName("-initializematerialRes")
public inline fun materialRes(block: bilibili.app.view.v1.MaterialResKt.Dsl.() -> kotlin.Unit): bilibili.app.view.v1.MaterialRes =
  bilibili.app.view.v1.MaterialResKt.Dsl._create(bilibili.app.view.v1.MaterialRes.newBuilder()).apply { block() }._build()
/**
 * ```
 * ```
 *
 * Protobuf type `bilibili.app.view.v1.MaterialRes`
 */
public object MaterialResKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: bilibili.app.view.v1.MaterialRes.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: bilibili.app.view.v1.MaterialRes.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): bilibili.app.view.v1.MaterialRes = _builder.build()

    /**
     * ```
     * ```
     *
     * `int64 id = 1;`
     */
    public var id: kotlin.Long
      @JvmName("getId")
      get() = _builder.getId()
      @JvmName("setId")
      set(value) {
        _builder.setId(value)
      }
    /**
     * ```
     * ```
     *
     * `int64 id = 1;`
     */
    public fun clearId() {
      _builder.clearId()
    }

    /**
     * ```
     * ```
     *
     * `string icon = 2;`
     */
    public var icon: kotlin.String
      @JvmName("getIcon")
      get() = _builder.getIcon()
      @JvmName("setIcon")
      set(value) {
        _builder.setIcon(value)
      }
    /**
     * ```
     * ```
     *
     * `string icon = 2;`
     */
    public fun clearIcon() {
      _builder.clearIcon()
    }

    /**
     * ```
     * ```
     *
     * `string url = 3;`
     */
    public var url: kotlin.String
      @JvmName("getUrl")
      get() = _builder.getUrl()
      @JvmName("setUrl")
      set(value) {
        _builder.setUrl(value)
      }
    /**
     * ```
     * ```
     *
     * `string url = 3;`
     */
    public fun clearUrl() {
      _builder.clearUrl()
    }

    /**
     * ```
     * ```
     *
     * `.bilibili.app.view.v1.MaterialSource type = 4;`
     */
    public var type: bilibili.app.view.v1.MaterialSource
      @JvmName("getType")
      get() = _builder.getType()
      @JvmName("setType")
      set(value) {
        _builder.setType(value)
      }
    public var typeValue: kotlin.Int
      @JvmName("getTypeValue")
      get() = _builder.getTypeValue()
      @JvmName("setTypeValue")
      set(value) {
        _builder.setTypeValue(value)
      }
    /**
     * ```
     * ```
     *
     * `.bilibili.app.view.v1.MaterialSource type = 4;`
     */
    public fun clearType() {
      _builder.clearType()
    }

    /**
     * ```
     * ```
     *
     * `string name = 5;`
     */
    public var name: kotlin.String
      @JvmName("getName")
      get() = _builder.getName()
      @JvmName("setName")
      set(value) {
        _builder.setName(value)
      }
    /**
     * ```
     * ```
     *
     * `string name = 5;`
     */
    public fun clearName() {
      _builder.clearName()
    }

    /**
     * ```
     * ```
     *
     * `string bg_color = 6;`
     */
    public var bgColor: kotlin.String
      @JvmName("getBgColor")
      get() = _builder.getBgColor()
      @JvmName("setBgColor")
      set(value) {
        _builder.setBgColor(value)
      }
    /**
     * ```
     * ```
     *
     * `string bg_color = 6;`
     */
    public fun clearBgColor() {
      _builder.clearBgColor()
    }

    /**
     * ```
     * ```
     *
     * `string bg_pic = 7;`
     */
    public var bgPic: kotlin.String
      @JvmName("getBgPic")
      get() = _builder.getBgPic()
      @JvmName("setBgPic")
      set(value) {
        _builder.setBgPic(value)
      }
    /**
     * ```
     * ```
     *
     * `string bg_pic = 7;`
     */
    public fun clearBgPic() {
      _builder.clearBgPic()
    }

    /**
     * ```
     * ```
     *
     * `int32 jump_type = 8;`
     */
    public var jumpType: kotlin.Int
      @JvmName("getJumpType")
      get() = _builder.getJumpType()
      @JvmName("setJumpType")
      set(value) {
        _builder.setJumpType(value)
      }
    /**
     * ```
     * ```
     *
     * `int32 jump_type = 8;`
     */
    public fun clearJumpType() {
      _builder.clearJumpType()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun bilibili.app.view.v1.MaterialRes.copy(block: `bilibili.app.view.v1`.MaterialResKt.Dsl.() -> kotlin.Unit): bilibili.app.view.v1.MaterialRes =
  `bilibili.app.view.v1`.MaterialResKt.Dsl._create(this.toBuilder()).apply { block() }._build()

