// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: bilibili/app/view/v1/view.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package bilibili.app.view.v1;

@kotlin.jvm.JvmName("-initializeoperationRelate")
public inline fun operationRelate(block: bilibili.app.view.v1.OperationRelateKt.Dsl.() -> kotlin.Unit): bilibili.app.view.v1.OperationRelate =
  bilibili.app.view.v1.OperationRelateKt.Dsl._create(bilibili.app.view.v1.OperationRelate.newBuilder()).apply { block() }._build()
/**
 * ```
 * 相关推荐(运营配置+AI推荐)
 * ```
 *
 * Protobuf type `bilibili.app.view.v1.OperationRelate`
 */
public object OperationRelateKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: bilibili.app.view.v1.OperationRelate.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: bilibili.app.view.v1.OperationRelate.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): bilibili.app.view.v1.OperationRelate = _builder.build()

    /**
     * ```
     * 模块标题
     * ```
     *
     * `string title = 1;`
     */
    public var title: kotlin.String
      @JvmName("getTitle")
      get() = _builder.getTitle()
      @JvmName("setTitle")
      set(value) {
        _builder.setTitle(value)
      }
    /**
     * ```
     * 模块标题
     * ```
     *
     * `string title = 1;`
     */
    public fun clearTitle() {
      _builder.clearTitle()
    }

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class RelateItemProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * ```
     * 相关推荐模块内容
     * ```
     *
     * `repeated .bilibili.app.view.v1.RelateItem relate_item = 2;`
     */
     public val relateItem: com.google.protobuf.kotlin.DslList<bilibili.app.view.v1.RelateItem, RelateItemProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.getRelateItemList()
      )
    /**
     * ```
     * 相关推荐模块内容
     * ```
     *
     * `repeated .bilibili.app.view.v1.RelateItem relate_item = 2;`
     * @param value The relateItem to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addRelateItem")
    public fun com.google.protobuf.kotlin.DslList<bilibili.app.view.v1.RelateItem, RelateItemProxy>.add(value: bilibili.app.view.v1.RelateItem) {
      _builder.addRelateItem(value)
    }
    /**
     * ```
     * 相关推荐模块内容
     * ```
     *
     * `repeated .bilibili.app.view.v1.RelateItem relate_item = 2;`
     * @param value The relateItem to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignRelateItem")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<bilibili.app.view.v1.RelateItem, RelateItemProxy>.plusAssign(value: bilibili.app.view.v1.RelateItem) {
      add(value)
    }
    /**
     * ```
     * 相关推荐模块内容
     * ```
     *
     * `repeated .bilibili.app.view.v1.RelateItem relate_item = 2;`
     * @param values The relateItem to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllRelateItem")
    public fun com.google.protobuf.kotlin.DslList<bilibili.app.view.v1.RelateItem, RelateItemProxy>.addAll(values: kotlin.collections.Iterable<bilibili.app.view.v1.RelateItem>) {
      _builder.addAllRelateItem(values)
    }
    /**
     * ```
     * 相关推荐模块内容
     * ```
     *
     * `repeated .bilibili.app.view.v1.RelateItem relate_item = 2;`
     * @param values The relateItem to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllRelateItem")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<bilibili.app.view.v1.RelateItem, RelateItemProxy>.plusAssign(values: kotlin.collections.Iterable<bilibili.app.view.v1.RelateItem>) {
      addAll(values)
    }
    /**
     * ```
     * 相关推荐模块内容
     * ```
     *
     * `repeated .bilibili.app.view.v1.RelateItem relate_item = 2;`
     * @param index The index to set the value at.
     * @param value The relateItem to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setRelateItem")
    public operator fun com.google.protobuf.kotlin.DslList<bilibili.app.view.v1.RelateItem, RelateItemProxy>.set(index: kotlin.Int, value: bilibili.app.view.v1.RelateItem) {
      _builder.setRelateItem(index, value)
    }
    /**
     * ```
     * 相关推荐模块内容
     * ```
     *
     * `repeated .bilibili.app.view.v1.RelateItem relate_item = 2;`
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearRelateItem")
    public fun com.google.protobuf.kotlin.DslList<bilibili.app.view.v1.RelateItem, RelateItemProxy>.clear() {
      _builder.clearRelateItem()
    }


    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class AiRelateItemProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * ```
     * AI相关推荐
     * ```
     *
     * `repeated .bilibili.app.view.v1.Relate ai_relate_item = 3;`
     */
     public val aiRelateItem: com.google.protobuf.kotlin.DslList<bilibili.app.view.v1.Relate, AiRelateItemProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.getAiRelateItemList()
      )
    /**
     * ```
     * AI相关推荐
     * ```
     *
     * `repeated .bilibili.app.view.v1.Relate ai_relate_item = 3;`
     * @param value The aiRelateItem to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAiRelateItem")
    public fun com.google.protobuf.kotlin.DslList<bilibili.app.view.v1.Relate, AiRelateItemProxy>.add(value: bilibili.app.view.v1.Relate) {
      _builder.addAiRelateItem(value)
    }
    /**
     * ```
     * AI相关推荐
     * ```
     *
     * `repeated .bilibili.app.view.v1.Relate ai_relate_item = 3;`
     * @param value The aiRelateItem to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAiRelateItem")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<bilibili.app.view.v1.Relate, AiRelateItemProxy>.plusAssign(value: bilibili.app.view.v1.Relate) {
      add(value)
    }
    /**
     * ```
     * AI相关推荐
     * ```
     *
     * `repeated .bilibili.app.view.v1.Relate ai_relate_item = 3;`
     * @param values The aiRelateItem to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllAiRelateItem")
    public fun com.google.protobuf.kotlin.DslList<bilibili.app.view.v1.Relate, AiRelateItemProxy>.addAll(values: kotlin.collections.Iterable<bilibili.app.view.v1.Relate>) {
      _builder.addAllAiRelateItem(values)
    }
    /**
     * ```
     * AI相关推荐
     * ```
     *
     * `repeated .bilibili.app.view.v1.Relate ai_relate_item = 3;`
     * @param values The aiRelateItem to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllAiRelateItem")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<bilibili.app.view.v1.Relate, AiRelateItemProxy>.plusAssign(values: kotlin.collections.Iterable<bilibili.app.view.v1.Relate>) {
      addAll(values)
    }
    /**
     * ```
     * AI相关推荐
     * ```
     *
     * `repeated .bilibili.app.view.v1.Relate ai_relate_item = 3;`
     * @param index The index to set the value at.
     * @param value The aiRelateItem to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setAiRelateItem")
    public operator fun com.google.protobuf.kotlin.DslList<bilibili.app.view.v1.Relate, AiRelateItemProxy>.set(index: kotlin.Int, value: bilibili.app.view.v1.Relate) {
      _builder.setAiRelateItem(index, value)
    }
    /**
     * ```
     * AI相关推荐
     * ```
     *
     * `repeated .bilibili.app.view.v1.Relate ai_relate_item = 3;`
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearAiRelateItem")
    public fun com.google.protobuf.kotlin.DslList<bilibili.app.view.v1.Relate, AiRelateItemProxy>.clear() {
      _builder.clearAiRelateItem()
    }

  }
}
@kotlin.jvm.JvmSynthetic
public inline fun bilibili.app.view.v1.OperationRelate.copy(block: `bilibili.app.view.v1`.OperationRelateKt.Dsl.() -> kotlin.Unit): bilibili.app.view.v1.OperationRelate =
  `bilibili.app.view.v1`.OperationRelateKt.Dsl._create(this.toBuilder()).apply { block() }._build()

