// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: bilibili/app/view/v1/view.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package bilibili.app.view.v1;

@kotlin.jvm.JvmName("-initializereserveReq")
public inline fun reserveReq(block: bilibili.app.view.v1.ReserveReqKt.Dsl.() -> kotlin.Unit): bilibili.app.view.v1.ReserveReq =
  bilibili.app.view.v1.ReserveReqKt.Dsl._create(bilibili.app.view.v1.ReserveReq.newBuilder()).apply { block() }._build()
/**
 * ```
 * ```
 *
 * Protobuf type `bilibili.app.view.v1.ReserveReq`
 */
public object ReserveReqKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: bilibili.app.view.v1.ReserveReq.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: bilibili.app.view.v1.ReserveReq.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): bilibili.app.view.v1.ReserveReq = _builder.build()

    /**
     * ```
     * ```
     *
     * `int64 reserve_id = 1;`
     */
    public var reserveId: kotlin.Long
      @JvmName("getReserveId")
      get() = _builder.getReserveId()
      @JvmName("setReserveId")
      set(value) {
        _builder.setReserveId(value)
      }
    /**
     * ```
     * ```
     *
     * `int64 reserve_id = 1;`
     */
    public fun clearReserveId() {
      _builder.clearReserveId()
    }

    /**
     * ```
     * ```
     *
     * `int64 reserve_action = 2;`
     */
    public var reserveAction: kotlin.Long
      @JvmName("getReserveAction")
      get() = _builder.getReserveAction()
      @JvmName("setReserveAction")
      set(value) {
        _builder.setReserveAction(value)
      }
    /**
     * ```
     * ```
     *
     * `int64 reserve_action = 2;`
     */
    public fun clearReserveAction() {
      _builder.clearReserveAction()
    }

    /**
     * ```
     * ```
     *
     * `int64 up_id = 3;`
     */
    public var upId: kotlin.Long
      @JvmName("getUpId")
      get() = _builder.getUpId()
      @JvmName("setUpId")
      set(value) {
        _builder.setUpId(value)
      }
    /**
     * ```
     * ```
     *
     * `int64 up_id = 3;`
     */
    public fun clearUpId() {
      _builder.clearUpId()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun bilibili.app.view.v1.ReserveReq.copy(block: `bilibili.app.view.v1`.ReserveReqKt.Dsl.() -> kotlin.Unit): bilibili.app.view.v1.ReserveReq =
  `bilibili.app.view.v1`.ReserveReqKt.Dsl._create(this.toBuilder()).apply { block() }._build()

