// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bilibili/broadcast/message/ogv/live.proto

// Protobuf Java Version: 4.26.1
package bilibili.broadcast.message.ogv;

public interface LiveEndEventOrBuilder extends
    // @@protoc_insertion_point(interface_extends:bilibili.broadcast.message.ogv.LiveEndEvent)
    com.google.protobuf.MessageOrBuilder {
}
