// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: bilibili/pgc/gateway/player/v1/playurl.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package bilibili.pgc.gateway.player.v1;

@kotlin.jvm.JvmName("-initializeroomShowInfo")
public inline fun roomShowInfo(block: bilibili.pgc.gateway.player.v1.RoomShowInfoKt.Dsl.() -> kotlin.Unit): bilibili.pgc.gateway.player.v1.RoomShowInfo =
  bilibili.pgc.gateway.player.v1.RoomShowInfoKt.Dsl._create(bilibili.pgc.gateway.player.v1.RoomShowInfo.newBuilder()).apply { block() }._build()
/**
 * ```
 * 房间信息-展示相关
 * ```
 *
 * Protobuf type `bilibili.pgc.gateway.player.v1.RoomShowInfo`
 */
public object RoomShowInfoKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: bilibili.pgc.gateway.player.v1.RoomShowInfo.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: bilibili.pgc.gateway.player.v1.RoomShowInfo.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): bilibili.pgc.gateway.player.v1.RoomShowInfo = _builder.build()

    /**
     * ```
     * 短号
     * ```
     *
     * `int64 short_id = 1;`
     */
    public var shortId: kotlin.Long
      @JvmName("getShortId")
      get() = _builder.getShortId()
      @JvmName("setShortId")
      set(value) {
        _builder.setShortId(value)
      }
    /**
     * ```
     * 短号
     * ```
     *
     * `int64 short_id = 1;`
     */
    public fun clearShortId() {
      _builder.clearShortId()
    }

    /**
     * ```
     * 人气值
     * ```
     *
     * `int64 popularity_count = 8;`
     */
    public var popularityCount: kotlin.Long
      @JvmName("getPopularityCount")
      get() = _builder.getPopularityCount()
      @JvmName("setPopularityCount")
      set(value) {
        _builder.setPopularityCount(value)
      }
    /**
     * ```
     * 人气值
     * ```
     *
     * `int64 popularity_count = 8;`
     */
    public fun clearPopularityCount() {
      _builder.clearPopularityCount()
    }

    /**
     * ```
     * 最近一次开播时间戳
     * ```
     *
     * `int64 live_start_time = 10;`
     */
    public var liveStartTime: kotlin.Long
      @JvmName("getLiveStartTime")
      get() = _builder.getLiveStartTime()
      @JvmName("setLiveStartTime")
      set(value) {
        _builder.setLiveStartTime(value)
      }
    /**
     * ```
     * 最近一次开播时间戳
     * ```
     *
     * `int64 live_start_time = 10;`
     */
    public fun clearLiveStartTime() {
      _builder.clearLiveStartTime()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun bilibili.pgc.gateway.player.v1.RoomShowInfo.copy(block: `bilibili.pgc.gateway.player.v1`.RoomShowInfoKt.Dsl.() -> kotlin.Unit): bilibili.pgc.gateway.player.v1.RoomShowInfo =
  `bilibili.pgc.gateway.player.v1`.RoomShowInfoKt.Dsl._create(this.toBuilder()).apply { block() }._build()

