// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bilibili/app/viewunite/pgcanymodel.proto

// Protobuf Java Version: 4.26.1
package bilibili.app.viewunite.pgcanymodel;

/**
 * <pre>
 * 权限相关信息
 * </pre>
 *
 * Protobuf type {@code bilibili.app.viewunite.pgcanymodel.Rights}
 */
public final class Rights extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:bilibili.app.viewunite.pgcanymodel.Rights)
    RightsOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 26,
      /* patch= */ 1,
      /* suffix= */ "",
      Rights.class.getName());
  }
  // Use Rights.newBuilder() to construct.
  private Rights(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private Rights() {
    copyright_ = "";
    copyrightName_ = "";
    resource_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return bilibili.app.viewunite.pgcanymodel.Pgcanymodel.internal_static_bilibili_app_viewunite_pgcanymodel_Rights_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return bilibili.app.viewunite.pgcanymodel.Pgcanymodel.internal_static_bilibili_app_viewunite_pgcanymodel_Rights_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            bilibili.app.viewunite.pgcanymodel.Rights.class, bilibili.app.viewunite.pgcanymodel.Rights.Builder.class);
  }

  public static final int ALLOW_DOWNLOAD_FIELD_NUMBER = 1;
  private int allowDownload_ = 0;
  /**
   * <pre>
   * </pre>
   *
   * <code>int32 allow_download = 1;</code>
   * @return The allowDownload.
   */
  @java.lang.Override
  public int getAllowDownload() {
    return allowDownload_;
  }

  public static final int ALLOW_REVIEW_FIELD_NUMBER = 2;
  private int allowReview_ = 0;
  /**
   * <pre>
   * </pre>
   *
   * <code>int32 allow_review = 2;</code>
   * @return The allowReview.
   */
  @java.lang.Override
  public int getAllowReview() {
    return allowReview_;
  }

  public static final int CAN_WATCH_FIELD_NUMBER = 3;
  private int canWatch_ = 0;
  /**
   * <pre>
   * </pre>
   *
   * <code>int32 can_watch = 3;</code>
   * @return The canWatch.
   */
  @java.lang.Override
  public int getCanWatch() {
    return canWatch_;
  }

  public static final int IS_COVER_SHOW_FIELD_NUMBER = 4;
  private int isCoverShow_ = 0;
  /**
   * <pre>
   * </pre>
   *
   * <code>int32 is_cover_show = 4;</code>
   * @return The isCoverShow.
   */
  @java.lang.Override
  public int getIsCoverShow() {
    return isCoverShow_;
  }

  public static final int COPYRIGHT_FIELD_NUMBER = 5;
  @SuppressWarnings("serial")
  private volatile java.lang.Object copyright_ = "";
  /**
   * <pre>
   * </pre>
   *
   * <code>string copyright = 5;</code>
   * @return The copyright.
   */
  @java.lang.Override
  public java.lang.String getCopyright() {
    java.lang.Object ref = copyright_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      copyright_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * </pre>
   *
   * <code>string copyright = 5;</code>
   * @return The bytes for copyright.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getCopyrightBytes() {
    java.lang.Object ref = copyright_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      copyright_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int COPYRIGHT_NAME_FIELD_NUMBER = 6;
  @SuppressWarnings("serial")
  private volatile java.lang.Object copyrightName_ = "";
  /**
   * <pre>
   * </pre>
   *
   * <code>string copyright_name = 6;</code>
   * @return The copyrightName.
   */
  @java.lang.Override
  public java.lang.String getCopyrightName() {
    java.lang.Object ref = copyrightName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      copyrightName_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * </pre>
   *
   * <code>string copyright_name = 6;</code>
   * @return The bytes for copyrightName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getCopyrightNameBytes() {
    java.lang.Object ref = copyrightName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      copyrightName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ALLOW_BP_FIELD_NUMBER = 7;
  private int allowBp_ = 0;
  /**
   * <pre>
   * </pre>
   *
   * <code>int32 allow_bp = 7;</code>
   * @return The allowBp.
   */
  @java.lang.Override
  public int getAllowBp() {
    return allowBp_;
  }

  public static final int AREA_LIMIT_FIELD_NUMBER = 8;
  private int areaLimit_ = 0;
  /**
   * <pre>
   * </pre>
   *
   * <code>int32 area_limit = 8;</code>
   * @return The areaLimit.
   */
  @java.lang.Override
  public int getAreaLimit() {
    return areaLimit_;
  }

  public static final int IS_PREVIEW_FIELD_NUMBER = 9;
  private int isPreview_ = 0;
  /**
   * <pre>
   * </pre>
   *
   * <code>int32 is_preview = 9;</code>
   * @return The isPreview.
   */
  @java.lang.Override
  public int getIsPreview() {
    return isPreview_;
  }

  public static final int BAN_AREA_SHOW_FIELD_NUMBER = 10;
  private int banAreaShow_ = 0;
  /**
   * <pre>
   * </pre>
   *
   * <code>int32 ban_area_show = 10;</code>
   * @return The banAreaShow.
   */
  @java.lang.Override
  public int getBanAreaShow() {
    return banAreaShow_;
  }

  public static final int WATCH_PLATFORM_FIELD_NUMBER = 11;
  private int watchPlatform_ = 0;
  /**
   * <pre>
   * </pre>
   *
   * <code>int32 watch_platform = 11;</code>
   * @return The watchPlatform.
   */
  @java.lang.Override
  public int getWatchPlatform() {
    return watchPlatform_;
  }

  public static final int ALLOW_BP_RANK_FIELD_NUMBER = 12;
  private int allowBpRank_ = 0;
  /**
   * <pre>
   * </pre>
   *
   * <code>int32 allow_bp_rank = 12;</code>
   * @return The allowBpRank.
   */
  @java.lang.Override
  public int getAllowBpRank() {
    return allowBpRank_;
  }

  public static final int RESOURCE_FIELD_NUMBER = 13;
  @SuppressWarnings("serial")
  private volatile java.lang.Object resource_ = "";
  /**
   * <pre>
   * </pre>
   *
   * <code>string resource = 13;</code>
   * @return The resource.
   */
  @java.lang.Override
  public java.lang.String getResource() {
    java.lang.Object ref = resource_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      resource_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * </pre>
   *
   * <code>string resource = 13;</code>
   * @return The bytes for resource.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getResourceBytes() {
    java.lang.Object ref = resource_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      resource_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int FORBID_PRE_FIELD_NUMBER = 14;
  private int forbidPre_ = 0;
  /**
   * <pre>
   * </pre>
   *
   * <code>int32 forbid_pre = 14;</code>
   * @return The forbidPre.
   */
  @java.lang.Override
  public int getForbidPre() {
    return forbidPre_;
  }

  public static final int ONLY_VIP_DOWNLOAD_FIELD_NUMBER = 15;
  private int onlyVipDownload_ = 0;
  /**
   * <pre>
   * </pre>
   *
   * <code>int32 only_vip_download = 15;</code>
   * @return The onlyVipDownload.
   */
  @java.lang.Override
  public int getOnlyVipDownload() {
    return onlyVipDownload_;
  }

  public static final int NEW_ALLOW_DOWNLOAD_FIELD_NUMBER = 16;
  private int newAllowDownload_ = 0;
  /**
   * <pre>
   * </pre>
   *
   * <code>int32 new_allow_download = 16;</code>
   * @return The newAllowDownload.
   */
  @java.lang.Override
  public int getNewAllowDownload() {
    return newAllowDownload_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (allowDownload_ != 0) {
      output.writeInt32(1, allowDownload_);
    }
    if (allowReview_ != 0) {
      output.writeInt32(2, allowReview_);
    }
    if (canWatch_ != 0) {
      output.writeInt32(3, canWatch_);
    }
    if (isCoverShow_ != 0) {
      output.writeInt32(4, isCoverShow_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(copyright_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 5, copyright_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(copyrightName_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 6, copyrightName_);
    }
    if (allowBp_ != 0) {
      output.writeInt32(7, allowBp_);
    }
    if (areaLimit_ != 0) {
      output.writeInt32(8, areaLimit_);
    }
    if (isPreview_ != 0) {
      output.writeInt32(9, isPreview_);
    }
    if (banAreaShow_ != 0) {
      output.writeInt32(10, banAreaShow_);
    }
    if (watchPlatform_ != 0) {
      output.writeInt32(11, watchPlatform_);
    }
    if (allowBpRank_ != 0) {
      output.writeInt32(12, allowBpRank_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(resource_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 13, resource_);
    }
    if (forbidPre_ != 0) {
      output.writeInt32(14, forbidPre_);
    }
    if (onlyVipDownload_ != 0) {
      output.writeInt32(15, onlyVipDownload_);
    }
    if (newAllowDownload_ != 0) {
      output.writeInt32(16, newAllowDownload_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (allowDownload_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, allowDownload_);
    }
    if (allowReview_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, allowReview_);
    }
    if (canWatch_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, canWatch_);
    }
    if (isCoverShow_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(4, isCoverShow_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(copyright_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(5, copyright_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(copyrightName_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(6, copyrightName_);
    }
    if (allowBp_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(7, allowBp_);
    }
    if (areaLimit_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(8, areaLimit_);
    }
    if (isPreview_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(9, isPreview_);
    }
    if (banAreaShow_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(10, banAreaShow_);
    }
    if (watchPlatform_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(11, watchPlatform_);
    }
    if (allowBpRank_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(12, allowBpRank_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(resource_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(13, resource_);
    }
    if (forbidPre_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(14, forbidPre_);
    }
    if (onlyVipDownload_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(15, onlyVipDownload_);
    }
    if (newAllowDownload_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(16, newAllowDownload_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof bilibili.app.viewunite.pgcanymodel.Rights)) {
      return super.equals(obj);
    }
    bilibili.app.viewunite.pgcanymodel.Rights other = (bilibili.app.viewunite.pgcanymodel.Rights) obj;

    if (getAllowDownload()
        != other.getAllowDownload()) return false;
    if (getAllowReview()
        != other.getAllowReview()) return false;
    if (getCanWatch()
        != other.getCanWatch()) return false;
    if (getIsCoverShow()
        != other.getIsCoverShow()) return false;
    if (!getCopyright()
        .equals(other.getCopyright())) return false;
    if (!getCopyrightName()
        .equals(other.getCopyrightName())) return false;
    if (getAllowBp()
        != other.getAllowBp()) return false;
    if (getAreaLimit()
        != other.getAreaLimit()) return false;
    if (getIsPreview()
        != other.getIsPreview()) return false;
    if (getBanAreaShow()
        != other.getBanAreaShow()) return false;
    if (getWatchPlatform()
        != other.getWatchPlatform()) return false;
    if (getAllowBpRank()
        != other.getAllowBpRank()) return false;
    if (!getResource()
        .equals(other.getResource())) return false;
    if (getForbidPre()
        != other.getForbidPre()) return false;
    if (getOnlyVipDownload()
        != other.getOnlyVipDownload()) return false;
    if (getNewAllowDownload()
        != other.getNewAllowDownload()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ALLOW_DOWNLOAD_FIELD_NUMBER;
    hash = (53 * hash) + getAllowDownload();
    hash = (37 * hash) + ALLOW_REVIEW_FIELD_NUMBER;
    hash = (53 * hash) + getAllowReview();
    hash = (37 * hash) + CAN_WATCH_FIELD_NUMBER;
    hash = (53 * hash) + getCanWatch();
    hash = (37 * hash) + IS_COVER_SHOW_FIELD_NUMBER;
    hash = (53 * hash) + getIsCoverShow();
    hash = (37 * hash) + COPYRIGHT_FIELD_NUMBER;
    hash = (53 * hash) + getCopyright().hashCode();
    hash = (37 * hash) + COPYRIGHT_NAME_FIELD_NUMBER;
    hash = (53 * hash) + getCopyrightName().hashCode();
    hash = (37 * hash) + ALLOW_BP_FIELD_NUMBER;
    hash = (53 * hash) + getAllowBp();
    hash = (37 * hash) + AREA_LIMIT_FIELD_NUMBER;
    hash = (53 * hash) + getAreaLimit();
    hash = (37 * hash) + IS_PREVIEW_FIELD_NUMBER;
    hash = (53 * hash) + getIsPreview();
    hash = (37 * hash) + BAN_AREA_SHOW_FIELD_NUMBER;
    hash = (53 * hash) + getBanAreaShow();
    hash = (37 * hash) + WATCH_PLATFORM_FIELD_NUMBER;
    hash = (53 * hash) + getWatchPlatform();
    hash = (37 * hash) + ALLOW_BP_RANK_FIELD_NUMBER;
    hash = (53 * hash) + getAllowBpRank();
    hash = (37 * hash) + RESOURCE_FIELD_NUMBER;
    hash = (53 * hash) + getResource().hashCode();
    hash = (37 * hash) + FORBID_PRE_FIELD_NUMBER;
    hash = (53 * hash) + getForbidPre();
    hash = (37 * hash) + ONLY_VIP_DOWNLOAD_FIELD_NUMBER;
    hash = (53 * hash) + getOnlyVipDownload();
    hash = (37 * hash) + NEW_ALLOW_DOWNLOAD_FIELD_NUMBER;
    hash = (53 * hash) + getNewAllowDownload();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static bilibili.app.viewunite.pgcanymodel.Rights parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static bilibili.app.viewunite.pgcanymodel.Rights parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static bilibili.app.viewunite.pgcanymodel.Rights parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static bilibili.app.viewunite.pgcanymodel.Rights parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static bilibili.app.viewunite.pgcanymodel.Rights parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static bilibili.app.viewunite.pgcanymodel.Rights parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static bilibili.app.viewunite.pgcanymodel.Rights parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static bilibili.app.viewunite.pgcanymodel.Rights parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static bilibili.app.viewunite.pgcanymodel.Rights parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static bilibili.app.viewunite.pgcanymodel.Rights parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static bilibili.app.viewunite.pgcanymodel.Rights parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static bilibili.app.viewunite.pgcanymodel.Rights parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(bilibili.app.viewunite.pgcanymodel.Rights prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * 权限相关信息
   * </pre>
   *
   * Protobuf type {@code bilibili.app.viewunite.pgcanymodel.Rights}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:bilibili.app.viewunite.pgcanymodel.Rights)
      bilibili.app.viewunite.pgcanymodel.RightsOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return bilibili.app.viewunite.pgcanymodel.Pgcanymodel.internal_static_bilibili_app_viewunite_pgcanymodel_Rights_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return bilibili.app.viewunite.pgcanymodel.Pgcanymodel.internal_static_bilibili_app_viewunite_pgcanymodel_Rights_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              bilibili.app.viewunite.pgcanymodel.Rights.class, bilibili.app.viewunite.pgcanymodel.Rights.Builder.class);
    }

    // Construct using bilibili.app.viewunite.pgcanymodel.Rights.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      allowDownload_ = 0;
      allowReview_ = 0;
      canWatch_ = 0;
      isCoverShow_ = 0;
      copyright_ = "";
      copyrightName_ = "";
      allowBp_ = 0;
      areaLimit_ = 0;
      isPreview_ = 0;
      banAreaShow_ = 0;
      watchPlatform_ = 0;
      allowBpRank_ = 0;
      resource_ = "";
      forbidPre_ = 0;
      onlyVipDownload_ = 0;
      newAllowDownload_ = 0;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return bilibili.app.viewunite.pgcanymodel.Pgcanymodel.internal_static_bilibili_app_viewunite_pgcanymodel_Rights_descriptor;
    }

    @java.lang.Override
    public bilibili.app.viewunite.pgcanymodel.Rights getDefaultInstanceForType() {
      return bilibili.app.viewunite.pgcanymodel.Rights.getDefaultInstance();
    }

    @java.lang.Override
    public bilibili.app.viewunite.pgcanymodel.Rights build() {
      bilibili.app.viewunite.pgcanymodel.Rights result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public bilibili.app.viewunite.pgcanymodel.Rights buildPartial() {
      bilibili.app.viewunite.pgcanymodel.Rights result = new bilibili.app.viewunite.pgcanymodel.Rights(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(bilibili.app.viewunite.pgcanymodel.Rights result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.allowDownload_ = allowDownload_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.allowReview_ = allowReview_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.canWatch_ = canWatch_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.isCoverShow_ = isCoverShow_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.copyright_ = copyright_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.copyrightName_ = copyrightName_;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.allowBp_ = allowBp_;
      }
      if (((from_bitField0_ & 0x00000080) != 0)) {
        result.areaLimit_ = areaLimit_;
      }
      if (((from_bitField0_ & 0x00000100) != 0)) {
        result.isPreview_ = isPreview_;
      }
      if (((from_bitField0_ & 0x00000200) != 0)) {
        result.banAreaShow_ = banAreaShow_;
      }
      if (((from_bitField0_ & 0x00000400) != 0)) {
        result.watchPlatform_ = watchPlatform_;
      }
      if (((from_bitField0_ & 0x00000800) != 0)) {
        result.allowBpRank_ = allowBpRank_;
      }
      if (((from_bitField0_ & 0x00001000) != 0)) {
        result.resource_ = resource_;
      }
      if (((from_bitField0_ & 0x00002000) != 0)) {
        result.forbidPre_ = forbidPre_;
      }
      if (((from_bitField0_ & 0x00004000) != 0)) {
        result.onlyVipDownload_ = onlyVipDownload_;
      }
      if (((from_bitField0_ & 0x00008000) != 0)) {
        result.newAllowDownload_ = newAllowDownload_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof bilibili.app.viewunite.pgcanymodel.Rights) {
        return mergeFrom((bilibili.app.viewunite.pgcanymodel.Rights)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(bilibili.app.viewunite.pgcanymodel.Rights other) {
      if (other == bilibili.app.viewunite.pgcanymodel.Rights.getDefaultInstance()) return this;
      if (other.getAllowDownload() != 0) {
        setAllowDownload(other.getAllowDownload());
      }
      if (other.getAllowReview() != 0) {
        setAllowReview(other.getAllowReview());
      }
      if (other.getCanWatch() != 0) {
        setCanWatch(other.getCanWatch());
      }
      if (other.getIsCoverShow() != 0) {
        setIsCoverShow(other.getIsCoverShow());
      }
      if (!other.getCopyright().isEmpty()) {
        copyright_ = other.copyright_;
        bitField0_ |= 0x00000010;
        onChanged();
      }
      if (!other.getCopyrightName().isEmpty()) {
        copyrightName_ = other.copyrightName_;
        bitField0_ |= 0x00000020;
        onChanged();
      }
      if (other.getAllowBp() != 0) {
        setAllowBp(other.getAllowBp());
      }
      if (other.getAreaLimit() != 0) {
        setAreaLimit(other.getAreaLimit());
      }
      if (other.getIsPreview() != 0) {
        setIsPreview(other.getIsPreview());
      }
      if (other.getBanAreaShow() != 0) {
        setBanAreaShow(other.getBanAreaShow());
      }
      if (other.getWatchPlatform() != 0) {
        setWatchPlatform(other.getWatchPlatform());
      }
      if (other.getAllowBpRank() != 0) {
        setAllowBpRank(other.getAllowBpRank());
      }
      if (!other.getResource().isEmpty()) {
        resource_ = other.resource_;
        bitField0_ |= 0x00001000;
        onChanged();
      }
      if (other.getForbidPre() != 0) {
        setForbidPre(other.getForbidPre());
      }
      if (other.getOnlyVipDownload() != 0) {
        setOnlyVipDownload(other.getOnlyVipDownload());
      }
      if (other.getNewAllowDownload() != 0) {
        setNewAllowDownload(other.getNewAllowDownload());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              allowDownload_ = input.readInt32();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 16: {
              allowReview_ = input.readInt32();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 24: {
              canWatch_ = input.readInt32();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            case 32: {
              isCoverShow_ = input.readInt32();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            case 42: {
              copyright_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000010;
              break;
            } // case 42
            case 50: {
              copyrightName_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000020;
              break;
            } // case 50
            case 56: {
              allowBp_ = input.readInt32();
              bitField0_ |= 0x00000040;
              break;
            } // case 56
            case 64: {
              areaLimit_ = input.readInt32();
              bitField0_ |= 0x00000080;
              break;
            } // case 64
            case 72: {
              isPreview_ = input.readInt32();
              bitField0_ |= 0x00000100;
              break;
            } // case 72
            case 80: {
              banAreaShow_ = input.readInt32();
              bitField0_ |= 0x00000200;
              break;
            } // case 80
            case 88: {
              watchPlatform_ = input.readInt32();
              bitField0_ |= 0x00000400;
              break;
            } // case 88
            case 96: {
              allowBpRank_ = input.readInt32();
              bitField0_ |= 0x00000800;
              break;
            } // case 96
            case 106: {
              resource_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00001000;
              break;
            } // case 106
            case 112: {
              forbidPre_ = input.readInt32();
              bitField0_ |= 0x00002000;
              break;
            } // case 112
            case 120: {
              onlyVipDownload_ = input.readInt32();
              bitField0_ |= 0x00004000;
              break;
            } // case 120
            case 128: {
              newAllowDownload_ = input.readInt32();
              bitField0_ |= 0x00008000;
              break;
            } // case 128
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private int allowDownload_ ;
    /**
     * <pre>
     * </pre>
     *
     * <code>int32 allow_download = 1;</code>
     * @return The allowDownload.
     */
    @java.lang.Override
    public int getAllowDownload() {
      return allowDownload_;
    }
    /**
     * <pre>
     * </pre>
     *
     * <code>int32 allow_download = 1;</code>
     * @param value The allowDownload to set.
     * @return This builder for chaining.
     */
    public Builder setAllowDownload(int value) {

      allowDownload_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * </pre>
     *
     * <code>int32 allow_download = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearAllowDownload() {
      bitField0_ = (bitField0_ & ~0x00000001);
      allowDownload_ = 0;
      onChanged();
      return this;
    }

    private int allowReview_ ;
    /**
     * <pre>
     * </pre>
     *
     * <code>int32 allow_review = 2;</code>
     * @return The allowReview.
     */
    @java.lang.Override
    public int getAllowReview() {
      return allowReview_;
    }
    /**
     * <pre>
     * </pre>
     *
     * <code>int32 allow_review = 2;</code>
     * @param value The allowReview to set.
     * @return This builder for chaining.
     */
    public Builder setAllowReview(int value) {

      allowReview_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * </pre>
     *
     * <code>int32 allow_review = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearAllowReview() {
      bitField0_ = (bitField0_ & ~0x00000002);
      allowReview_ = 0;
      onChanged();
      return this;
    }

    private int canWatch_ ;
    /**
     * <pre>
     * </pre>
     *
     * <code>int32 can_watch = 3;</code>
     * @return The canWatch.
     */
    @java.lang.Override
    public int getCanWatch() {
      return canWatch_;
    }
    /**
     * <pre>
     * </pre>
     *
     * <code>int32 can_watch = 3;</code>
     * @param value The canWatch to set.
     * @return This builder for chaining.
     */
    public Builder setCanWatch(int value) {

      canWatch_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * </pre>
     *
     * <code>int32 can_watch = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearCanWatch() {
      bitField0_ = (bitField0_ & ~0x00000004);
      canWatch_ = 0;
      onChanged();
      return this;
    }

    private int isCoverShow_ ;
    /**
     * <pre>
     * </pre>
     *
     * <code>int32 is_cover_show = 4;</code>
     * @return The isCoverShow.
     */
    @java.lang.Override
    public int getIsCoverShow() {
      return isCoverShow_;
    }
    /**
     * <pre>
     * </pre>
     *
     * <code>int32 is_cover_show = 4;</code>
     * @param value The isCoverShow to set.
     * @return This builder for chaining.
     */
    public Builder setIsCoverShow(int value) {

      isCoverShow_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * </pre>
     *
     * <code>int32 is_cover_show = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearIsCoverShow() {
      bitField0_ = (bitField0_ & ~0x00000008);
      isCoverShow_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object copyright_ = "";
    /**
     * <pre>
     * </pre>
     *
     * <code>string copyright = 5;</code>
     * @return The copyright.
     */
    public java.lang.String getCopyright() {
      java.lang.Object ref = copyright_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        copyright_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * </pre>
     *
     * <code>string copyright = 5;</code>
     * @return The bytes for copyright.
     */
    public com.google.protobuf.ByteString
        getCopyrightBytes() {
      java.lang.Object ref = copyright_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        copyright_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * </pre>
     *
     * <code>string copyright = 5;</code>
     * @param value The copyright to set.
     * @return This builder for chaining.
     */
    public Builder setCopyright(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      copyright_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * </pre>
     *
     * <code>string copyright = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearCopyright() {
      copyright_ = getDefaultInstance().getCopyright();
      bitField0_ = (bitField0_ & ~0x00000010);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * </pre>
     *
     * <code>string copyright = 5;</code>
     * @param value The bytes for copyright to set.
     * @return This builder for chaining.
     */
    public Builder setCopyrightBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      copyright_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }

    private java.lang.Object copyrightName_ = "";
    /**
     * <pre>
     * </pre>
     *
     * <code>string copyright_name = 6;</code>
     * @return The copyrightName.
     */
    public java.lang.String getCopyrightName() {
      java.lang.Object ref = copyrightName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        copyrightName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * </pre>
     *
     * <code>string copyright_name = 6;</code>
     * @return The bytes for copyrightName.
     */
    public com.google.protobuf.ByteString
        getCopyrightNameBytes() {
      java.lang.Object ref = copyrightName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        copyrightName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * </pre>
     *
     * <code>string copyright_name = 6;</code>
     * @param value The copyrightName to set.
     * @return This builder for chaining.
     */
    public Builder setCopyrightName(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      copyrightName_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * </pre>
     *
     * <code>string copyright_name = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearCopyrightName() {
      copyrightName_ = getDefaultInstance().getCopyrightName();
      bitField0_ = (bitField0_ & ~0x00000020);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * </pre>
     *
     * <code>string copyright_name = 6;</code>
     * @param value The bytes for copyrightName to set.
     * @return This builder for chaining.
     */
    public Builder setCopyrightNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      copyrightName_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }

    private int allowBp_ ;
    /**
     * <pre>
     * </pre>
     *
     * <code>int32 allow_bp = 7;</code>
     * @return The allowBp.
     */
    @java.lang.Override
    public int getAllowBp() {
      return allowBp_;
    }
    /**
     * <pre>
     * </pre>
     *
     * <code>int32 allow_bp = 7;</code>
     * @param value The allowBp to set.
     * @return This builder for chaining.
     */
    public Builder setAllowBp(int value) {

      allowBp_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * </pre>
     *
     * <code>int32 allow_bp = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearAllowBp() {
      bitField0_ = (bitField0_ & ~0x00000040);
      allowBp_ = 0;
      onChanged();
      return this;
    }

    private int areaLimit_ ;
    /**
     * <pre>
     * </pre>
     *
     * <code>int32 area_limit = 8;</code>
     * @return The areaLimit.
     */
    @java.lang.Override
    public int getAreaLimit() {
      return areaLimit_;
    }
    /**
     * <pre>
     * </pre>
     *
     * <code>int32 area_limit = 8;</code>
     * @param value The areaLimit to set.
     * @return This builder for chaining.
     */
    public Builder setAreaLimit(int value) {

      areaLimit_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * </pre>
     *
     * <code>int32 area_limit = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearAreaLimit() {
      bitField0_ = (bitField0_ & ~0x00000080);
      areaLimit_ = 0;
      onChanged();
      return this;
    }

    private int isPreview_ ;
    /**
     * <pre>
     * </pre>
     *
     * <code>int32 is_preview = 9;</code>
     * @return The isPreview.
     */
    @java.lang.Override
    public int getIsPreview() {
      return isPreview_;
    }
    /**
     * <pre>
     * </pre>
     *
     * <code>int32 is_preview = 9;</code>
     * @param value The isPreview to set.
     * @return This builder for chaining.
     */
    public Builder setIsPreview(int value) {

      isPreview_ = value;
      bitField0_ |= 0x00000100;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * </pre>
     *
     * <code>int32 is_preview = 9;</code>
     * @return This builder for chaining.
     */
    public Builder clearIsPreview() {
      bitField0_ = (bitField0_ & ~0x00000100);
      isPreview_ = 0;
      onChanged();
      return this;
    }

    private int banAreaShow_ ;
    /**
     * <pre>
     * </pre>
     *
     * <code>int32 ban_area_show = 10;</code>
     * @return The banAreaShow.
     */
    @java.lang.Override
    public int getBanAreaShow() {
      return banAreaShow_;
    }
    /**
     * <pre>
     * </pre>
     *
     * <code>int32 ban_area_show = 10;</code>
     * @param value The banAreaShow to set.
     * @return This builder for chaining.
     */
    public Builder setBanAreaShow(int value) {

      banAreaShow_ = value;
      bitField0_ |= 0x00000200;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * </pre>
     *
     * <code>int32 ban_area_show = 10;</code>
     * @return This builder for chaining.
     */
    public Builder clearBanAreaShow() {
      bitField0_ = (bitField0_ & ~0x00000200);
      banAreaShow_ = 0;
      onChanged();
      return this;
    }

    private int watchPlatform_ ;
    /**
     * <pre>
     * </pre>
     *
     * <code>int32 watch_platform = 11;</code>
     * @return The watchPlatform.
     */
    @java.lang.Override
    public int getWatchPlatform() {
      return watchPlatform_;
    }
    /**
     * <pre>
     * </pre>
     *
     * <code>int32 watch_platform = 11;</code>
     * @param value The watchPlatform to set.
     * @return This builder for chaining.
     */
    public Builder setWatchPlatform(int value) {

      watchPlatform_ = value;
      bitField0_ |= 0x00000400;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * </pre>
     *
     * <code>int32 watch_platform = 11;</code>
     * @return This builder for chaining.
     */
    public Builder clearWatchPlatform() {
      bitField0_ = (bitField0_ & ~0x00000400);
      watchPlatform_ = 0;
      onChanged();
      return this;
    }

    private int allowBpRank_ ;
    /**
     * <pre>
     * </pre>
     *
     * <code>int32 allow_bp_rank = 12;</code>
     * @return The allowBpRank.
     */
    @java.lang.Override
    public int getAllowBpRank() {
      return allowBpRank_;
    }
    /**
     * <pre>
     * </pre>
     *
     * <code>int32 allow_bp_rank = 12;</code>
     * @param value The allowBpRank to set.
     * @return This builder for chaining.
     */
    public Builder setAllowBpRank(int value) {

      allowBpRank_ = value;
      bitField0_ |= 0x00000800;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * </pre>
     *
     * <code>int32 allow_bp_rank = 12;</code>
     * @return This builder for chaining.
     */
    public Builder clearAllowBpRank() {
      bitField0_ = (bitField0_ & ~0x00000800);
      allowBpRank_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object resource_ = "";
    /**
     * <pre>
     * </pre>
     *
     * <code>string resource = 13;</code>
     * @return The resource.
     */
    public java.lang.String getResource() {
      java.lang.Object ref = resource_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        resource_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * </pre>
     *
     * <code>string resource = 13;</code>
     * @return The bytes for resource.
     */
    public com.google.protobuf.ByteString
        getResourceBytes() {
      java.lang.Object ref = resource_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        resource_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * </pre>
     *
     * <code>string resource = 13;</code>
     * @param value The resource to set.
     * @return This builder for chaining.
     */
    public Builder setResource(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      resource_ = value;
      bitField0_ |= 0x00001000;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * </pre>
     *
     * <code>string resource = 13;</code>
     * @return This builder for chaining.
     */
    public Builder clearResource() {
      resource_ = getDefaultInstance().getResource();
      bitField0_ = (bitField0_ & ~0x00001000);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * </pre>
     *
     * <code>string resource = 13;</code>
     * @param value The bytes for resource to set.
     * @return This builder for chaining.
     */
    public Builder setResourceBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      resource_ = value;
      bitField0_ |= 0x00001000;
      onChanged();
      return this;
    }

    private int forbidPre_ ;
    /**
     * <pre>
     * </pre>
     *
     * <code>int32 forbid_pre = 14;</code>
     * @return The forbidPre.
     */
    @java.lang.Override
    public int getForbidPre() {
      return forbidPre_;
    }
    /**
     * <pre>
     * </pre>
     *
     * <code>int32 forbid_pre = 14;</code>
     * @param value The forbidPre to set.
     * @return This builder for chaining.
     */
    public Builder setForbidPre(int value) {

      forbidPre_ = value;
      bitField0_ |= 0x00002000;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * </pre>
     *
     * <code>int32 forbid_pre = 14;</code>
     * @return This builder for chaining.
     */
    public Builder clearForbidPre() {
      bitField0_ = (bitField0_ & ~0x00002000);
      forbidPre_ = 0;
      onChanged();
      return this;
    }

    private int onlyVipDownload_ ;
    /**
     * <pre>
     * </pre>
     *
     * <code>int32 only_vip_download = 15;</code>
     * @return The onlyVipDownload.
     */
    @java.lang.Override
    public int getOnlyVipDownload() {
      return onlyVipDownload_;
    }
    /**
     * <pre>
     * </pre>
     *
     * <code>int32 only_vip_download = 15;</code>
     * @param value The onlyVipDownload to set.
     * @return This builder for chaining.
     */
    public Builder setOnlyVipDownload(int value) {

      onlyVipDownload_ = value;
      bitField0_ |= 0x00004000;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * </pre>
     *
     * <code>int32 only_vip_download = 15;</code>
     * @return This builder for chaining.
     */
    public Builder clearOnlyVipDownload() {
      bitField0_ = (bitField0_ & ~0x00004000);
      onlyVipDownload_ = 0;
      onChanged();
      return this;
    }

    private int newAllowDownload_ ;
    /**
     * <pre>
     * </pre>
     *
     * <code>int32 new_allow_download = 16;</code>
     * @return The newAllowDownload.
     */
    @java.lang.Override
    public int getNewAllowDownload() {
      return newAllowDownload_;
    }
    /**
     * <pre>
     * </pre>
     *
     * <code>int32 new_allow_download = 16;</code>
     * @param value The newAllowDownload to set.
     * @return This builder for chaining.
     */
    public Builder setNewAllowDownload(int value) {

      newAllowDownload_ = value;
      bitField0_ |= 0x00008000;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * </pre>
     *
     * <code>int32 new_allow_download = 16;</code>
     * @return This builder for chaining.
     */
    public Builder clearNewAllowDownload() {
      bitField0_ = (bitField0_ & ~0x00008000);
      newAllowDownload_ = 0;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:bilibili.app.viewunite.pgcanymodel.Rights)
  }

  // @@protoc_insertion_point(class_scope:bilibili.app.viewunite.pgcanymodel.Rights)
  private static final bilibili.app.viewunite.pgcanymodel.Rights DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new bilibili.app.viewunite.pgcanymodel.Rights();
  }

  public static bilibili.app.viewunite.pgcanymodel.Rights getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Rights>
      PARSER = new com.google.protobuf.AbstractParser<Rights>() {
    @java.lang.Override
    public Rights parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Rights> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Rights> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public bilibili.app.viewunite.pgcanymodel.Rights getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

