// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: bilibili/app/listener/v1/listener.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package bilibili.app.listener.v1;

@kotlin.jvm.JvmName("-initializefavFolderMeta")
public inline fun favFolderMeta(block: bilibili.app.listener.v1.FavFolderMetaKt.Dsl.() -> kotlin.Unit): bilibili.app.listener.v1.FavFolderMeta =
  bilibili.app.listener.v1.FavFolderMetaKt.Dsl._create(bilibili.app.listener.v1.FavFolderMeta.newBuilder()).apply { block() }._build()
/**
 * ```
 * ```
 *
 * Protobuf type `bilibili.app.listener.v1.FavFolderMeta`
 */
public object FavFolderMetaKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: bilibili.app.listener.v1.FavFolderMeta.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: bilibili.app.listener.v1.FavFolderMeta.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): bilibili.app.listener.v1.FavFolderMeta = _builder.build()

    /**
     * ```
     * ```
     *
     * `int64 fid = 1;`
     */
    public var fid: kotlin.Long
      @JvmName("getFid")
      get() = _builder.getFid()
      @JvmName("setFid")
      set(value) {
        _builder.setFid(value)
      }
    /**
     * ```
     * ```
     *
     * `int64 fid = 1;`
     */
    public fun clearFid() {
      _builder.clearFid()
    }

    /**
     * ```
     * ```
     *
     * `int32 folder_type = 2;`
     */
    public var folderType: kotlin.Int
      @JvmName("getFolderType")
      get() = _builder.getFolderType()
      @JvmName("setFolderType")
      set(value) {
        _builder.setFolderType(value)
      }
    /**
     * ```
     * ```
     *
     * `int32 folder_type = 2;`
     */
    public fun clearFolderType() {
      _builder.clearFolderType()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun bilibili.app.listener.v1.FavFolderMeta.copy(block: `bilibili.app.listener.v1`.FavFolderMetaKt.Dsl.() -> kotlin.Unit): bilibili.app.listener.v1.FavFolderMeta =
  `bilibili.app.listener.v1`.FavFolderMetaKt.Dsl._create(this.toBuilder()).apply { block() }._build()

