// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: bilibili/app/listener/v1/listener.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package bilibili.app.listener.v1;

@kotlin.jvm.JvmName("-initializefavFolderDetailReq")
public inline fun favFolderDetailReq(block: bilibili.app.listener.v1.FavFolderDetailReqKt.Dsl.() -> kotlin.Unit): bilibili.app.listener.v1.FavFolderDetailReq =
  bilibili.app.listener.v1.FavFolderDetailReqKt.Dsl._create(bilibili.app.listener.v1.FavFolderDetailReq.newBuilder()).apply { block() }._build()
/**
 * ```
 * ```
 *
 * Protobuf type `bilibili.app.listener.v1.FavFolderDetailReq`
 */
public object FavFolderDetailReqKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: bilibili.app.listener.v1.FavFolderDetailReq.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: bilibili.app.listener.v1.FavFolderDetailReq.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): bilibili.app.listener.v1.FavFolderDetailReq = _builder.build()

    /**
     * ```
     * ```
     *
     * `int64 fid = 1;`
     */
    public var fid: kotlin.Long
      @JvmName("getFid")
      get() = _builder.getFid()
      @JvmName("setFid")
      set(value) {
        _builder.setFid(value)
      }
    /**
     * ```
     * ```
     *
     * `int64 fid = 1;`
     */
    public fun clearFid() {
      _builder.clearFid()
    }

    /**
     * ```
     * ```
     *
     * `int32 folder_type = 2;`
     */
    public var folderType: kotlin.Int
      @JvmName("getFolderType")
      get() = _builder.getFolderType()
      @JvmName("setFolderType")
      set(value) {
        _builder.setFolderType(value)
      }
    /**
     * ```
     * ```
     *
     * `int32 folder_type = 2;`
     */
    public fun clearFolderType() {
      _builder.clearFolderType()
    }

    /**
     * ```
     * ```
     *
     * `int64 fav_mid = 3;`
     */
    public var favMid: kotlin.Long
      @JvmName("getFavMid")
      get() = _builder.getFavMid()
      @JvmName("setFavMid")
      set(value) {
        _builder.setFavMid(value)
      }
    /**
     * ```
     * ```
     *
     * `int64 fav_mid = 3;`
     */
    public fun clearFavMid() {
      _builder.clearFavMid()
    }

    /**
     * ```
     * ```
     *
     * `.bilibili.app.listener.v1.FavItem last_item = 4;`
     */
    public var lastItem: bilibili.app.listener.v1.FavItem
      @JvmName("getLastItem")
      get() = _builder.getLastItem()
      @JvmName("setLastItem")
      set(value) {
        _builder.setLastItem(value)
      }
    /**
     * ```
     * ```
     *
     * `.bilibili.app.listener.v1.FavItem last_item = 4;`
     */
    public fun clearLastItem() {
      _builder.clearLastItem()
    }
    /**
     * ```
     * ```
     *
     * `.bilibili.app.listener.v1.FavItem last_item = 4;`
     * @return Whether the lastItem field is set.
     */
    public fun hasLastItem(): kotlin.Boolean {
      return _builder.hasLastItem()
    }
    public val FavFolderDetailReqKt.Dsl.lastItemOrNull: bilibili.app.listener.v1.FavItem?
      get() = _builder.lastItemOrNull

    /**
     * ```
     * ```
     *
     * `int32 page_size = 5;`
     */
    public var pageSize: kotlin.Int
      @JvmName("getPageSize")
      get() = _builder.getPageSize()
      @JvmName("setPageSize")
      set(value) {
        _builder.setPageSize(value)
      }
    /**
     * ```
     * ```
     *
     * `int32 page_size = 5;`
     */
    public fun clearPageSize() {
      _builder.clearPageSize()
    }

    /**
     * ```
     * ```
     *
     * `bool need_folder_info = 6;`
     */
    public var needFolderInfo: kotlin.Boolean
      @JvmName("getNeedFolderInfo")
      get() = _builder.getNeedFolderInfo()
      @JvmName("setNeedFolderInfo")
      set(value) {
        _builder.setNeedFolderInfo(value)
      }
    /**
     * ```
     * ```
     *
     * `bool need_folder_info = 6;`
     */
    public fun clearNeedFolderInfo() {
      _builder.clearNeedFolderInfo()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun bilibili.app.listener.v1.FavFolderDetailReq.copy(block: `bilibili.app.listener.v1`.FavFolderDetailReqKt.Dsl.() -> kotlin.Unit): bilibili.app.listener.v1.FavFolderDetailReq =
  `bilibili.app.listener.v1`.FavFolderDetailReqKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val bilibili.app.listener.v1.FavFolderDetailReqOrBuilder.lastItemOrNull: bilibili.app.listener.v1.FavItem?
  get() = if (hasLastItem()) getLastItem() else null

