// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: bilibili/pangu/gallery/v1/gallery.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package bilibili.pangu.gallery.v1;

@kotlin.jvm.JvmName("-initializelistOrderByMidReply")
public inline fun listOrderByMidReply(block: bilibili.pangu.gallery.v1.ListOrderByMidReplyKt.Dsl.() -> kotlin.Unit): bilibili.pangu.gallery.v1.ListOrderByMidReply =
  bilibili.pangu.gallery.v1.ListOrderByMidReplyKt.Dsl._create(bilibili.pangu.gallery.v1.ListOrderByMidReply.newBuilder()).apply { block() }._build()
/**
 * ```
 * ```
 *
 * Protobuf type `bilibili.pangu.gallery.v1.ListOrderByMidReply`
 */
public object ListOrderByMidReplyKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: bilibili.pangu.gallery.v1.ListOrderByMidReply.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: bilibili.pangu.gallery.v1.ListOrderByMidReply.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): bilibili.pangu.gallery.v1.ListOrderByMidReply = _builder.build()

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class OrdersProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * ```
     * ```
     *
     * `repeated .bilibili.pangu.gallery.v1.Order orders = 1;`
     */
     public val orders: com.google.protobuf.kotlin.DslList<bilibili.pangu.gallery.v1.Order, OrdersProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.getOrdersList()
      )
    /**
     * ```
     * ```
     *
     * `repeated .bilibili.pangu.gallery.v1.Order orders = 1;`
     * @param value The orders to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addOrders")
    public fun com.google.protobuf.kotlin.DslList<bilibili.pangu.gallery.v1.Order, OrdersProxy>.add(value: bilibili.pangu.gallery.v1.Order) {
      _builder.addOrders(value)
    }
    /**
     * ```
     * ```
     *
     * `repeated .bilibili.pangu.gallery.v1.Order orders = 1;`
     * @param value The orders to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignOrders")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<bilibili.pangu.gallery.v1.Order, OrdersProxy>.plusAssign(value: bilibili.pangu.gallery.v1.Order) {
      add(value)
    }
    /**
     * ```
     * ```
     *
     * `repeated .bilibili.pangu.gallery.v1.Order orders = 1;`
     * @param values The orders to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllOrders")
    public fun com.google.protobuf.kotlin.DslList<bilibili.pangu.gallery.v1.Order, OrdersProxy>.addAll(values: kotlin.collections.Iterable<bilibili.pangu.gallery.v1.Order>) {
      _builder.addAllOrders(values)
    }
    /**
     * ```
     * ```
     *
     * `repeated .bilibili.pangu.gallery.v1.Order orders = 1;`
     * @param values The orders to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllOrders")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<bilibili.pangu.gallery.v1.Order, OrdersProxy>.plusAssign(values: kotlin.collections.Iterable<bilibili.pangu.gallery.v1.Order>) {
      addAll(values)
    }
    /**
     * ```
     * ```
     *
     * `repeated .bilibili.pangu.gallery.v1.Order orders = 1;`
     * @param index The index to set the value at.
     * @param value The orders to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setOrders")
    public operator fun com.google.protobuf.kotlin.DslList<bilibili.pangu.gallery.v1.Order, OrdersProxy>.set(index: kotlin.Int, value: bilibili.pangu.gallery.v1.Order) {
      _builder.setOrders(index, value)
    }
    /**
     * ```
     * ```
     *
     * `repeated .bilibili.pangu.gallery.v1.Order orders = 1;`
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearOrders")
    public fun com.google.protobuf.kotlin.DslList<bilibili.pangu.gallery.v1.Order, OrdersProxy>.clear() {
      _builder.clearOrders()
    }


    /**
     * ```
     * ```
     *
     * `int64 anchor_id = 2;`
     */
    public var anchorId: kotlin.Long
      @JvmName("getAnchorId")
      get() = _builder.getAnchorId()
      @JvmName("setAnchorId")
      set(value) {
        _builder.setAnchorId(value)
      }
    /**
     * ```
     * ```
     *
     * `int64 anchor_id = 2;`
     */
    public fun clearAnchorId() {
      _builder.clearAnchorId()
    }

    /**
     * ```
     * ```
     *
     * `bool end = 3;`
     */
    public var end: kotlin.Boolean
      @JvmName("getEnd")
      get() = _builder.getEnd()
      @JvmName("setEnd")
      set(value) {
        _builder.setEnd(value)
      }
    /**
     * ```
     * ```
     *
     * `bool end = 3;`
     */
    public fun clearEnd() {
      _builder.clearEnd()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun bilibili.pangu.gallery.v1.ListOrderByMidReply.copy(block: `bilibili.pangu.gallery.v1`.ListOrderByMidReplyKt.Dsl.() -> kotlin.Unit): bilibili.pangu.gallery.v1.ListOrderByMidReply =
  `bilibili.pangu.gallery.v1`.ListOrderByMidReplyKt.Dsl._create(this.toBuilder()).apply { block() }._build()

